//! Module declarations for `net.minecraft.client.model.object` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod armorstand;
pub mod banner;
pub mod bell;
pub mod boat;
pub mod book;
pub mod cart;
pub mod chest;
pub mod crystal;
pub mod equipment;
pub mod leash;
pub mod projectile;
pub mod skull;
pub mod statue;
