//! Module declarations for `net.minecraft.world.level.block.state.properties` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AttachFace;
pub mod BambooLeaves;
pub mod BedPart;
pub mod BellAttachType;
pub mod BlockSetType;
pub mod BlockStateProperties;
pub mod BooleanProperty;
pub mod ChestType;
pub mod ComparatorMode;
pub mod CreakingHeartState;
pub mod DoorHingeSide;
pub mod DoubleBlockHalf;
pub mod EnumProperty;
pub mod Half;
pub mod IntegerProperty;
pub mod NoteBlockInstrument;
pub mod PistonType;
pub mod PotentSulfurState;
pub mod Property;
pub mod RailShape;
pub mod RedstoneSide;
pub mod RotationSegment;
pub mod SculkSensorPhase;
pub mod SideChainPart;
pub mod SlabType;
pub mod SpeleothemThickness;
pub mod StairsShape;
pub mod StructureMode;
pub mod TestBlockMode;
pub mod Tilt;
pub mod WallSide;
pub mod WoodType;
#[path = "package-info.rs"]
pub mod package_info;
