//! Module declarations for `net.minecraft.network.chat.contents.data` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BlockDataSource;
pub mod DataSource;
pub mod DataSources;
pub mod EntityDataSource;
pub mod StorageDataSource;
#[path = "package-info.rs"]
pub mod package_info;
