//! Module declarations for `com.mojang.realmsclient` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod client;
pub mod dto;
pub mod exception;
pub mod gui;
pub mod util;

pub mod RealmsAvailability;
pub mod RealmsMainScreen;
pub mod Unit;
#[path = "package-info.rs"]
pub mod package_info;
