//! Module declarations for `net.minecraft.client.renderer.feature` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod phase;
pub mod submit;

pub mod BlockModelFeatureRenderer;
pub mod CustomFeatureRenderer;
pub mod FeatureFrameContext;
pub mod FeatureRenderDispatcher;
pub mod FeatureRenderer;
pub mod FeatureRendererMap;
pub mod FeatureRendererType;
pub mod FlameFeatureRenderer;
pub mod GizmoFeatureRenderer;
pub mod ItemFeatureRenderer;
pub mod LeashFeatureRenderer;
pub mod ModelFeatureRenderer;
pub mod MovingBlockFeatureRenderer;
pub mod NameTagFeatureRenderer;
pub mod QuadParticleFeatureRenderer;
pub mod RenderTypeFeatureRenderer;
pub mod ShadowFeatureRenderer;
pub mod ShapeOutlineFeatureRenderer;
pub mod TextFeatureRenderer;
#[path = "package-info.rs"]
pub mod package_info;
