//! Module declarations for `net.minecraft.network.codec` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod ByteBufCodecs;
pub mod IdDispatchCodec;
pub mod StreamCodec;
pub mod StreamDecoder;
pub mod StreamEncoder;
pub mod StreamMemberEncoder;
#[path = "package-info.rs"]
pub mod package_info;
