//! Module declarations for `net.minecraft.client.model.animal.pig` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BabyPigModel;
pub mod ColdPigModel;
pub mod PigModel;
#[path = "package-info.rs"]
pub mod package_info;
