//! Module declarations for `net.minecraft.server.dialog` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod action;
pub mod body;
#[path = "input/mod.rs"]
pub mod input;

pub mod ActionButton;
pub mod ButtonListDialog;
pub mod CommonButtonData;
pub mod CommonDialogData;
pub mod ConfirmationDialog;
pub mod Dialog;
pub mod DialogAction;
pub mod DialogListDialog;
pub mod DialogTypes;
pub mod Dialogs;
#[path = "Input.rs"]
pub mod Input;
pub mod MultiActionDialog;
pub mod NoticeDialog;
pub mod ServerLinksDialog;
pub mod SimpleDialog;
#[path = "package-info.rs"]
pub mod package_info;
