//! Module declarations for `net.minecraft.server.bossevents` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod CustomBossEvent;
pub mod CustomBossEvents;
#[path = "package-info.rs"]
pub mod package_info;
