//! Module declarations for `net.minecraft.world.entity.animal.armadillo` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod Armadillo;
pub mod ArmadilloAi;
#[path = "package-info.rs"]
pub mod package_info;
