//! Module declarations for `net.minecraft.client.telemetry` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod events;

pub mod ClientTelemetryManager;
pub mod TelemetryEventInstance;
pub mod TelemetryEventLog;
pub mod TelemetryEventLogger;
pub mod TelemetryEventSender;
pub mod TelemetryEventType;
pub mod TelemetryLogManager;
pub mod TelemetryProperty;
pub mod TelemetryPropertyMap;
pub mod WorldSessionTelemetryManager;
#[path = "package-info.rs"]
pub mod package_info;
