//! Module declarations for `net.minecraft.client.renderer.item` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod properties;

pub mod BundleSelectedItemSpecialRenderer;
pub mod ClientItem;
pub mod CompositeModel;
pub mod ConditionalItemModel;
pub mod CuboidItemModelWrapper;
pub mod EmptyModel;
pub mod ItemModel;
pub mod ItemModelResolver;
pub mod ItemModels;
pub mod ItemStackRenderState;
pub mod MissingItemModel;
pub mod ModelRenderProperties;
pub mod RangeSelectItemModel;
pub mod SelectItemModel;
pub mod SpecialModelWrapper;
pub mod TrackingItemStackRenderState;
#[path = "package-info.rs"]
pub mod package_info;
