//! Module declarations for `net.minecraft.world.item.enchantment.providers` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod EnchantmentProvider;
pub mod EnchantmentProviderTypes;
pub mod EnchantmentsByCost;
pub mod EnchantmentsByCostWithDifficulty;
pub mod SingleEnchantment;
pub mod VanillaEnchantmentProviders;
#[path = "package-info.rs"]
pub mod package_info;
