//! Module declarations for `net.minecraft.client.gui.font` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod glyphs;
pub mod providers;

pub mod ActiveArea;
pub mod AllMissingGlyphProvider;
pub mod AtlasGlyphProvider;
pub mod CodepointMap;
pub mod EmptyArea;
pub mod FontManager;
pub mod FontOption;
pub mod FontSet;
pub mod FontTexture;
pub mod GlyphRenderTypes;
pub mod GlyphStitcher;
pub mod PlainTextRenderable;
pub mod PlayerGlyphProvider;
pub mod SingleSpriteSource;
pub mod TextFieldHelper;
pub mod TextRenderable;
#[path = "package-info.rs"]
pub mod package_info;
