//! Module declarations for `net.minecraft.world.level.levelgen.structure.templatesystem.rule.blockentity` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AppendLoot;
pub mod AppendStatic;
pub mod Clear;
pub mod Passthrough;
pub mod RuleBlockEntityModifier;
pub mod RuleBlockEntityModifierType;
#[path = "package-info.rs"]
pub mod package_info;
