//! Module declarations for `com.mojang.realmsclient.gui.screens` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod configuration;

pub mod AddRealmPopupScreen;
pub mod RealmsBrokenWorldScreen;
pub mod RealmsClientOutdatedScreen;
pub mod RealmsConfirmScreen;
pub mod RealmsCreateRealmScreen;
pub mod RealmsDownloadLatestWorldScreen;
pub mod RealmsGenericErrorScreen;
pub mod RealmsLongRunningMcoConnectTaskScreen;
pub mod RealmsLongRunningMcoTaskScreen;
pub mod RealmsNotificationsScreen;
pub mod RealmsParentalConsentScreen;
pub mod RealmsPendingInvitesScreen;
pub mod RealmsPopups;
pub mod RealmsResetWorldScreen;
pub mod RealmsSelectFileToUploadScreen;
pub mod RealmsSelectWorldTemplateScreen;
pub mod RealmsTermsScreen;
pub mod RealmsUploadScreen;
pub mod UploadResult;
#[path = "package-info.rs"]
pub mod package_info;
