//! Module declarations for `net.minecraft.util.profiling.jfr.stats` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod ChunkGenStat;
pub mod ChunkIdentification;
pub mod CpuLoadStat;
pub mod FileIOStat;
pub mod FpsStat;
pub mod GcHeapStat;
pub mod IoSummary;
pub mod PacketIdentification;
pub mod StructureGenStat;
pub mod ThreadAllocationStat;
pub mod TickTimeStat;
pub mod TimedStat;
pub mod TimedStatSummary;
#[path = "package-info.rs"]
pub mod package_info;
