//! Module declarations for `net.minecraft.world.item.consume_effects` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod ApplyStatusEffectsConsumeEffect;
pub mod ClearAllStatusEffectsConsumeEffect;
pub mod ConsumeEffect;
pub mod PlaySoundConsumeEffect;
pub mod RemoveStatusEffectsConsumeEffect;
pub mod TeleportRandomlyConsumeEffect;
#[path = "package-info.rs"]
pub mod package_info;
