//! Module declarations for `net.minecraft.client.renderer.block.model.properties.select` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod DisplayContext;
pub mod SelectBlockModelProperty;
#[path = "package-info.rs"]
pub mod package_info;
