//! Module declarations for `net.minecraft.client.gui.screens.inventory.tooltip` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BelowOrAboveWidgetTooltipPositioner;
pub mod ClientActivePlayersTooltip;
pub mod ClientBundleTooltip;
pub mod ClientTextTooltip;
pub mod ClientTooltipComponent;
pub mod ClientTooltipPositioner;
pub mod DefaultTooltipPositioner;
pub mod MenuTooltipPositioner;
pub mod TooltipRenderUtil;
#[path = "package-info.rs"]
pub mod package_info;
