//! Module declarations for `net.minecraft.client.renderer.debug` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BeeDebugRenderer;
pub mod BrainDebugRenderer;
pub mod BreezeDebugRenderer;
pub mod ChunkBorderRenderer;
pub mod ChunkCullingDebugRenderer;
pub mod ChunkDebugRenderer;
pub mod CollisionBoxRenderer;
pub mod DebugRenderer;
pub mod EntityBlockIntersectionDebugRenderer;
pub mod EntityHitboxDebugRenderer;
pub mod GameEventListenerRenderer;
pub mod GameTestBlockHighlightRenderer;
pub mod GoalSelectorDebugRenderer;
pub mod HeightMapRenderer;
pub mod LightDebugRenderer;
pub mod LightSectionDebugRenderer;
pub mod NeighborsUpdateRenderer;
pub mod OctreeDebugRenderer;
pub mod PathfindingRenderer;
pub mod PoiDebugRenderer;
pub mod RaidDebugRenderer;
pub mod RedstoneWireOrientationsRenderer;
pub mod SolidFaceRenderer;
pub mod StructureRenderer;
pub mod SupportBlockRenderer;
pub mod VillageSectionsDebugRenderer;
pub mod WaterDebugRenderer;
#[path = "package-info.rs"]
pub mod package_info;
