//! Module declarations for `com.mojang.realmsclient.dto` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod Backup;
pub mod BackupList;
pub mod Exclude;
pub mod GuardedSerializer;
pub mod Ops;
pub mod OutboundPlayer;
pub mod PendingInvite;
pub mod PendingInvitesList;
pub mod PingResult;
pub mod PlayerInfo;
pub mod PreferredRegionsDto;
pub mod RealmsConfigurationDto;
pub mod RealmsDescriptionDto;
pub mod RealmsJoinInformation;
pub mod RealmsNews;
pub mod RealmsNotification;
pub mod RealmsRegion;
pub mod RealmsServer;
pub mod RealmsServerList;
pub mod RealmsServerPlayerLists;
pub mod RealmsSetting;
pub mod RealmsSlot;
pub mod RealmsSlotUpdateDto;
pub mod RealmsText;
pub mod RealmsWorldOptions;
pub mod RealmsWorldResetDto;
pub mod ReflectionBasedSerialization;
pub mod RegionDataDto;
pub mod RegionPingResult;
pub mod RegionSelectionPreference;
pub mod RegionSelectionPreferenceDto;
pub mod ServiceQuality;
pub mod Subscription;
pub mod UploadInfo;
pub mod ValueObject;
pub mod WorldDownload;
pub mod WorldTemplate;
pub mod WorldTemplatePaginatedList;
#[path = "package-info.rs"]
pub mod package_info;
