//! Module declarations for `net.minecraft.client.resources.model.sprite` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AtlasManager;
pub mod Material;
pub mod MaterialBaker;
pub mod SpriteGetter;
pub mod SpriteId;
pub mod TextureSlots;
#[path = "package-info.rs"]
pub mod package_info;
