//! Module declarations for `net.minecraft.world.level.storage.loot.predicates` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AllOfCondition;
pub mod AnyOfCondition;
pub mod BonusLevelTableCondition;
pub mod CompositeLootItemCondition;
pub mod ConditionReference;
pub mod ConditionUserBuilder;
pub mod DamageSourceCondition;
pub mod EnchantmentActiveCheck;
pub mod EntityHasScoreCondition;
pub mod EnvironmentAttributeCheck;
pub mod ExplosionCondition;
pub mod InvertedLootItemCondition;
pub mod LocationCheck;
pub mod LootItemBlockStatePropertyCondition;
pub mod LootItemCondition;
pub mod LootItemConditions;
pub mod LootItemEntityPropertyCondition;
pub mod LootItemKilledByPlayerCondition;
pub mod LootItemRandomChanceCondition;
pub mod LootItemRandomChanceWithEnchantedBonusCondition;
pub mod MatchTool;
pub mod TimeCheck;
pub mod ValueCheckCondition;
pub mod WeatherCheck;
#[path = "package-info.rs"]
pub mod package_info;
