//! Module declarations for `net.minecraft.world` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod attribute;
pub mod clock;
pub mod damagesource;
pub mod effect;
pub mod entity;
pub mod flag;
pub mod food;
pub mod inventory;
pub mod item;
pub mod level;
pub mod phys;
pub mod scores;
pub mod ticks;
pub mod timeline;
pub mod waypoints;

pub mod BossEvent;
pub mod Clearable;
pub mod CompoundContainer;
pub mod Container;
pub mod ContainerHelper;
pub mod Containers;
pub mod Difficulty;
pub mod DifficultyInstance;
pub mod InteractionHand;
pub mod InteractionResult;
pub mod ItemStackWithSlot;
pub mod LockCode;
pub mod MenuProvider;
pub mod Nameable;
pub mod RandomSequence;
pub mod RandomSequences;
pub mod RandomizableContainer;
pub mod SimpleContainer;
pub mod SimpleMenuProvider;
pub mod Stopwatch;
pub mod Stopwatches;
pub mod TickRateManager;
pub mod WorldlyContainer;
pub mod WorldlyContainerHolder;
#[path = "package-info.rs"]
pub mod package_info;
