//! Module declarations for `net.minecraft.world.level.levelgen.feature.trunkplacers` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BendingTrunkPlacer;
pub mod CherryTrunkPlacer;
pub mod DarkOakTrunkPlacer;
pub mod FancyTrunkPlacer;
pub mod ForkingTrunkPlacer;
pub mod GiantTrunkPlacer;
pub mod MegaJungleTrunkPlacer;
pub mod StraightTrunkPlacer;
pub mod TrunkPlacer;
pub mod TrunkPlacerType;
pub mod UpwardsBranchingTrunkPlacer;
#[path = "package-info.rs"]
pub mod package_info;
