//! Module declarations for `net.minecraft.commands.arguments.coordinates` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BlockPosArgument;
pub mod ColumnPosArgument;
pub mod Coordinates;
pub mod LocalCoordinates;
pub mod RotationArgument;
pub mod SwizzleArgument;
pub mod Vec2Argument;
pub mod Vec3Argument;
pub mod WorldCoordinate;
pub mod WorldCoordinates;
#[path = "package-info.rs"]
pub mod package_info;
