//! Module declarations for `net.minecraft.world.entity.animal.pig` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod Pig;
pub mod PigSoundVariant;
pub mod PigSoundVariants;
pub mod PigVariant;
pub mod PigVariants;
#[path = "package-info.rs"]
pub mod package_info;
