//! Module declarations for `com.mojang.blaze3d.buffers` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod GpuBuffer;
pub mod GpuBufferSlice;
pub mod GpuFence;
pub mod Std140Builder;
pub mod Std140SizeCalculator;
#[path = "package-info.rs"]
pub mod package_info;
