//! Module declarations for `net.minecraft.world.entity.animal.nautilus` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractNautilus;
pub mod Nautilus;
pub mod NautilusAi;
pub mod ZombieNautilus;
pub mod ZombieNautilusAi;
pub mod ZombieNautilusVariant;
pub mod ZombieNautilusVariants;
#[path = "package-info.rs"]
pub mod package_info;
