//! Module declarations for `net.minecraft.world.phys` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod shapes;

pub mod AABB;
pub mod BlockHitResult;
pub mod EntityHitResult;
pub mod HitResult;
pub mod Vec2;
pub mod Vec3;
#[path = "package-info.rs"]
pub mod package_info;
