//! Module declarations for `net.minecraft.references` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BlockIds;
pub mod BlockItemId;
pub mod BlockItemIds;
pub mod ItemIds;
#[path = "package-info.rs"]
pub mod package_info;
