//! Module declarations for `net.minecraft.world.level.levelgen.carver` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod CanyonCarverConfiguration;
pub mod CanyonWorldCarver;
pub mod CarverConfiguration;
pub mod CarverDebugSettings;
pub mod CarvingContext;
pub mod CaveCarverConfiguration;
pub mod CaveWorldCarver;
pub mod ConfiguredWorldCarver;
pub mod NetherWorldCarver;
pub mod WorldCarver;
#[path = "package-info.rs"]
pub mod package_info;
