//! Module declarations for `net.minecraft.client.gui.narration` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod NarratableEntry;
pub mod NarratedElementType;
pub mod NarrationElementOutput;
pub mod NarrationSupplier;
pub mod NarrationThunk;
pub mod ScreenNarrationCollector;
#[path = "package-info.rs"]
pub mod package_info;
