//! Module declarations for `net.minecraft.client.gui` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod components;
pub mod contextualbar;
#[path = "font/mod.rs"]
pub mod font;
pub mod layouts;
pub mod narration;
pub mod navigation;
pub mod render;
pub mod screens;
pub mod spectator;

pub mod ActiveTextCollector;
pub mod BundleMouseActions;
pub mod ComponentPath;
#[path = "Font.rs"]
pub mod Font;
pub mod GlyphSource;
pub mod Gui;
pub mod GuiGraphicsExtractor;
pub mod Hud;
pub mod ItemSlotMouseAction;
pub mod TextAlignment;
#[path = "package-info.rs"]
pub mod package_info;
