//! Module declarations for `net.minecraft.world.entity.npc.villager` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractVillager;
pub mod Villager;
pub mod VillagerData;
pub mod VillagerDataHolder;
pub mod VillagerProfession;
pub mod VillagerType;
#[path = "package-info.rs"]
pub mod package_info;
