//! Module declarations for `net.minecraft.world.entity.monster.breeze` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod Breeze;
pub mod BreezeAi;
pub mod BreezeUtil;
pub mod LongJump;
pub mod Shoot;
pub mod ShootWhenStuck;
pub mod Slide;
#[path = "package-info.rs"]
pub mod package_info;
