//! Module declarations for `net.minecraft.client.model` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod ambient;
pub mod animal;
pub mod effects;
pub mod geom;
pub mod monster;
pub mod npc;
pub mod object;
pub mod player;

pub mod AdultAndBabyModelPair;
pub mod AnimationUtils;
pub mod ArmedModel;
pub mod BabyModelTransform;
pub mod EntityModel;
pub mod HeadedModel;
pub mod HumanoidModel;
pub mod Model;
pub mod QuadrupedModel;
pub mod VillagerLikeModel;
#[path = "package-info.rs"]
pub mod package_info;
