//! Module declarations for `net.minecraft.client.resources.model` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod cuboid;
pub mod geometry;
pub mod sprite;

pub mod BlockStateDefinitions;
pub mod BlockStateModelLoader;
pub mod ClientItemInfoLoader;
pub mod EquipmentAssetManager;
pub mod EquipmentClientInfo;
pub mod ModelBaker;
pub mod ModelBakery;
pub mod ModelDebugName;
pub mod ModelDiscovery;
pub mod ModelGroupCollector;
pub mod ModelManager;
pub mod ResolvableModel;
pub mod ResolvedModel;
pub mod SimpleModelWrapper;
pub mod UnbakedModel;
#[path = "package-info.rs"]
pub mod package_info;
