//! Module declarations for `net.minecraft.client.model.animal` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod allay;
pub mod armadillo;
pub mod axolotl;
pub mod bee;
pub mod camel;
pub mod chicken;
pub mod cow;
pub mod dolphin;
pub mod equine;
pub mod feline;
pub mod fish;
pub mod fox;
pub mod frog;
pub mod ghast;
pub mod goat;
pub mod golem;
pub mod llama;
pub mod nautilus;
pub mod panda;
pub mod parrot;
pub mod pig;
pub mod polarbear;
pub mod rabbit;
pub mod sheep;
pub mod sniffer;
pub mod squid;
pub mod turtle;
pub mod wolf;

#[path = "package-info.rs"]
pub mod package_info;
