//! Module declarations for `net.minecraft.world.level.border` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BorderChangeListener;
pub mod BorderStatus;
pub mod WorldBorder;
#[path = "package-info.rs"]
pub mod package_info;
