//! Module declarations for `net.minecraft.world.level.levelgen.presets` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod WorldPreset;
pub mod WorldPresets;
#[path = "package-info.rs"]
pub mod package_info;
