//! Module declarations for `net.minecraft.world.entity.projectile.throwableitemprojectile` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractThrownPotion;
pub mod Snowball;
pub mod ThrowableItemProjectile;
pub mod ThrownEgg;
pub mod ThrownEnderpearl;
pub mod ThrownExperienceBottle;
pub mod ThrownLingeringPotion;
pub mod ThrownSplashPotion;
#[path = "package-info.rs"]
pub mod package_info;
