//! Module declarations for `net.minecraft.world.item.enchantment.effects` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AddValue;
pub mod AllOf;
pub mod ApplyEntityImpulse;
pub mod ApplyExhaustion;
pub mod ApplyMobEffect;
pub mod ChangeItemDamage;
pub mod DamageEntity;
pub mod DamageImmunity;
pub mod EnchantmentAttributeEffect;
pub mod EnchantmentEntityEffect;
pub mod EnchantmentLocationBasedEffect;
pub mod EnchantmentValueEffect;
pub mod ExplodeEffect;
pub mod Ignite;
pub mod MultiplyValue;
pub mod PlaySoundEffect;
pub mod RemoveBinomial;
pub mod ReplaceBlock;
pub mod ReplaceDisk;
pub mod RunFunction;
pub mod ScaleExponentially;
pub mod SetBlockProperties;
pub mod SetValue;
pub mod SpawnParticlesEffect;
pub mod SummonEntityEffect;
#[path = "package-info.rs"]
pub mod package_info;
