//! Module declarations for `net.minecraft.client.model.animal.cow` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BabyCowModel;
pub mod ColdCowModel;
pub mod CowModel;
pub mod WarmCowModel;
#[path = "package-info.rs"]
pub mod package_info;
