//! Module declarations for `net.minecraft.util.parsing` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod packrat;

#[path = "package-info.rs"]
pub mod package_info;
