//! Module declarations for `net.minecraft.resources` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod DelegatingOps;
pub mod DependantName;
pub mod FileToIdConverter;
pub mod HolderSetCodec;
pub mod Identifier;
pub mod NetworkRegistryLoadTask;
pub mod RegistryDataLoader;
pub mod RegistryFileCodec;
pub mod RegistryFixedCodec;
pub mod RegistryLoadTask;
pub mod RegistryOps;
pub mod RegistryValidator;
pub mod ResourceKey;
pub mod ResourceManagerRegistryLoadTask;
#[path = "package-info.rs"]
pub mod package_info;
