//! Module declarations for `com.mojang.blaze3d.resource` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod CrossFrameResourcePool;
pub mod GraphicsResourceAllocator;
pub mod RenderTargetDescriptor;
pub mod ResourceDescriptor;
pub mod ResourceHandle;
#[path = "package-info.rs"]
pub mod package_info;
