//! Module declarations for `com.mojang.blaze3d.platform` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod cursor;

pub mod BlendFactor;
pub mod BlendOp;
pub mod ClientShutdownWatchdog;
pub mod ClipboardManager;
pub mod CompareOp;
pub mod DebugMemoryUntracker;
pub mod DisplayData;
pub mod FramerateLimitTracker;
pub mod GLX;
pub mod IconSet;
pub mod InputConstants;
pub mod Lighting;
pub mod MacosUtil;
pub mod MessageBox;
pub mod Monitor;
pub mod MonitorManager;
pub mod NativeImage;
pub mod NativeLibrariesBootstrap;
pub mod PolygonMode;
pub mod TextInputManager;
pub mod TextureUtil;
pub mod Transparency;
pub mod VideoMode;
pub mod Window;
pub mod WindowEventHandler;
#[path = "package-info.rs"]
pub mod package_info;
