//! Module declarations for `net.minecraft.world.item.crafting` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod display;

pub mod AbstractCookingRecipe;
pub mod BannerDuplicateRecipe;
pub mod BlastingRecipe;
pub mod BookCloningRecipe;
pub mod CampfireCookingRecipe;
pub mod CookingBookCategory;
pub mod CraftingBookCategory;
pub mod CraftingInput;
pub mod CraftingRecipe;
pub mod CustomRecipe;
pub mod DecoratedPotRecipe;
pub mod DyeRecipe;
pub mod ExtendedRecipeBookCategory;
pub mod FireworkRocketRecipe;
pub mod FireworkStarFadeRecipe;
pub mod FireworkStarRecipe;
pub mod ImbueRecipe;
pub mod Ingredient;
pub mod MapExtendingRecipe;
pub mod NormalCraftingRecipe;
pub mod PlacementInfo;
pub mod Recipe;
pub mod RecipeAccess;
pub mod RecipeBookCategories;
pub mod RecipeBookCategory;
pub mod RecipeCache;
pub mod RecipeHolder;
pub mod RecipeInput;
pub mod RecipeManager;
pub mod RecipeMap;
pub mod RecipePropertySet;
pub mod RecipeSerializer;
pub mod RecipeSerializers;
pub mod RecipeType;
pub mod RepairItemRecipe;
pub mod SelectableRecipe;
pub mod ShapedRecipe;
pub mod ShapedRecipePattern;
pub mod ShapelessRecipe;
pub mod ShieldDecorationRecipe;
pub mod SimpleSmithingRecipe;
pub mod SingleItemRecipe;
pub mod SingleRecipeInput;
pub mod SmeltingRecipe;
pub mod SmithingRecipe;
pub mod SmithingRecipeInput;
pub mod SmithingTransformRecipe;
pub mod SmithingTrimRecipe;
pub mod SmokingRecipe;
pub mod StonecutterRecipe;
pub mod TransmuteRecipe;
#[path = "package-info.rs"]
pub mod package_info;
