//! Module declarations for `net.minecraft.world.entity.animal.frog` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod Frog;
pub mod FrogAi;
pub mod FrogVariant;
pub mod FrogVariants;
pub mod ShootTongue;
pub mod Tadpole;
pub mod TadpoleAi;
#[path = "package-info.rs"]
pub mod package_info;
