//! Module declarations for `net.minecraft.client.renderer.state.gui` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod pip;

pub mod BlitRenderState;
pub mod ColoredRectangleRenderState;
pub mod GlyphRenderState;
pub mod GuiElementRenderState;
pub mod GuiItemRenderState;
pub mod GuiRenderState;
pub mod GuiTextRenderState;
pub mod PanoramaRenderState;
pub mod ScreenArea;
pub mod TiledBlitRenderState;
#[path = "package-info.rs"]
pub mod package_info;
