//! Module declarations for `com.mojang.blaze3d.vertex` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BufferBuilder;
pub mod ByteBufferBuilder;
pub mod CompactVectorArray;
pub mod DefaultVertexFormat;
pub mod MeshData;
pub mod PoseStack;
pub mod QuadInstance;
pub mod SheetedDecalTextureGenerator;
pub mod StagingBuffer;
pub mod TlsfAllocator;
pub mod UberGpuBuffer;
pub mod VertexConsumer;
pub mod VertexFormat;
pub mod VertexFormatElement;
pub mod VertexSorting;
#[path = "package-info.rs"]
pub mod package_info;
