//! Module declarations for `net.minecraft.world.entity.ai.sensing` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AdultSensor;
pub mod AdultSensorAnyType;
pub mod AxolotlAttackablesSensor;
pub mod BreezeAttackEntitySensor;
pub mod DummySensor;
pub mod FrogAttackablesSensor;
pub mod GolemSensor;
pub mod HoglinSpecificSensor;
pub mod HurtBySensor;
pub mod IsInWaterSensor;
pub mod MobSensor;
pub mod NearestBedSensor;
pub mod NearestItemSensor;
pub mod NearestLivingEntitySensor;
pub mod NearestVisibleLivingEntitySensor;
pub mod PiglinBruteSpecificSensor;
pub mod PiglinSpecificSensor;
pub mod PlayerSensor;
pub mod SecondaryPoiSensor;
pub mod Sensing;
pub mod Sensor;
pub mod SensorType;
pub mod TemptingSensor;
pub mod VillagerBabiesSensor;
pub mod VillagerHostilesSensor;
pub mod WardenEntitySensor;
#[path = "package-info.rs"]
pub mod package_info;
