//! Module declarations for `net.minecraft.client.color.item` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod Constant;
pub mod CustomModelDataSource;
pub mod Dye;
pub mod Firework;
pub mod GrassColorSource;
pub mod ItemTintSource;
pub mod ItemTintSources;
pub mod MapColor;
pub mod Potion;
pub mod TeamColor;
#[path = "package-info.rs"]
pub mod package_info;
