//! Module declarations for `net.minecraft.client.gui.components.events` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractContainerEventHandler;
pub mod ContainerEventHandler;
pub mod GuiEventListener;
#[path = "package-info.rs"]
pub mod package_info;
