//! Module declarations for `net.minecraft.core.component` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod predicates;

pub mod DataComponentExactPredicate;
pub mod DataComponentGetter;
pub mod DataComponentHolder;
pub mod DataComponentInitializers;
pub mod DataComponentLookup;
pub mod DataComponentMap;
pub mod DataComponentPatch;
pub mod DataComponentType;
pub mod DataComponents;
pub mod PatchedDataComponentMap;
pub mod TypedDataComponent;
#[path = "package-info.rs"]
pub mod package_info;
