//! Module declarations for `net.minecraft.client.gui.screens.options` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod controls;

pub mod AccessibilityOptionsScreen;
pub mod ChatOptionsScreen;
pub mod DifficultyButtons;
pub mod FontOptionsScreen;
pub mod HasDifficultyReaction;
pub mod HasGamemasterPermissionReaction;
pub mod InWorldGameRulesScreen;
pub mod LanguageSelectScreen;
pub mod MouseSettingsScreen;
pub mod OnlineOptionsScreen;
pub mod OptionsScreen;
pub mod OptionsSubScreen;
pub mod SkinCustomizationScreen;
pub mod SoundOptionsScreen;
pub mod UnsupportedGraphicsWarningScreen;
pub mod VideoSettingsScreen;
pub mod WorldOptionsScreen;
#[path = "package-info.rs"]
pub mod package_info;
