//! Module declarations for `net.minecraft.world.food` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod FoodConstants;
pub mod FoodData;
pub mod FoodProperties;
pub mod Foods;
#[path = "package-info.rs"]
pub mod package_info;
