//! Module declarations for `com.mojang.realmsclient.gui.screens.configuration` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod RealmsBackupInfoScreen;
pub mod RealmsBackupScreen;
pub mod RealmsConfigurationTab;
pub mod RealmsConfigureWorldScreen;
pub mod RealmsInviteScreen;
pub mod RealmsPlayersTab;
pub mod RealmsPreferredRegionSelectionScreen;
pub mod RealmsSettingsTab;
pub mod RealmsSlotOptionsScreen;
pub mod RealmsSubscriptionTab;
pub mod RealmsWorldsTab;
#[path = "package-info.rs"]
pub mod package_info;
