//! Module declarations for `net.minecraft.client.renderer.block` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod dispatch;
pub mod model;

pub mod BlockAndTintGetter;
pub mod BlockModelLighter;
pub mod BlockModelRenderState;
pub mod BlockModelResolver;
pub mod BlockModelSet;
pub mod BlockQuadOutput;
pub mod BlockStateModelSet;
pub mod BuiltInBlockModels;
pub mod FluidModel;
pub mod FluidRenderer;
pub mod FluidStateModelSet;
pub mod LoadedBlockModels;
pub mod ModelBlockRenderer;
pub mod MovingBlockRenderState;
pub mod SelectBlockModel;
#[path = "package-info.rs"]
pub mod package_info;
