#!/usr/bin/env python3
"""
mirror.py -- Generate the Rust mirror of minecraft-decompiled/.

Reads only from minecraft-decompiled/ (never writes to it) and creates/updates
files under "Converted Minecraft in rust/".

Guarantees
----------
* One .java file  ->  one .rs file at the SAME relative path, SAME base name.
* Existing .rs files are NEVER overwritten (a hand-ported file survives).
* Idempotent: running twice changes nothing on disk.
* Writes/updates _porting/MANIFEST.csv.

Usage
-----
    python "Converted Minecraft in rust/_porting/tools/mirror.py"
    python "Converted Minecraft in rust/_porting/tools/mirror.py" --check
        --check  = dry run, print a summary, touch nothing, exit 1 if drift.
"""

from __future__ import annotations

import argparse
import csv
import os
import re
import sys
from collections import OrderedDict

# --------------------------------------------------------------------------
# Paths (quoted everywhere because the folder name contains spaces)
# --------------------------------------------------------------------------
HERE = os.path.dirname(os.path.abspath(__file__))                       # .../_porting/tools
RUST_ROOT = os.path.abspath(os.path.join(HERE, os.pardir, os.pardir))    # .../Converted Minecraft in rust
REPO_ROOT = os.path.abspath(os.path.join(RUST_ROOT, os.pardir))         # repo root
SRC = os.path.join(REPO_ROOT, "minecraft-decompiled")
PORTING = os.path.join(RUST_ROOT, "_porting")
MANIFEST = os.path.join(PORTING, "MANIFEST.csv")

CRATE_NAME = "minecraft_rust"

CARGO_TOML = """\
# Generated by _porting/tools/mirror.py -- one crate, mirrored layout.
[package]
name = "minecraft_rust"
version = "0.1.0"
edition = "2021"
publish = false
description = "Bit-exact Rust translation of Minecraft 26.2 (Fabric split client jar)"

[lib]
name = "minecraft_rust"
path = "lib.rs"

# Parity tests against the Java oracle golden data (see _porting/java-oracle).
# Paths are relative to the crate root, i.e. "Converted Minecraft in rust/".
#
# NOTE: this file is regenerated on every mirror.py run, so a new parity test must be
# added HERE, not by editing Cargo.toml directly. Adding it only to Cargo.toml works
# right up until the next `mirror.py` run silently drops it -- and the failure mode is
# "no test target named parity_X", which reads like a typo rather than a lost entry.
[[test]]
name = "parity_mth"
path = "_porting/tests/parity_mth.rs"

[[test]]
name = "parity_core"
path = "_porting/tests/parity_core.rs"

[[test]]
name = "parity_random"
path = "_porting/tests/parity_random.rs"

[[test]]
name = "parity_batch2"
path = "_porting/tests/parity_batch2.rs"

[profile.dev]
# 7055 mirrored modules: keep debug info out of the way.
debug = 0
"""

LIB_RS = """\
//! Rust translation of Minecraft 26.2 (Fabric Loom split-environment *client* jar).
//!
//! Layout rule: the folder tree below this crate root is a byte-for-byte mirror of
//! `minecraft-decompiled/`. Every `.java` file has exactly one `.rs` sibling with the
//! same base name (`Mth.java` -> `Mth.rs`). Do NOT flatten, rename or reorganise.
//!
//! Prime directive: NO GAMEPLAY CHANGES. Same inputs, same outputs, tick for tick,
//! bit for bit. Vanilla bugs are mechanics and must be preserved.
//!
//! Generated by _porting/tools/mirror.py.

#![allow(non_snake_case, non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(unused_imports, unused_variables, unused_mut, dead_code, unused_parens)]
#![allow(unreachable_code, unused_assignments, unused_labels)]
#![allow(clippy::all)]

pub mod com;
pub mod net;

/// Java standard-library equivalents (Math.floorMod, String.hashCode, the
/// java.util.Random LCG, MD5, the golden-data reader). These have no `.java`
/// counterpart in minecraft-decompiled/, so Rule 3 puts them in `_porting/`; we
/// still expose them as a normal crate module so ported game code can `use`
/// them without path gymnastics. See _porting/DESIGN_DECISIONS.md (#javacompat).
#[path = "_porting/javacompat/mod.rs"]
pub mod javacompat;
"""

MOD_RS_HEADER = "//! Module declarations for `{pkg}` -- generated by _porting/tools/mirror.py.\n"

# --------------------------------------------------------------------------
# Java source parsing (deliberately shallow: we only need names + LOC)
# --------------------------------------------------------------------------
RE_PACKAGE = re.compile(r"^\s*package\s+([\w.]+)\s*;", re.M)

# Top-level type declaration: modifiers then class/interface/enum/record/@interface then Name
RE_TOPLEVEL_TYPE = re.compile(
    r"^(?:@\w+(?:\([^)]*\))?\s+)*"          # annotations
    r"(?:public\s+|final\s+|abstract\s+|sealed\s+|non-sealed\s+|strictfp\s+)*"
    r"(class|interface|enum|record|@interface)\s+(\w+)",
    re.M,
)

# Nested type declaration (must be indented -> inside a type body)
RE_NESTED_TYPE = re.compile(
    r"^\t+(?:@\w+(?:\([^)]*\))?\s+)*"
    r"(?:public\s+|final\s+|abstract\s+|sealed\s+|non-sealed\s+|strictfp\s+|static\s+)*"
    r"(class|interface|enum|record|@interface)\s+(\w+)",
    re.M,
)

RE_ANON = re.compile(r"\bnew\s+[A-Za-z_$][\w.$]*\s*(?:<[^;()]*?>)?\s*\([^;]*?\)\s*\{\s*$", re.M)
RE_IMPORT_MC = re.compile(r"^\s*import\s+(?:static\s+)?(net\.minecraft\.[\w.]+|com\.mojang\.[\w.]+)\s*;", re.M)
RE_IMPORT_MC_STATIC = re.compile(r"^\s*import\s+static\s+(net\.minecraft\.[\w.]+|com\.mojang\.[\w.]+)\s*\.", re.M)

IDENT = re.compile(r"^[A-Za-z_$][\w$]*$")


def count_loc(path: str) -> int:
    """Physical lines, 1-based count (same as `wc -l` for LF-terminated files)."""
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        return sum(1 for _ in fh)


def read(path: str) -> str:
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        return fh.read()


def strip_comments(text: str) -> str:
    """Remove /* */ and // comments so we don't match types inside javadoc."""
    out = []
    i, n = 0, len(text)
    while i < n:
        c = text[i]
        if c == '"':
            j = i + 1
            while j < n and text[j] != '"':
                if text[j] == "\\":
                    j += 1
                j += 1
            out.append(text[i:j + 1])
            i = j + 1
            continue
        if c == "'":
            j = i + 1
            while j < n and text[j] != "'":
                if text[j] == "\\":
                    j += 1
                j += 1
            out.append(text[i:j + 1])
            i = j + 1
            continue
        if text.startswith("//", i):
            j = text.find("\n", i)
            i = n if j < 0 else j
            continue
        if text.startswith("/*", i):
            j = text.find("*/", i + 2)
            i = n if j < 0 else j + 2
            continue
        out.append(c)
        i += 1
    return "".join(out)


def analyse(java_path: str) -> dict:
    text = read(java_path)
    code = strip_comments(text)

    m = RE_PACKAGE.search(code)
    package = m.group(1) if m else ""

    types = []
    mm = RE_TOPLEVEL_TYPE.search(code)
    if mm:
        types.append(mm.group(2))
    for m2 in RE_NESTED_TYPE.finditer(code):
        types.append(m2.group(2))

    anon = len(RE_ANON.findall(code))

    return {
        "package": package,
        "types": types,
        "anon": anon,
        "imports": sorted(set(RE_IMPORT_MC.findall(code))),
        "static_imports": sorted(set(RE_IMPORT_MC_STATIC.findall(code))),
        "loc": count_loc(java_path),
    }


def class_name_to_rel(fqcn: str) -> str:
    """net.minecraft.util.Mth -> net/minecraft/util/Mth.java (no .java present check)."""
    return fqcn.replace(".", "/") + ".java"


def side_of(rel_java: str, info: dict) -> str:
    if "/client/" in "/" + rel_java or rel_java.startswith("client/"):
        return "client"
    if rel_java.startswith("com/mojang/blaze3d/") or rel_java.startswith("com/mojang/realmsclient/"):
        return "client"
    if "/server/" in "/" + rel_java or rel_java.startswith("server/"):
        return "server"
    if info["package"] == "com.mojang.math":
        return "common"
    return "common"


# --------------------------------------------------------------------------
# Rust module naming
# --------------------------------------------------------------------------
def rust_module_ident(base: str) -> str:
    """Java base name -> Rust module identifier. Only `package-info` needs work."""
    if IDENT.match(base):
        return base
    return base.replace("-", "_")


def mod_rs_body(dir_rel: str, files: list, subdirs: list, pkg: str) -> str:
    """`mod.rs` declares child modules only: sibling .rs files AND child folders.

    No game logic here, ever.

    Windows/macOS filesystems are case-insensitive, so a sibling file and a child
    folder whose names differ only in case (Java: `Font.java` next to `font/`) make
    rustc report E0761 "file for module found at both". For those (and only those)
    entries we emit an explicit `#[path]`, which bypasses rustc's file search. The
    on-disk names still match the Java names exactly.
    """
    entries = [(name, ident, name + ".rs", False) for name, ident in files]
    entries += [(name, ident, name + "/mod.rs", True) for name, ident in subdirs]

    lowered = {}
    for name, ident, path, _is_dir in entries:
        lowered.setdefault(ident.lower(), []).append((name, ident, path))

    forced = set()
    for group in lowered.values():
        if len(group) > 1:
            forced.update(path for _n, _i, path in group)

    def emit(name: str, ident: str, path: str, is_dir: bool) -> list:
        needs_path = path in forced or ident != name
        if needs_path:
            return [f'#[path = "{path}"]', f"pub mod {ident};"]
        return [f"pub mod {ident};"]

    lines = [MOD_RS_HEADER.format(pkg=pkg or "<crate root>"), "//",
             "// No game logic in mod.rs -- only child module declarations.",
             "// Child folders first, then sibling files (both mirror minecraft-decompiled/).", ""]
    for name, ident, path, is_dir in sorted((e for e in entries if e[3]), key=lambda e: e[0]):
        lines.extend(emit(name, ident, path, is_dir))
    if subdirs and files:
        lines.append("")
    for name, ident, path, is_dir in sorted((e for e in entries if not e[3]), key=lambda e: e[0]):
        lines.extend(emit(name, ident, path, is_dir))
    lines.append("")
    return "\n".join(lines)


def rs_header(java_rel: str, info: dict, status: str) -> str:
    names = list(info["types"])
    fqcns = [f"{info['package']}.{t}" if info["package"] else t for t in names]
    if info["anon"]:
        fqcns.append(f"{info['types'][0] if info['types'] else '?'}::<{info['anon']} anonymous class(es)>")
    body = ", ".join(fqcns) if fqcns else "(none)"
    return (
        f"//! Port of: {java_rel}\n"
        f"//! Java class(es): {body}\n"
        f"//! Status: {status}\n"
        f"//!\n"
        f"//! Not yet ported. See _porting/MANIFEST.csv and\n"
        f"//! _porting/OPEN_QUESTIONS.md. Do not invent behaviour here.\n"
        "\n"
    )


# --------------------------------------------------------------------------
# Walk
# --------------------------------------------------------------------------
def walk_java():
    files = []
    for dp, dn, fn in os.walk(SRC):
        dn.sort()
        for f in sorted(fn):
            if f.endswith(".java"):
                files.append(os.path.relpath(os.path.join(dp, f), SRC).replace("\\", "/"))
    return sorted(files)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="dry run; exit 1 on drift")
    args = ap.parse_args()

    if not os.path.isdir(SRC):
        print(f"FATAL: source tree not found: {SRC}", file=sys.stderr)
        return 2

    java_files = walk_java()
    by_rel = {p: os.path.join(SRC, p.replace("/", os.sep)) for p in java_files}

    # ---- analyse (single pass, reused by skeleton + manifest) ----
    infos = {}
    for rel in java_files:
        infos[rel] = analyse(by_rel[rel])

    # set of known class simple-names per package, for same-package dependency detection
    pkg_names = {}
    for rel, info in infos.items():
        pkg_names.setdefault(info["package"], set()).update(info["types"])

    # ---- dir -> children ----
    dirs = {}  # dir_rel -> list[(file_base, module_ident)]
    for rel in java_files:
        d, _, base = rel.rpartition("/")
        base = base[:-5]
        dirs.setdefault(d, []).append((base, rust_module_ident(base)))

    # Every ancestor folder of every folder that holds a .java file needs a mod.rs,
    # even when it holds no .java file itself (e.g. com/ , com/mojang/ ).
    all_dirs = set(dirs) | {""}
    changed = True
    while changed:
        changed = False
        for d in list(all_dirs):
            parent = d.rpartition("/")[0]
            if parent not in all_dirs:
                all_dirs.add(parent)
                changed = True

    # ---- write skeleton + mod.rs ----
    created_rs = 0
    created_mod = 0
    plan = {}  # rust_rel -> content to write if missing

    for rel in java_files:
        rust_rel = rel[:-5] + ".rs"
        dst = os.path.join(RUST_ROOT, rust_rel.replace("/", os.sep))
        if not os.path.exists(dst):
            plan[dst] = rs_header(rel, infos[rel], "SKELETON")
            created_rs += 1

    for d in sorted(x for x in all_dirs if x):  # "" == crate root -> handled by lib.rs
        children = dirs.get(d, [])
        prefix = d + "/"
        subs = sorted(x[len(prefix):] for x in all_dirs if x.startswith(prefix) and "/" not in x[len(prefix):])
        subs = [(s, s) for s in subs]
        pkg = ".".join(d.split("/")) if d else ""
        # package root `net/minecraft/util` -> java package `net.minecraft.util`
        content = mod_rs_body(d, children, subs, pkg)
        dst = os.path.join(RUST_ROOT, d.replace("/", os.sep), "mod.rs")
        if not os.path.exists(dst):
            plan[dst] = content
            created_mod += 1
        else:
            cur = read(dst)
            if cur != content:
                plan[dst] = content  # regenerate (idempotent afterwards)

    for extra, content in ((os.path.join(RUST_ROOT, "Cargo.toml"), CARGO_TOML),
                           (os.path.join(RUST_ROOT, "lib.rs"), LIB_RS)):
        if not os.path.exists(extra) or read(extra) != content:
            plan[extra] = content

    if args.check:
        if plan:
            print(f"DRIFT: {len(plan)} file(s) would change:")
            for p in sorted(plan)[:40]:
                print("  " + os.path.relpath(p, RUST_ROOT).replace("\\", "/"))
            return 1
        print(f"OK: mirror up to date ({len(java_files)} java files).")
        return 0

    for dst, content in sorted(plan.items()):
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        with open(dst, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(content)

    # ---- status + manifest (reads what is actually on disk now) ----
    rows = []
    for rel in java_files:
        info = infos[rel]
        rust_rel = rel[:-5] + ".rs"
        dst = os.path.join(RUST_ROOT, rust_rel.replace("/", os.sep))
        status = "MISSING"
        if os.path.exists(dst):
            for line in read(dst).splitlines()[:8]:
                if line.startswith("//! Status:"):
                    status = line.split(":", 1)[1].strip()
                    break

        deps = []
        for fq in info["imports"]:
            if class_name_to_rel(fq) in by_rel:
                deps.append(fq)
        for fq in info["static_imports"]:
            deps.append(fq + ".*")
        # same-package simple-name references (Java needs no import for these)
        body = strip_comments(read(by_rel[rel]))
        for simple in sorted(pkg_names.get(info["package"], ())):
            if simple in info["types"]:
                continue
            if re.search(r"(?<![\w$.])" + re.escape(simple) + r"(?![\w$])", body):
                deps.append(f"{info['package']}.{simple}")

        seen, uniq = set(), []
        for d in deps:
            if d not in seen:
                seen.add(d)
                uniq.append(d)
        uniq.sort()

        notes = []
        if info["anon"]:
            notes.append(f"{info['anon']}-anon-class")
        if not info["types"]:
            notes.append("no-type-decl")
        if status == "SKELETON":
            notes.append("not-ported")

        rows.append(OrderedDict([
            ("java_path", rel),
            ("rust_path", rust_rel),
            ("java_loc", info["loc"]),
            ("package", info["package"]),
            ("side", side_of(rel, info)),
            ("status", status),
            ("depends_on", ";".join(uniq)),
            ("notes", ";".join(notes)),
        ]))

    os.makedirs(PORTING, exist_ok=True)
    tmp = MANIFEST + ".tmp"
    with open(tmp, "w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0].keys()), lineterminator="\n")
        w.writeheader()
        w.writerows(rows)
    os.replace(tmp, MANIFEST)

    total_loc = sum(r["java_loc"] for r in rows)
    print(f"java files      : {len(java_files)}")
    print(f"java LOC        : {total_loc}")
    print(f".rs created now : {created_rs}")
    print(f"mod.rs created  : {created_mod}")
    print(f"dirs            : {len(all_dirs)}")
    print(f"manifest rows   : {len(rows)} -> {os.path.relpath(MANIFEST, REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
