//! Module declarations for `net.minecraft.client.tutorial` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod CompletedTutorialStepInstance;
pub mod CraftPlanksTutorialStep;
pub mod FindTreeTutorialStepInstance;
pub mod MovementTutorialStepInstance;
pub mod OpenInventoryTutorialStep;
pub mod PunchTreeTutorialStepInstance;
pub mod Tutorial;
pub mod TutorialStepInstance;
pub mod TutorialSteps;
#[path = "package-info.rs"]
pub mod package_info;
