//! Module declarations for `net.minecraft.commands.arguments.selector` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod options;

pub mod EntitySelector;
pub mod EntitySelectorParser;
#[path = "package-info.rs"]
pub mod package_info;
