//! Module declarations for `net.minecraft.commands.arguments` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod blocks;
pub mod coordinates;
pub mod item;
pub mod selector;

pub mod AngleArgument;
pub mod ArgumentSignatures;
pub mod ComponentArgument;
pub mod CompoundTagArgument;
pub mod DimensionArgument;
pub mod EntityAnchorArgument;
pub mod EntityArgument;
pub mod GameModeArgument;
pub mod GameProfileArgument;
pub mod HeightmapTypeArgument;
pub mod HexColorArgument;
pub mod IdentifierArgument;
pub mod MessageArgument;
pub mod NbtPathArgument;
pub mod NbtTagArgument;
pub mod ObjectiveArgument;
pub mod ObjectiveCriteriaArgument;
pub mod OperationArgument;
pub mod ParticleArgument;
pub mod RangeArgument;
pub mod ResourceArgument;
pub mod ResourceKeyArgument;
pub mod ResourceOrIdArgument;
pub mod ResourceOrTagArgument;
pub mod ResourceOrTagKeyArgument;
pub mod ResourceSelectorArgument;
pub mod ScoreHolderArgument;
pub mod ScoreboardSlotArgument;
pub mod SignedArgument;
pub mod SlotArgument;
pub mod SlotsArgument;
pub mod StringRepresentableArgument;
pub mod StyleArgument;
pub mod TeamArgument;
pub mod TeamColorArgument;
pub mod TemplateMirrorArgument;
pub mod TemplateRotationArgument;
pub mod TimeArgument;
pub mod UuidArgument;
pub mod WaypointArgument;
#[path = "package-info.rs"]
pub mod package_info;
