//! Module declarations for `net.minecraft.network.chat.numbers` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BlankFormat;
pub mod FixedFormat;
pub mod NumberFormat;
pub mod NumberFormatType;
pub mod NumberFormatTypes;
pub mod StyledFormat;
#[path = "package-info.rs"]
pub mod package_info;
