//! Module declarations for `net.minecraft.world.level.block.entity.vault` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod VaultBlockEntity;
pub mod VaultClientData;
pub mod VaultConfig;
pub mod VaultServerData;
pub mod VaultSharedData;
pub mod VaultState;
#[path = "package-info.rs"]
pub mod package_info;
