//! Module declarations for `net.minecraft.world.level.levelgen.structure.templatesystem.rule` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod blockentity;
