//! Module declarations for `net.minecraft.client.gui.navigation` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod FocusNavigationEvent;
pub mod ScreenAxis;
pub mod ScreenDirection;
pub mod ScreenPosition;
pub mod ScreenRectangle;
#[path = "package-info.rs"]
pub mod package_info;
