//! Module declarations for `net.minecraft.world.entity.vehicle.minecart` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractMinecart;
pub mod AbstractMinecartContainer;
pub mod Minecart;
pub mod MinecartBehavior;
pub mod MinecartChest;
pub mod MinecartCommandBlock;
pub mod MinecartFurnace;
pub mod MinecartHopper;
pub mod MinecartSpawner;
pub mod MinecartTNT;
pub mod NewMinecartBehavior;
pub mod OldMinecartBehavior;
#[path = "package-info.rs"]
pub mod package_info;
