//! Module declarations for `net.minecraft.client.resources` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod language;
pub mod metadata;
pub mod model;
pub mod server;
pub mod sounds;

pub mod ClientPackSource;
pub mod DefaultPlayerSkin;
pub mod DryFoliageColorReloadListener;
pub mod FoliageColorReloadListener;
pub mod GrassColorReloadListener;
pub mod IndexedAssetSource;
pub mod LegacyStuffWrapper;
pub mod MapTextureManager;
pub mod SkinManager;
pub mod SplashManager;
pub mod WaypointStyle;
pub mod WaypointStyleManager;
#[path = "package-info.rs"]
pub mod package_info;
