//! Module declarations for `net.minecraft.world.level.gameevent.vibrations` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod VibrationInfo;
pub mod VibrationSelector;
pub mod VibrationSystem;
#[path = "package-info.rs"]
pub mod package_info;
