//! Module declarations for `net.minecraft.client.gui.components` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod debug;
pub mod debugchart;
pub mod events;
pub mod spectator;
pub mod tabs;
pub mod toasts;

pub mod AbstractButton;
pub mod AbstractContainerWidget;
pub mod AbstractOptionSliderButton;
pub mod AbstractScrollArea;
pub mod AbstractSelectionList;
pub mod AbstractSliderButton;
pub mod AbstractStringWidget;
pub mod AbstractTextAreaWidget;
pub mod AbstractWidget;
pub mod BossHealthOverlay;
pub mod Button;
pub mod ChatComponent;
pub mod Checkbox;
pub mod CommandSuggestions;
pub mod CommonButtons;
pub mod ComponentRenderUtils;
pub mod ContainerObjectSelectionList;
pub mod CycleButton;
pub mod DebugScreenOverlay;
pub mod EditBox;
pub mod FittingMultiLineTextWidget;
pub mod FocusableTextWidget;
pub mod FriendsButton;
pub mod IMEPreeditOverlay;
pub mod ImageButton;
pub mod ImageWidget;
pub mod ItemDisplayWidget;
pub mod LerpingBossEvent;
pub mod LoadingDotsWidget;
pub mod LockIconButton;
pub mod LogoRenderer;
pub mod MultiLineEditBox;
pub mod MultiLineLabel;
pub mod MultiLineTextWidget;
pub mod MultilineTextField;
pub mod ObjectSelectionList;
pub mod OptionsList;
pub mod PlainTextButton;
pub mod PlayerFaceExtractor;
pub mod PlayerFaceWidget;
pub mod PlayerSkinWidget;
pub mod PlayerTabOverlay;
pub mod PopupScreen;
pub mod Renderable;
pub mod ResettableOptionWidget;
pub mod ScrollableLayout;
pub mod SelectableEntry;
pub mod SplashRenderer;
pub mod SpriteIconButton;
pub mod StringWidget;
pub mod SubtitleOverlay;
pub mod TabButton;
pub mod TabOrderedElement;
pub mod TextCursorUtils;
pub mod Tooltip;
pub mod Whence;
pub mod WidgetSprites;
pub mod WidgetTooltipHolder;
#[path = "package-info.rs"]
pub mod package_info;
