//! Module declarations for `net.minecraft.world.level.block.entity.trialspawner` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod PlayerDetector;
pub mod TrialSpawner;
pub mod TrialSpawnerConfig;
pub mod TrialSpawnerConfigs;
pub mod TrialSpawnerState;
pub mod TrialSpawnerStateData;
#[path = "package-info.rs"]
pub mod package_info;
