//! Module declarations for `net.minecraft.world.level.storage.loot.providers.score` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod ContextScoreboardNameProvider;
pub mod FixedScoreboardNameProvider;
pub mod ScoreboardNameProvider;
pub mod ScoreboardNameProviders;
#[path = "package-info.rs"]
pub mod package_info;
