//! Module declarations for `net.minecraft.world.entity.ai.behavior.warden` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod Digging;
pub mod Emerging;
pub mod ForceUnmount;
pub mod Roar;
pub mod SetRoarTarget;
pub mod SetWardenLookTarget;
pub mod Sniffing;
pub mod SonicBoom;
pub mod TryToSniff;
#[path = "package-info.rs"]
pub mod package_info;
