//! Module declarations for `com.mojang.blaze3d.framegraph` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod FrameGraphBuilder;
pub mod FramePass;
#[path = "package-info.rs"]
pub mod package_info;
