//! Module declarations for `net.minecraft.client.renderer.special` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BannerSpecialRenderer;
pub mod BellSpecialRenderer;
pub mod BookSpecialRenderer;
pub mod ChestSpecialRenderer;
pub mod ConduitSpecialRenderer;
pub mod CopperGolemStatueSpecialRenderer;
pub mod DecoratedPotSpecialRenderer;
pub mod EndCubeSpecialRenderer;
pub mod NoDataSpecialModelRenderer;
pub mod PlayerHeadSpecialRenderer;
pub mod ShieldSpecialRenderer;
pub mod ShulkerBoxSpecialRenderer;
pub mod SkullSpecialRenderer;
pub mod SpecialModelRenderer;
pub mod SpecialModelRenderers;
pub mod TridentSpecialRenderer;
#[path = "package-info.rs"]
pub mod package_info;
