//! Module declarations for `net.minecraft.client.gui.screens.social` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod PlayerEntry;
pub mod PlayerSocialManager;
pub mod PresenceHandler;
pub mod RemoteFriendListUpdateHandler;
pub mod SocialInteractionsPlayerList;
pub mod SocialInteractionsScreen;
#[path = "package-info.rs"]
pub mod package_info;
