//! Module declarations for `net.minecraft.client.gui.screens.recipebook` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod CraftingRecipeBookComponent;
pub mod FurnaceRecipeBookComponent;
pub mod GhostSlots;
pub mod OverlayRecipeComponent;
pub mod RecipeBookComponent;
pub mod RecipeBookPage;
pub mod RecipeBookTabButton;
pub mod RecipeButton;
pub mod RecipeCollection;
pub mod RecipeUpdateListener;
pub mod SearchRecipeBookCategory;
pub mod SlotSelectTime;
#[path = "package-info.rs"]
pub mod package_info;
