//! Module declarations for `net.minecraft.world.level.levelgen.flat` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod FlatLayerInfo;
pub mod FlatLevelGeneratorPreset;
pub mod FlatLevelGeneratorPresets;
pub mod FlatLevelGeneratorSettings;
#[path = "package-info.rs"]
pub mod package_info;
