//! Module declarations for `net.minecraft.client.resources.metadata` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod animation;
pub mod gui;
pub mod language;
pub mod texture;

#[path = "package-info.rs"]
pub mod package_info;
