//! Module declarations for `net.minecraft.world.item.equipment.trim` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod ArmorTrim;
pub mod MaterialAssetGroup;
pub mod TrimMaterial;
pub mod TrimMaterials;
pub mod TrimPattern;
pub mod TrimPatterns;
#[path = "package-info.rs"]
pub mod package_info;
