//! Module declarations for `net.minecraft.world.entity.projectile` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod arrow;
pub mod hurtingprojectile;
pub mod throwableitemprojectile;

pub mod EvokerFangs;
pub mod EyeOfEnder;
pub mod FireworkRocketEntity;
pub mod FishingHook;
pub mod ItemSupplier;
pub mod LlamaSpit;
pub mod Projectile;
pub mod ProjectileDeflection;
pub mod ProjectileUtil;
pub mod ShulkerBullet;
pub mod ThrowableProjectile;
#[path = "package-info.rs"]
pub mod package_info;
