//! Module declarations for `net.minecraft.world.entity.monster.warden` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AngerLevel;
pub mod AngerManagement;
pub mod Warden;
pub mod WardenAi;
pub mod WardenSpawnTracker;
#[path = "package-info.rs"]
pub mod package_info;
