//! Module declarations for `net.minecraft.util.profiling` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod jfr;
pub mod metrics;

pub mod ActiveProfiler;
pub mod ContinuousProfiler;
pub mod EmptyProfileResults;
pub mod FilledProfileResults;
pub mod InactiveProfiler;
pub mod ProfileCollector;
pub mod ProfileResults;
pub mod Profiler;
pub mod ProfilerFiller;
pub mod ProfilerPathEntry;
pub mod ResultField;
pub mod SingleTickProfiler;
pub mod TracyZoneFiller;
pub mod Zone;
#[path = "package-info.rs"]
pub mod package_info;
