//! Module declarations for `net.minecraft.world.level.levelgen.structure.templatesystem.loader` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod DirectoryTemplateSource;
pub mod ResourceManagerTemplateSource;
pub mod TemplatePathFactory;
pub mod TemplateSource;
#[path = "package-info.rs"]
pub mod package_info;
