//! Module declarations for `net.minecraft.world.level.levelgen.feature.configurations` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BlockBlobConfiguration;
pub mod BlockColumnConfiguration;
pub mod BlockPileConfiguration;
pub mod BlockStateConfiguration;
pub mod ColumnFeatureConfiguration;
pub mod CompositeFeatureConfiguration;
pub mod CountConfiguration;
pub mod DeltaFeatureConfiguration;
pub mod DiskConfiguration;
pub mod EndGatewayConfiguration;
pub mod EndSpikeConfiguration;
pub mod FallenTreeConfiguration;
pub mod FeatureConfiguration;
pub mod GeodeConfiguration;
pub mod HugeMushroomFeatureConfiguration;
pub mod LargeDripstoneConfiguration;
pub mod LayerConfiguration;
pub mod MultifaceGrowthConfiguration;
pub mod NetherForestVegetationConfig;
pub mod NoneFeatureConfiguration;
pub mod OreConfiguration;
pub mod ProbabilityFeatureConfiguration;
pub mod RandomBooleanFeatureConfiguration;
pub mod RandomFeatureConfiguration;
pub mod ReplaceBlockConfiguration;
pub mod ReplaceSphereConfiguration;
pub mod RootSystemConfiguration;
pub mod SculkPatchConfiguration;
pub mod SimpleBlockConfiguration;
pub mod SpeleothemClusterConfiguration;
pub mod SpeleothemConfiguration;
pub mod SpikeConfiguration;
pub mod SpringConfiguration;
pub mod TemplateFeatureConfiguration;
pub mod TreeConfiguration;
pub mod TwistingVinesConfig;
pub mod UnderwaterMagmaConfiguration;
pub mod VegetationPatchConfiguration;
pub mod WeightedRandomFeatureConfiguration;
#[path = "package-info.rs"]
pub mod package_info;
