//! Module declarations for `net.minecraft.advancements` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod predicates;
pub mod triggers;

pub mod Advancement;
pub mod AdvancementHolder;
pub mod AdvancementNode;
pub mod AdvancementProgress;
pub mod AdvancementRequirements;
pub mod AdvancementRewards;
pub mod AdvancementTree;
pub mod AdvancementType;
pub mod CriterionProgress;
pub mod CriterionTriggerInstance;
pub mod DisplayInfo;
pub mod TreeNodePosition;
#[path = "package-info.rs"]
pub mod package_info;
