//! Module declarations for `net.minecraft.advancements.predicates.entity` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod CubeMobPredicate;
pub mod DistanceToPlayerPredicate;
pub mod EntityEffectsPredicate;
pub mod EntityEquipmentPredicate;
pub mod EntityExactDataComponentsPredicate;
pub mod EntityFlagsPredicate;
pub mod EntityLocationPredicate;
pub mod EntityNbtPredicate;
pub mod EntityPartialComponentsPredicate;
pub mod EntityPredicate;
pub mod EntitySlotsPredicate;
pub mod EntitySubPredicate;
pub mod EntitySubPredicates;
pub mod EntityTagPredicate;
pub mod EntityTypePredicate;
pub mod FishingHookPredicate;
pub mod LightningBoltPredicate;
pub mod MovementAffectedByPredicate;
pub mod MovementPredicate;
pub mod PassengerPredicate;
pub mod PeriodicEntityTickPredicate;
pub mod PlayerPredicate;
pub mod RaiderPredicate;
pub mod SheepPredicate;
pub mod SteppingOnPredicate;
pub mod TargetedEntityPredicate;
pub mod TeamPredicate;
pub mod VehiclePredicate;
#[path = "package-info.rs"]
pub mod package_info;
