//! Module declarations for `net.minecraft.network.chat` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod contents;
pub mod numbers;

pub mod ChatDecorator;
pub mod ChatType;
pub mod ChatTypeDecoration;
pub mod ClickEvent;
pub mod CommonComponents;
pub mod Component;
pub mod ComponentContents;
pub mod ComponentSerialization;
pub mod ComponentUtils;
pub mod FilterMask;
pub mod FontDescription;
pub mod FormattedText;
pub mod HoverEvent;
pub mod LastSeenMessages;
pub mod LastSeenMessagesTracker;
pub mod LastSeenMessagesValidator;
pub mod LastSeenTrackedEntry;
pub mod LocalChatSession;
pub mod MessageSignature;
pub mod MessageSignatureCache;
pub mod MutableComponent;
pub mod OutgoingChatMessage;
pub mod PlayerChatMessage;
pub mod RemoteChatSession;
pub mod ResolutionContext;
pub mod SignableCommand;
pub mod SignedMessageBody;
pub mod SignedMessageChain;
pub mod SignedMessageLink;
pub mod SignedMessageValidator;
pub mod Style;
pub mod SubStringSource;
pub mod TextColor;
pub mod ThrowingComponent;
#[path = "package-info.rs"]
pub mod package_info;
