//! Module declarations for `net.minecraft.world.level.levelgen.structure` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod pieces;
pub mod placement;
pub mod pools;
pub mod structures;
pub mod templatesystem;

pub mod BoundingBox;
pub mod BuiltinStructureSets;
pub mod BuiltinStructures;
pub mod PoolElementStructurePiece;
pub mod PostPlacementProcessor;
pub mod ScatteredFeaturePiece;
pub mod SinglePieceStructure;
pub mod Structure;
pub mod StructureCheck;
pub mod StructureCheckResult;
pub mod StructurePiece;
pub mod StructurePieceAccessor;
pub mod StructureSet;
pub mod StructureSpawnOverride;
pub mod StructureStart;
pub mod StructureType;
pub mod TemplateStructurePiece;
pub mod TerrainAdjustment;
#[path = "package-info.rs"]
pub mod package_info;
