//! Module declarations for `net.minecraft.world.attribute.modifier` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AttributeModifier;
pub mod BooleanModifier;
pub mod ColorModifier;
pub mod FloatModifier;
pub mod FloatWithAlpha;
pub mod IntegerModifier;
#[path = "package-info.rs"]
pub mod package_info;
