//! Module declarations for `net.minecraft.client.renderer.feature.phase` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod FeatureRenderPhase;
pub mod SimpleFeatureRenderPhase;
pub mod TranslucentFeatureRenderPhase;
#[path = "package-info.rs"]
pub mod package_info;
