//! Module declarations for `net.minecraft.data` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod advancements;
pub mod info;
pub mod loot;
pub mod metadata;
pub mod recipes;
pub mod registries;
pub mod structures;
pub mod tags;
pub mod worldgen;

pub mod AtlasIds;
pub mod BlockFamilies;
pub mod BlockFamily;
pub mod CachedOutput;
pub mod DataGenerator;
pub mod DataProvider;
pub mod HashCache;
pub mod Main;
pub mod PackOutput;
#[path = "package-info.rs"]
pub mod package_info;
