//! Module declarations for `net.minecraft.client.multiplayer.chat` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod report;

pub mod ChatAbilities;
pub mod ChatListener;
pub mod ChatLog;
pub mod ChatRestriction;
pub mod ChatTrustLevel;
pub mod GuiMessage;
pub mod GuiMessageSource;
pub mod GuiMessageTag;
pub mod LoggedChatEvent;
pub mod LoggedChatMessage;
#[path = "package-info.rs"]
pub mod package_info;
