//! Module declarations for `net.minecraft.data.tags` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BannerPatternTagsProvider;
pub mod BiomeTagsProvider;
pub mod BlockItemTagAppender;
pub mod BlockItemTagsProvider;
pub mod DamageTypeTagsProvider;
pub mod DialogTagsProvider;
pub mod EnchantmentTagsProvider;
pub mod EntityTypeTagsProvider;
pub mod FeatureTagsProvider;
pub mod FlatLevelGeneratorPresetTagsProvider;
pub mod FluidTagsProvider;
pub mod GameEventTagsProvider;
pub mod InstrumentTagsProvider;
pub mod PaintingVariantTagsProvider;
pub mod PoiTypeTagsProvider;
pub mod PotionTagsProvider;
pub mod StructureTagsProvider;
pub mod TagAppender;
pub mod TagsProvider;
pub mod TimelineTagsProvider;
pub mod TradeRebalanceEnchantmentTagsProvider;
pub mod TradeRebalanceTradeTagsProvider;
pub mod VanillaBlockItemTagsProvider;
pub mod VanillaBlockTagsProvider;
pub mod VanillaEnchantmentTagsProvider;
pub mod VanillaItemTagsProvider;
pub mod VillagerTradesTagsProvider;
pub mod WorldPresetTagsProvider;
#[path = "package-info.rs"]
pub mod package_info;
