//! Module declarations for `net.minecraft.util.filefix.access` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod ChunkNbt;
pub mod CompressedNbt;
pub mod FileAccess;
pub mod FileAccessProvider;
pub mod FileRelation;
pub mod FileResourceType;
pub mod FileResourceTypes;
pub mod LevelDat;
pub mod PlayerData;
pub mod SavedDataNbt;
#[path = "package-info.rs"]
pub mod package_info;
