//! Module declarations for `net.minecraft.world.entity.boss.enderdragon` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod phases;

pub mod DragonFlightHistory;
pub mod EndCrystal;
pub mod EnderDragon;
pub mod EnderDragonPart;
#[path = "package-info.rs"]
pub mod package_info;
