//! Module declarations for `net.minecraft.client.resources.metadata.animation` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AnimationFrame;
pub mod AnimationMetadataSection;
pub mod FrameSize;
pub mod VillagerMetadataSection;
#[path = "package-info.rs"]
pub mod package_info;
