//! Module declarations for `net.minecraft.world.attribute` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod modifier;

pub mod AmbientAdditionsSettings;
pub mod AmbientMoodSettings;
pub mod AmbientParticle;
pub mod AmbientSounds;
pub mod AttributeRange;
pub mod AttributeType;
pub mod AttributeTypes;
pub mod BackgroundMusic;
pub mod BedRule;
pub mod EnvironmentAttribute;
pub mod EnvironmentAttributeLayer;
pub mod EnvironmentAttributeMap;
pub mod EnvironmentAttributeProbe;
pub mod EnvironmentAttributeReader;
pub mod EnvironmentAttributeSystem;
pub mod EnvironmentAttributes;
pub mod GaussianSampler;
pub mod LerpFunction;
pub mod SpatialAttributeInterpolator;
pub mod WeatherAttributes;
#[path = "package-info.rs"]
pub mod package_info;
