//! Module declarations for `net.minecraft.world.entity.vehicle` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod boat;
pub mod minecart;

pub mod ContainerEntity;
pub mod DismountHelper;
pub mod VehicleEntity;
#[path = "package-info.rs"]
pub mod package_info;
