//! Module declarations for `net.minecraft.world.level.storage.loot.providers` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod nbt;
pub mod number;
pub mod score;
