//! Module declarations for `net.minecraft.data.worldgen.biome` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BiomeData;
pub mod EndBiomes;
pub mod NetherBiomes;
pub mod OverworldBiomes;
#[path = "package-info.rs"]
pub mod package_info;
