//! Module declarations for `net.minecraft.util.profiling.jfr.parse` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod JfrStatsParser;
pub mod JfrStatsResult;
#[path = "package-info.rs"]
pub mod package_info;
