//! Module declarations for `net.minecraft.data.loot` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod packs;

pub mod BlockLootSubProvider;
pub mod EntityLootSubProvider;
pub mod LootTableProvider;
pub mod LootTableSubProvider;
#[path = "package-info.rs"]
pub mod package_info;
