//! Module declarations for `net.minecraft.core` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod cauldron;
pub mod component;
pub mod dispenser;
pub mod particles;
pub mod registries;

pub mod AxisCycle;
pub mod BlockBox;
pub mod BlockMath;
pub mod BlockPos;
pub mod ClientAsset;
pub mod Cloner;
pub mod Cursor3D;
pub mod DefaultedMappedRegistry;
pub mod DefaultedRegistry;
pub mod Direction;
pub mod Direction8;
pub mod FrontAndTop;
pub mod GlobalPos;
pub mod Holder;
pub mod HolderGetter;
pub mod HolderLookup;
pub mod HolderOwner;
pub mod HolderSet;
pub mod IdMap;
pub mod IdMapper;
pub mod LayeredRegistryAccess;
pub mod MappedRegistry;
pub mod NonNullList;
pub mod Position;
pub mod QuartPos;
pub mod RegistrationInfo;
pub mod Registry;
pub mod RegistryAccess;
pub mod RegistryCodecs;
pub mod RegistrySetBuilder;
pub mod RegistrySynchronization;
pub mod Rotations;
pub mod SectionPos;
pub mod TypedInstance;
pub mod UUIDUtil;
pub mod Vec3i;
pub mod WritableRegistry;
#[path = "package-info.rs"]
pub mod package_info;
