//! Module declarations for `com.mojang.blaze3d.systems` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BackendCreationException;
pub mod CommandEncoder;
pub mod CommandEncoderBackend;
pub mod DeviceFeatures;
pub mod DeviceInfo;
pub mod DeviceLimits;
pub mod DeviceType;
pub mod GpuBackend;
pub mod GpuDevice;
pub mod GpuDeviceBackend;
pub mod GpuQuery;
pub mod GpuQueryPool;
pub mod GpuSurface;
pub mod GpuSurfaceBackend;
pub mod HintsAndWorkarounds;
pub mod RenderPass;
pub mod RenderPassBackend;
pub mod RenderPassDescriptor;
pub mod RenderSystem;
pub mod SamplerCache;
pub mod ScissorState;
pub mod SurfaceException;
pub mod TimerQuery;
pub mod TracyGpuProfiler;
pub mod TransientMemory;
#[path = "package-info.rs"]
pub mod package_info;
