//! Module declarations for `net.minecraft.world.entity.monster` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod breeze;
pub mod creaking;
pub mod cubemob;
pub mod hoglin;
pub mod illager;
pub mod piglin;
pub mod skeleton;
pub mod spider;
pub mod warden;
pub mod zombie;

pub mod Blaze;
pub mod Creeper;
pub mod CrossbowAttackMob;
pub mod ElderGuardian;
pub mod EnderMan;
pub mod Endermite;
pub mod Enemy;
pub mod Ghast;
pub mod Giant;
pub mod Guardian;
pub mod Monster;
pub mod PatrollingMonster;
pub mod Phantom;
pub mod RangedAttackMob;
pub mod Ravager;
pub mod Shulker;
pub mod Silverfish;
pub mod Strider;
pub mod Vex;
pub mod Witch;
pub mod Zoglin;
#[path = "package-info.rs"]
pub mod package_info;
