//! Module declarations for `net.minecraft.sounds` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod Music;
pub mod Musics;
pub mod SoundEvent;
pub mod SoundEvents;
pub mod SoundSource;
#[path = "package-info.rs"]
pub mod package_info;
