//! Module declarations for `net.minecraft.server.packs.resources` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod CloseableResourceManager;
pub mod FallbackResourceManager;
pub mod IoSupplier;
pub mod MultiPackResourceManager;
pub mod PreparableReloadListener;
pub mod ProfiledReloadInstance;
pub mod ReloadInstance;
pub mod ReloadableResourceManager;
pub mod Resource;
pub mod ResourceFilterSection;
pub mod ResourceManager;
pub mod ResourceManagerReloadListener;
pub mod ResourceMetadata;
pub mod ResourceProvider;
pub mod SimpleJsonResourceReloadListener;
pub mod SimplePreparableReloadListener;
pub mod SimpleReloadInstance;
#[path = "package-info.rs"]
pub mod package_info;
