//! Module declarations for `net.minecraft.client.animation.definitions` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod ArmadilloAnimation;
pub mod BabyArmadilloAnimation;
pub mod BabyAxolotlAnimation;
pub mod BabyRabbitAnimation;
pub mod BatAnimation;
pub mod BreezeAnimation;
pub mod CamelAnimation;
pub mod CamelBabyAnimation;
pub mod CopperGolemAnimation;
pub mod CreakingAnimation;
pub mod FoxBabyAnimation;
pub mod FrogAnimation;
pub mod NautilusAnimation;
pub mod RabbitAnimation;
pub mod SnifferAnimation;
pub mod WardenAnimation;
#[path = "package-info.rs"]
pub mod package_info;
