//! Module declarations for `net.minecraft.world.entity.projectile.hurtingprojectile.windcharge` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractWindCharge;
pub mod BreezeWindCharge;
pub mod WindCharge;
#[path = "package-info.rs"]
pub mod package_info;
