//! Module declarations for `net.minecraft.world.item.enchantment` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod effects;
pub mod providers;

pub mod ConditionalEffect;
pub mod Enchantable;
pub mod EnchantedItemInUse;
pub mod Enchantment;
pub mod EnchantmentEffectComponents;
pub mod EnchantmentHelper;
pub mod EnchantmentInstance;
pub mod EnchantmentTarget;
pub mod Enchantments;
pub mod ItemEnchantments;
pub mod LevelBasedValue;
pub mod Repairable;
pub mod TargetedConditionalEffect;
#[path = "package-info.rs"]
pub mod package_info;
