//! Module declarations for `net.minecraft.world.ticks` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BlackholeTickAccess;
pub mod ContainerSingleItem;
pub mod LevelChunkTicks;
pub mod LevelTickAccess;
pub mod LevelTicks;
pub mod ProtoChunkTicks;
pub mod SavedTick;
pub mod ScheduledTick;
pub mod SerializableTickContainer;
pub mod TickAccess;
pub mod TickContainerAccess;
pub mod TickPriority;
pub mod WorldGenTickAccess;
#[path = "package-info.rs"]
pub mod package_info;
