//! Module declarations for `net.minecraft.world.level.block.state.pattern` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BlockInWorld;
pub mod BlockPattern;
pub mod BlockPatternBuilder;
#[path = "package-info.rs"]
pub mod package_info;
