//! Module declarations for `net.minecraft.client.renderer.block.dispatch` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod multipart;

pub mod BlockModelRotation;
pub mod BlockStateModel;
pub mod BlockStateModelDispatcher;
pub mod BlockStateModelPart;
pub mod ModelState;
pub mod SingleVariant;
pub mod Variant;
pub mod VariantMutator;
pub mod VariantSelector;
pub mod WeightedVariants;
#[path = "package-info.rs"]
pub mod package_info;
