//! Module declarations for `net.minecraft.client.model.animal.camel` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AdultCamelModel;
pub mod BabyCamelModel;
pub mod CamelModel;
pub mod CamelSaddleModel;
#[path = "package-info.rs"]
pub mod package_info;
