//! Module declarations for `net.minecraft.world.level.entity` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod ChunkEntities;
pub mod ChunkStatusUpdateListener;
pub mod EntityAccess;
pub mod EntityInLevelCallback;
pub mod EntityLookup;
pub mod EntityPersistentStorage;
pub mod EntitySection;
pub mod EntitySectionStorage;
pub mod EntityTickList;
pub mod EntityTypeTest;
pub mod LevelCallback;
pub mod LevelEntityGetter;
pub mod LevelEntityGetterAdapter;
pub mod PersistentEntitySectionManager;
pub mod TransientEntitySectionManager;
pub mod UUIDLookup;
pub mod UniquelyIdentifyable;
pub mod Visibility;
#[path = "package-info.rs"]
pub mod package_info;
