//! Rust translation of Minecraft 26.2 (Fabric Loom split-environment *client* jar).
//!
//! Layout rule: the folder tree below this crate root is a byte-for-byte mirror of
//! `minecraft-decompiled/`. Every `.java` file has exactly one `.rs` sibling with the
//! same base name (`Mth.java` -> `Mth.rs`). Do NOT flatten, rename or reorganise.
//!
//! Prime directive: NO GAMEPLAY CHANGES. Same inputs, same outputs, tick for tick,
//! bit for bit. Vanilla bugs are mechanics and must be preserved.
//!
//! Generated by _porting/tools/mirror.py.

#![allow(non_snake_case, non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(unused_imports, unused_variables, unused_mut, dead_code, unused_parens)]
#![allow(unreachable_code, unused_assignments, unused_labels)]
#![allow(clippy::all)]

pub mod com;
pub mod net;
