//! Rust translation of Minecraft 26.2 (Fabric Loom split-environment *client* jar).
//!
//! Layout rule: the folder tree below this crate root is a byte-for-byte mirror of
//! `minecraft-decompiled/`. Every `.java` file has exactly one `.rs` sibling with the
//! same base name (`Mth.java` -> `Mth.rs`). Do NOT flatten, rename or reorganise.
//!
//! Prime directive: NO GAMEPLAY CHANGES. Same inputs, same outputs, tick for tick,
//! bit for bit. Vanilla bugs are mechanics and must be preserved.
//!
//! Generated by _porting/tools/mirror.py.

#![allow(non_snake_case, non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(unused_imports, unused_variables, unused_mut, dead_code, unused_parens)]
#![allow(unreachable_code, unused_assignments, unused_labels)]
#![allow(clippy::all)]

pub mod com;
pub mod net;

/// Java standard-library equivalents (Math.floorMod, String.hashCode, the
/// java.util.Random LCG, MD5, the golden-data reader). These have no `.java`
/// counterpart in minecraft-decompiled/, so Rule 3 puts them in `_porting/`; we
/// still expose them as a normal crate module so ported game code can `use`
/// them without path gymnastics. See _porting/DESIGN_DECISIONS.md (#javacompat).
#[path = "_porting/javacompat/mod.rs"]
pub mod javacompat;

/// Data tables GENERATED from the Java oracle's golden output, not hand-written.
///
/// `ARGB`'s two sRGB lookup tables hold 1280 values that must be embedded rather than
/// recomputed, because the Java initialisers call `Math.pow` and `Math.pow` is a HotSpot
/// intrinsic we have not ported. Typing 1280 values would be exactly the hand-derived-constant
/// error this project forbids, so `_porting/tools/gen_argb_tables.py` derives them from the jar
/// and this module holds the result.
///
/// Regenerate with `python _porting/tools/gen_argb_tables.py`. `parity_batch2` compares every
/// value here against the golden, so the file and the data cannot drift apart silently.
#[path = "_porting/generated/argb_srgb_tables.rs"]
pub mod argb_srgb_tables;
