//! Module declarations for `com.mojang.blaze3d` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod audio;
pub mod buffers;
pub mod font;
pub mod framegraph;
pub mod opengl;
pub mod pipeline;
pub mod platform;
pub mod preprocessor;
pub mod resource;
pub mod shaders;
pub mod systems;
pub mod textures;
pub mod util;
pub mod vertex;
pub mod vulkan;

pub mod Blaze3D;
pub mod GLFWErrorCapture;
pub mod GLFWErrorScope;
pub mod GpuDeviceLossException;
pub mod GpuFormat;
pub mod GpuOutOfMemoryException;
pub mod IndexType;
pub mod PrimitiveTopology;
pub mod ProjectionType;
pub mod TracyBootstrap;
pub mod TracyFrameCapture;
#[path = "package-info.rs"]
pub mod package_info;
