//! Module declarations for `net.minecraft.client.renderer.texture` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod atlas;

pub mod AbstractTexture;
pub mod CubeMapTexture;
pub mod Dumpable;
pub mod DynamicTexture;
pub mod MipmapGenerator;
pub mod MipmapStrategy;
pub mod MissingTextureAtlasSprite;
pub mod OverlayTexture;
pub mod ReloadableTexture;
pub mod SimpleTexture;
pub mod SkinTextureDownloader;
pub mod SpriteContents;
pub mod SpriteLoader;
pub mod Stitcher;
pub mod StitcherException;
pub mod TextureAtlas;
pub mod TextureAtlasSprite;
pub mod TextureContents;
pub mod TextureManager;
pub mod TickableTexture;
#[path = "package-info.rs"]
pub mod package_info;
