//! Module declarations for `net.minecraft.client.renderer.fog.environment` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AtmosphericFogEnvironment;
pub mod BlindnessFogEnvironment;
pub mod DarknessFogEnvironment;
pub mod FogEnvironment;
pub mod LavaFogEnvironment;
pub mod MobEffectFogEnvironment;
pub mod PowderedSnowFogEnvironment;
pub mod WaterFogEnvironment;
#[path = "package-info.rs"]
pub mod package_info;
