//! Module declarations for `net.minecraft.world.entity.animal.equine` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractChestedHorse;
pub mod AbstractHorse;
pub mod Donkey;
pub mod Horse;
pub mod Llama;
pub mod Markings;
pub mod Mule;
pub mod SkeletonHorse;
pub mod SkeletonTrapGoal;
pub mod TraderLlama;
pub mod Variant;
pub mod ZombieHorse;
#[path = "package-info.rs"]
pub mod package_info;
