//! Module declarations for `net.minecraft.world.entity.projectile.hurtingprojectile` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod windcharge;

pub mod AbstractHurtingProjectile;
pub mod DragonFireball;
pub mod Fireball;
pub mod LargeFireball;
pub mod SmallFireball;
pub mod WitherSkull;
#[path = "package-info.rs"]
pub mod package_info;
