//! Module declarations for `com.mojang.blaze3d.textures` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AddressMode;
pub mod FilterMode;
pub mod GpuSampler;
pub mod GpuTexture;
pub mod GpuTextureView;
#[path = "package-info.rs"]
pub mod package_info;
