//! Module declarations for `net.minecraft.commands.synchronization.brigadier` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod DoubleArgumentInfo;
pub mod FloatArgumentInfo;
pub mod IntegerArgumentInfo;
pub mod LongArgumentInfo;
pub mod StringArgumentSerializer;
#[path = "package-info.rs"]
pub mod package_info;
