//! Module declarations for `net.minecraft.client.renderer.item.properties.conditional` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod Broken;
pub mod BundleHasSelectedItem;
pub mod ComponentMatches;
pub mod ConditionalItemModelProperties;
pub mod ConditionalItemModelProperty;
pub mod CustomModelDataProperty;
pub mod Damaged;
pub mod ExtendedView;
pub mod FishingRodCast;
pub mod HasComponent;
pub mod IsCarried;
pub mod IsKeybindDown;
pub mod IsSelected;
pub mod IsUsingItem;
pub mod IsViewEntity;
pub mod ItemModelPropertyTest;
#[path = "package-info.rs"]
pub mod package_info;
