//! Module declarations for `net.minecraft.data.info` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BiomeParametersDumpReport;
pub mod BlockListReport;
pub mod CommandsReport;
pub mod DatapackStructureReport;
pub mod PacketReport;
pub mod RegistryComponentsReport;
pub mod RegistryDumpReport;
#[path = "package-info.rs"]
pub mod package_info;
