//! Module declarations for `net.minecraft.world.item.slot` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod CompositeSlotSource;
pub mod ContentsSlotSource;
pub mod EmptySlotSource;
pub mod FilteredSlotSource;
pub mod GroupSlotSource;
pub mod LimitSlotSource;
pub mod RangeSlotSource;
pub mod SlotCollection;
pub mod SlotSource;
pub mod SlotSources;
pub mod TransformedSlotSource;
#[path = "package-info.rs"]
pub mod package_info;
