//! Module declarations for `net.minecraft.data.advancements.packs` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod VanillaAdvancementProvider;
pub mod VanillaAdventureAdvancements;
pub mod VanillaHusbandryAdvancements;
pub mod VanillaNetherAdvancements;
pub mod VanillaStoryAdvancements;
pub mod VanillaTheEndAdvancements;
#[path = "package-info.rs"]
pub mod package_info;
