//! Module declarations for `net.minecraft.client.gui.screens.dialog.input` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod InputControlHandler;
pub mod InputControlHandlers;
#[path = "package-info.rs"]
pub mod package_info;
