//! Module declarations for `net.minecraft.world.entity.player` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod Abilities;
pub mod ChatVisiblity;
pub mod Input;
pub mod Inventory;
pub mod Player;
pub mod PlayerEquipment;
pub mod PlayerModelPart;
pub mod PlayerModelType;
pub mod PlayerSkin;
pub mod ProfileKeyPair;
pub mod ProfilePublicKey;
pub mod StackedContents;
pub mod StackedItemContents;
#[path = "package-info.rs"]
pub mod package_info;
