//! Module declarations for `net.minecraft.network.protocol.handshake` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod ClientIntent;
pub mod ClientIntentionPacket;
pub mod HandshakePacketTypes;
pub mod HandshakeProtocols;
pub mod ServerHandshakePacketListener;
#[path = "package-info.rs"]
pub mod package_info;
