//! Module declarations for `com.mojang.blaze3d.opengl` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BufferStorage;
pub mod DirectStateAccess;
pub mod FrameBufferAttachment;
pub mod FrameBufferCache;
pub mod GlBackend;
pub mod GlBuffer;
pub mod GlCommandEncoder;
pub mod GlConst;
pub mod GlDebug;
pub mod GlDebugLabel;
pub mod GlDevice;
pub mod GlFence;
pub mod GlHeuristics;
pub mod GlProgram;
pub mod GlQueryPool;
pub mod GlRenderPass;
pub mod GlRenderPipeline;
pub mod GlSampler;
pub mod GlShaderModule;
pub mod GlStateManager;
pub mod GlSurface;
pub mod GlTexture;
pub mod GlTextureView;
pub mod GlTransientMemory;
pub mod GlUtil;
pub mod Uniform;
pub mod VertexArrayCache;
#[path = "package-info.rs"]
pub mod package_info;
