//! Module declarations for `net.minecraft.client.data.models` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod blockstates;
pub mod model;

pub mod BlockModelGenerators;
pub mod EquipmentAssetProvider;
pub mod ItemModelGenerators;
pub mod ItemModelOutput;
pub mod ModelProvider;
pub mod MultiVariant;
pub mod WaypointStyleProvider;
#[path = "package-info.rs"]
pub mod package_info;
