//! Module declarations for `net.minecraft.client.gui.components.toasts` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AdvancementToast;
pub mod FriendToast;
pub mod NowPlayingToast;
pub mod RecipeToast;
pub mod SystemToast;
pub mod Toast;
pub mod ToastManager;
pub mod TutorialToast;
#[path = "package-info.rs"]
pub mod package_info;
