//! Module declarations for `net.minecraft.world.level.gameevent` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod vibrations;

pub mod BlockPositionSource;
pub mod DynamicGameEventListener;
pub mod EntityPositionSource;
pub mod EuclideanGameEventListenerRegistry;
pub mod GameEvent;
pub mod GameEventDispatcher;
pub mod GameEventListener;
pub mod GameEventListenerRegistry;
pub mod PositionSource;
pub mod PositionSourceType;
#[path = "package-info.rs"]
pub mod package_info;
