//! Module declarations for `net.minecraft.client.gui.screens.options.controls` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod ControlsScreen;
pub mod KeyBindsList;
pub mod KeyBindsScreen;
#[path = "package-info.rs"]
pub mod package_info;
