//! Module declarations for `com.mojang.blaze3d.vulkan.checkpoints` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractCheckpointStorage;
pub mod AmdCheckpointExtension;
pub mod CheckpointExtension;
pub mod NoopCheckpointExtension;
pub mod NvidiaCheckpointExtension;
#[path = "package-info.rs"]
pub mod package_info;
