//! Module declarations for `net.minecraft.client.color.block` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BlockColors;
pub mod BlockTintCache;
pub mod BlockTintSource;
pub mod BlockTintSources;
#[path = "package-info.rs"]
pub mod package_info;
