//! Module declarations for `net.minecraft.client.model.animal.equine` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractEquineModel;
pub mod BabyDonkeyModel;
pub mod BabyHorseModel;
pub mod DonkeyModel;
pub mod EquineSaddleModel;
pub mod HorseModel;
#[path = "package-info.rs"]
pub mod package_info;
