//! Module declarations for `net.minecraft.world.entity.animal.cow` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractCow;
pub mod Cow;
pub mod CowSoundVariant;
pub mod CowSoundVariants;
pub mod CowVariant;
pub mod CowVariants;
pub mod MushroomCow;
#[path = "package-info.rs"]
pub mod package_info;
