//! Module declarations for `net.minecraft.world.level.storage.loot.providers.number` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BinomialDistributionGenerator;
pub mod ConstantValue;
pub mod EnchantmentLevelProvider;
pub mod EnvironmentAttributeValue;
pub mod NumberProvider;
pub mod NumberProviders;
pub mod ScoreboardValue;
pub mod StorageValue;
pub mod Sum;
pub mod UniformGenerator;
#[path = "package-info.rs"]
pub mod package_info;
