//! Module declarations for `net.minecraft.world.entity.item` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod FallingBlockEntity;
pub mod ItemEntity;
pub mod PrimedTnt;
#[path = "package-info.rs"]
pub mod package_info;
