//! Module declarations for `net.minecraft.client.model.player` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod PlayerCapeModel;
pub mod PlayerEarsModel;
pub mod PlayerModel;
#[path = "package-info.rs"]
pub mod package_info;
