//! Module declarations for `net.minecraft.client.renderer.block.model` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod properties;

pub mod BlockDisplayContext;
pub mod BlockModel;
pub mod BlockStateModelWrapper;
pub mod CompositeBlockModel;
pub mod ConditionalBlockModel;
pub mod EmptyBlockModel;
pub mod SpecialBlockModelWrapper;
#[path = "package-info.rs"]
pub mod package_info;
