//! Module declarations for `net.minecraft.core.component.predicates` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AnyValue;
pub mod AttributeModifiersPredicate;
pub mod BundlePredicate;
pub mod ContainerPredicate;
pub mod CustomDataPredicate;
pub mod DamagePredicate;
pub mod DataComponentPredicate;
pub mod DataComponentPredicates;
pub mod EnchantmentsPredicate;
pub mod FireworkExplosionPredicate;
pub mod FireworksPredicate;
pub mod JukeboxPlayablePredicate;
pub mod PotionsPredicate;
pub mod TrimPredicate;
pub mod VillagerTypePredicate;
pub mod WritableBookPredicate;
pub mod WrittenBookPredicate;
#[path = "package-info.rs"]
pub mod package_info;
