//! Module declarations for `net.minecraft.world.entity.ai.gossip` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod GossipContainer;
pub mod GossipType;
#[path = "package-info.rs"]
pub mod package_info;
