//! Module declarations for `net.minecraft.world.level.levelgen.feature.rootplacers` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AboveRootPlacement;
pub mod MangroveRootPlacement;
pub mod MangroveRootPlacer;
pub mod RootPlacer;
pub mod RootPlacerType;
#[path = "package-info.rs"]
pub mod package_info;
