//! Module declarations for `net.minecraft.client.resources.language` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod ClientLanguage;
pub mod FormattedBidiReorder;
pub mod I18n;
pub mod LanguageInfo;
pub mod LanguageManager;
#[path = "package-info.rs"]
pub mod package_info;
