//! Module declarations for `com.mojang.blaze3d.font` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod GlyphBitmap;
pub mod GlyphInfo;
pub mod GlyphProvider;
pub mod SpaceProvider;
pub mod TrueTypeGlyphProvider;
pub mod UnbakedGlyph;
#[path = "package-info.rs"]
pub mod package_info;
