//! Module declarations for `net.minecraft.network.protocol.common.custom` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BrandPayload;
pub mod CustomPacketPayload;
pub mod DiscardedPayload;
#[path = "package-info.rs"]
pub mod package_info;
