//! Module declarations for `net.minecraft.client.gui.render.pip` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod GuiBannerResultRenderer;
pub mod GuiBookModelRenderer;
pub mod GuiEntityRenderer;
pub mod GuiProfilerChartRenderer;
pub mod GuiSkinRenderer;
pub mod OversizedItemRenderer;
pub mod PictureInPictureRenderer;
#[path = "package-info.rs"]
pub mod package_info;
