//! Module declarations for `net.minecraft.world.level.levelgen.feature.foliageplacers` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AcaciaFoliagePlacer;
pub mod BlobFoliagePlacer;
pub mod BushFoliagePlacer;
pub mod CherryFoliagePlacer;
pub mod DarkOakFoliagePlacer;
pub mod FancyFoliagePlacer;
pub mod FoliagePlacer;
pub mod FoliagePlacerType;
pub mod MegaJungleFoliagePlacer;
pub mod MegaPineFoliagePlacer;
pub mod PineFoliagePlacer;
pub mod RandomSpreadFoliagePlacer;
pub mod SpruceFoliagePlacer;
#[path = "package-info.rs"]
pub mod package_info;
