//! Module declarations for `net.minecraft.data.loot.packs` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod TradeRebalanceChestLoot;
pub mod TradeRebalanceLootTableProvider;
pub mod VanillaArchaeologyLoot;
pub mod VanillaBlockInteractLoot;
pub mod VanillaBlockLoot;
pub mod VanillaChargedCreeperExplosionLoot;
pub mod VanillaChestLoot;
pub mod VanillaEntityInteractLoot;
pub mod VanillaEntityLoot;
pub mod VanillaEquipmentLoot;
pub mod VanillaFishingLoot;
pub mod VanillaGiftLoot;
pub mod VanillaLootTableProvider;
pub mod VanillaPiglinBarterLoot;
pub mod VanillaShearingLoot;
#[path = "package-info.rs"]
pub mod package_info;
