//! Module declarations for `net.minecraft.realms` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod RealmsConnect;
pub mod RealmsScreen;
pub mod RepeatedNarrator;
#[path = "package-info.rs"]
pub mod package_info;
