//! Module declarations for `net.minecraft.client.renderer.blockentity.state` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BannerRenderState;
pub mod BeaconRenderState;
pub mod BedRenderState;
pub mod BellRenderState;
pub mod BlockEntityRenderState;
pub mod BlockEntityWithBoundingBoxRenderState;
pub mod BrushableBlockRenderState;
pub mod CampfireRenderState;
pub mod ChestRenderState;
pub mod ConduitRenderState;
pub mod CopperGolemStatueRenderState;
pub mod DecoratedPotRenderState;
pub mod EnchantTableRenderState;
pub mod EndGatewayRenderState;
pub mod EndPortalRenderState;
pub mod HangingSignRenderState;
pub mod LecternRenderState;
pub mod PistonHeadRenderState;
pub mod ShelfRenderState;
pub mod ShulkerBoxRenderState;
pub mod SignRenderState;
pub mod SkullBlockRenderState;
pub mod SpawnerRenderState;
pub mod StandingSignRenderState;
pub mod TestInstanceRenderState;
pub mod VaultRenderState;
#[path = "package-info.rs"]
pub mod package_info;
