//! Module declarations for `net.minecraft.server.permissions` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod LevelBasedPermissionSet;
pub mod Permission;
pub mod PermissionCheck;
pub mod PermissionCheckTypes;
pub mod PermissionLevel;
pub mod PermissionProviderCheck;
pub mod PermissionSet;
pub mod PermissionSetSupplier;
pub mod PermissionSetUnion;
pub mod PermissionTypes;
pub mod Permissions;
#[path = "package-info.rs"]
pub mod package_info;
