//! Module declarations for `net.minecraft.client.renderer.item.properties.select` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod Charge;
pub mod ComponentContents;
pub mod ContextDimension;
pub mod ContextEntityType;
pub mod CustomModelDataProperty;
pub mod DisplayContext;
pub mod ItemBlockState;
pub mod LocalTime;
pub mod MainHand;
pub mod SelectItemModelProperties;
pub mod SelectItemModelProperty;
pub mod TrimMaterialProperty;
#[path = "package-info.rs"]
pub mod package_info;
