//! Module declarations for `net.minecraft.world.timeline` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AttributeTrack;
pub mod AttributeTrackSampler;
pub mod Timeline;
pub mod Timelines;
#[path = "package-info.rs"]
pub mod package_info;
