//! Module declarations for `net.minecraft.world.level.levelgen.feature.treedecorators` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AlterGroundDecorator;
pub mod AttachedToLeavesDecorator;
pub mod AttachedToLogsDecorator;
pub mod BeehiveDecorator;
pub mod CocoaDecorator;
pub mod CreakingHeartDecorator;
pub mod LeaveVineDecorator;
pub mod PaleMossDecorator;
pub mod PlaceOnGroundDecorator;
pub mod TreeDecorator;
pub mod TreeDecoratorType;
pub mod TrunkVineDecorator;
#[path = "package-info.rs"]
pub mod package_info;
