//! Module declarations for `net.minecraft.client.gui.screens.dialog` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod body;
pub mod input;

pub mod ButtonListDialogScreen;
pub mod DialogConnectionAccess;
pub mod DialogControlSet;
pub mod DialogListDialogScreen;
pub mod DialogScreen;
pub mod DialogScreens;
pub mod MultiButtonDialogScreen;
pub mod ServerLinksDialogScreen;
pub mod SimpleDialogScreen;
pub mod WaitingForResponseScreen;
#[path = "package-info.rs"]
pub mod package_info;
