//! Module declarations for `net.minecraft.client.renderer.item.properties.numeric` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BundleFullness;
pub mod CompassAngle;
pub mod CompassAngleState;
pub mod Cooldown;
pub mod Count;
pub mod CrossbowPull;
pub mod CustomModelDataProperty;
pub mod Damage;
pub mod NeedleDirectionHelper;
pub mod RangeSelectItemModelProperties;
pub mod RangeSelectItemModelProperty;
pub mod Time;
pub mod UseCycle;
pub mod UseDuration;
#[path = "package-info.rs"]
pub mod package_info;
