//! Module declarations for `net.minecraft.world.level.levelgen.blockpredicates` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AllOfPredicate;
pub mod AnyOfPredicate;
pub mod BlockPredicate;
pub mod BlockPredicateType;
pub mod CombiningPredicate;
pub mod HasSturdyFacePredicate;
pub mod InsideWorldBoundsPredicate;
pub mod MatchingBiomesPredicate;
pub mod MatchingBlockTagPredicate;
pub mod MatchingBlocksPredicate;
pub mod MatchingFluidsPredicate;
pub mod NotPredicate;
pub mod ReplaceablePredicate;
pub mod SolidPredicate;
pub mod StateTestingPredicate;
pub mod TrueBlockPredicate;
pub mod UnobstructedPredicate;
pub mod WouldSurvivePredicate;
#[path = "package-info.rs"]
pub mod package_info;
