//! Module declarations for `net.minecraft.data.recipes` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod packs;

pub mod CustomCraftingRecipeBuilder;
pub mod RecipeBuilder;
pub mod RecipeCategory;
pub mod RecipeOutput;
pub mod RecipeProvider;
pub mod RecipeUnlockAdvancementBuilder;
pub mod ShapedRecipeBuilder;
pub mod ShapelessRecipeBuilder;
pub mod SimpleCookingRecipeBuilder;
pub mod SingleItemRecipeBuilder;
pub mod SmithingTransformRecipeBuilder;
pub mod SmithingTrimRecipeBuilder;
pub mod SpecialRecipeBuilder;
pub mod TransmuteRecipeBuilder;
#[path = "package-info.rs"]
pub mod package_info;
