//! Module declarations for `net.minecraft.tags` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BannerPatternTags;
pub mod BiomeTags;
pub mod BlockItemTagId;
pub mod BlockItemTags;
pub mod BlockTags;
pub mod DamageTypeTags;
pub mod DialogTags;
pub mod EnchantmentTags;
pub mod EntityTypeTags;
pub mod FeatureTags;
pub mod FlatLevelGeneratorPresetTags;
pub mod FluidTags;
pub mod GameEventTags;
pub mod InstrumentTags;
pub mod ItemTags;
pub mod PaintingVariantTags;
pub mod PoiTypeTags;
pub mod PotionTags;
pub mod StructureTags;
pub mod TagBuilder;
pub mod TagEntry;
pub mod TagFile;
pub mod TagKey;
pub mod TagLoader;
pub mod TagNetworkSerialization;
pub mod TimelineTags;
pub mod VillagerTradeTags;
pub mod WorldPresetTags;
#[path = "package-info.rs"]
pub mod package_info;
