//! Module declarations for `net.minecraft.world.item.component` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AttackRange;
pub mod Bees;
pub mod BlockItemStateProperties;
pub mod BlocksAttacks;
pub mod BookContent;
pub mod BundleContents;
pub mod ChargedProjectiles;
pub mod Consumable;
pub mod ConsumableListener;
pub mod Consumables;
pub mod CustomData;
pub mod CustomModelData;
pub mod DamageResistant;
pub mod DeathProtection;
pub mod DebugStickState;
pub mod DyedItemColor;
pub mod FireworkExplosion;
pub mod Fireworks;
pub mod InstrumentComponent;
pub mod ItemAttributeModifiers;
pub mod ItemContainerContents;
pub mod ItemLore;
pub mod KineticWeapon;
pub mod LodestoneTracker;
pub mod MapDecorations;
pub mod MapItemColor;
pub mod MapPostProcessing;
pub mod OminousBottleAmplifier;
pub mod PiercingWeapon;
pub mod ProvidesTrimMaterial;
pub mod ResolvableProfile;
pub mod SeededContainerLoot;
pub mod SulfurCubeContent;
pub mod SuspiciousStewEffects;
pub mod SwingAnimation;
pub mod Tool;
pub mod TooltipDisplay;
pub mod TooltipProvider;
pub mod TypedEntityData;
pub mod UseCooldown;
pub mod UseEffects;
pub mod UseRemainder;
pub mod Weapon;
pub mod WritableBookContent;
pub mod WrittenBookContent;
#[path = "package-info.rs"]
pub mod package_info;
