//! Module declarations for `net.minecraft.client.model.animal.chicken` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AdultChickenModel;
pub mod BabyChickenModel;
pub mod ChickenModel;
pub mod ColdChickenModel;
#[path = "package-info.rs"]
pub mod package_info;
