//! Module declarations for `net.minecraft.client.gui.screens.reporting` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractReportScreen;
pub mod ChatReportScreen;
pub mod ChatSelectionLogFiller;
pub mod ChatSelectionScreen;
pub mod NameReportScreen;
pub mod ReportPlayerScreen;
pub mod ReportReasonSelectionScreen;
pub mod SkinReportScreen;
#[path = "package-info.rs"]
pub mod package_info;
