//! Module declarations for `net.minecraft.world.level.levelgen.placement` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BiomeFilter;
pub mod BlockPredicateFilter;
pub mod CaveSurface;
pub mod CountOnEveryLayerPlacement;
pub mod CountPlacement;
pub mod EnvironmentScanPlacement;
pub mod FixedPlacement;
pub mod HeightRangePlacement;
pub mod HeightmapPlacement;
pub mod InSquarePlacement;
pub mod NoiseBasedCountPlacement;
pub mod NoiseThresholdCountPlacement;
pub mod PlacedFeature;
pub mod PlacementContext;
pub mod PlacementFilter;
pub mod PlacementModifier;
pub mod PlacementModifierType;
pub mod RandomOffsetPlacement;
pub mod RarityFilter;
pub mod RepeatingPlacement;
pub mod SurfaceRelativeThresholdFilter;
pub mod SurfaceWaterDepthFilter;
#[path = "package-info.rs"]
pub mod package_info;
