//! Module declarations for `net.minecraft.world.entity.monster.cubemob` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractCubeMob;
pub mod MagmaCube;
pub mod Slime;
pub mod SulfurCube;
#[path = "package-info.rs"]
pub mod package_info;
