//! Module declarations for `net.minecraft.client.resources.sounds` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractSoundInstance;
pub mod AbstractTickableSoundInstance;
pub mod AmbientSoundHandler;
pub mod BeeAggressiveSoundInstance;
pub mod BeeFlyingSoundInstance;
pub mod BeeSoundInstance;
pub mod BiomeAmbientSoundsHandler;
pub mod BubbleColumnAmbientSoundHandler;
pub mod DirectionalSoundInstance;
pub mod ElytraOnPlayerSoundInstance;
pub mod EntityBoundSoundInstance;
pub mod GuardianAttackSoundInstance;
pub mod MinecartSoundInstance;
pub mod RidingEntitySoundInstance;
pub mod RidingMinecartSoundInstance;
pub mod SimpleSoundInstance;
pub mod SnifferSoundInstance;
pub mod Sound;
pub mod SoundEventRegistration;
pub mod SoundEventRegistrationSerializer;
pub mod SoundInstance;
pub mod TickableSoundInstance;
pub mod UnderwaterAmbientSoundHandler;
pub mod UnderwaterAmbientSoundInstances;
#[path = "package-info.rs"]
pub mod package_info;
