//! Module declarations for `net.minecraft.client.model.animal.bee` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AdultBeeModel;
pub mod BabyBeeModel;
pub mod BeeModel;
pub mod BeeStingerModel;
#[path = "package-info.rs"]
pub mod package_info;
