//! Module declarations for `net.minecraft.commands.synchronization` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod brigadier;

pub mod ArgumentTypeInfo;
pub mod ArgumentTypeInfos;
pub mod ArgumentUtils;
pub mod SingletonArgumentInfo;
pub mod SuggestionProviders;
#[path = "package-info.rs"]
pub mod package_info;
