//! Module declarations for `net.minecraft.client.model.object.boat` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractBoatModel;
pub mod BoatModel;
pub mod RaftModel;
#[path = "package-info.rs"]
pub mod package_info;
