//! Module declarations for `com.mojang.realmsclient.util` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod task;

pub mod JsonUtils;
pub mod RealmsPersistence;
pub mod RealmsTextureManager;
pub mod RealmsUtil;
pub mod TextRenderingUtils;
pub mod UploadTokenCache;
#[path = "package-info.rs"]
pub mod package_info;
