//! Module declarations for `net.minecraft.client.renderer.state` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod gui;
pub mod level;

pub mod GameRenderState;
pub mod LightmapRenderState;
pub mod MapRenderState;
pub mod OptionsRenderState;
pub mod WindowRenderState;
#[path = "package-info.rs"]
pub mod package_info;
