//! Module declarations for `net.minecraft.world.item.alchemy` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod Potion;
pub mod PotionBrewing;
pub mod PotionContents;
pub mod PotionIds;
pub mod Potions;
#[path = "package-info.rs"]
pub mod package_info;
