//! Module declarations for `net.minecraft.client.animation` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod definitions;

pub mod AnimationChannel;
pub mod AnimationDefinition;
pub mod Keyframe;
pub mod KeyframeAnimation;
pub mod KeyframeAnimations;
#[path = "package-info.rs"]
pub mod package_info;
