//! Module declarations for `net.minecraft.util.debug` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod DebugBeeInfo;
pub mod DebugBrainDump;
pub mod DebugBreezeInfo;
pub mod DebugEntityBlockIntersection;
pub mod DebugGameEventInfo;
pub mod DebugGameEventListenerInfo;
pub mod DebugGoalInfo;
pub mod DebugHiveInfo;
pub mod DebugPathInfo;
pub mod DebugPoiInfo;
pub mod DebugStructureInfo;
pub mod DebugSubscription;
pub mod DebugSubscriptions;
pub mod DebugValueAccess;
pub mod DebugValueSource;
pub mod LevelDebugSynchronizers;
pub mod ServerDebugSubscribers;
pub mod TrackingDebugSynchronizer;
#[path = "package-info.rs"]
pub mod package_info;
