//! Module declarations for `net.minecraft.world.entity.boss.enderdragon.phases` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractDragonPhaseInstance;
pub mod AbstractDragonSittingPhase;
pub mod DragonChargePlayerPhase;
pub mod DragonDeathPhase;
pub mod DragonHoldingPatternPhase;
pub mod DragonHoverPhase;
pub mod DragonLandingApproachPhase;
pub mod DragonLandingPhase;
pub mod DragonPhaseInstance;
pub mod DragonSittingAttackingPhase;
pub mod DragonSittingFlamingPhase;
pub mod DragonSittingScanningPhase;
pub mod DragonStrafePlayerPhase;
pub mod DragonTakeoffPhase;
pub mod EnderDragonPhase;
pub mod EnderDragonPhaseManager;
#[path = "package-info.rs"]
pub mod package_info;
