//! Module declarations for `net.minecraft.client.gui.screens.friends` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractFriendsEntryContainerWidget;
pub mod AbstractFriendsTab;
pub mod AddFriendWidget;
pub mod FriendEntry;
pub mod FriendsListConfirmScreen;
pub mod FriendsOverlayScreen;
pub mod FriendsOverlayTabButton;
pub mod FriendsTab;
pub mod IncomingEntry;
pub mod OutgoingEntry;
pub mod PendingTab;
#[path = "package-info.rs"]
pub mod package_info;
