//! Module declarations for `net.minecraft.client.gui.screens.inventory` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod tooltip;

pub mod AbstractCommandBlockEditScreen;
pub mod AbstractContainerScreen;
pub mod AbstractFurnaceScreen;
pub mod AbstractMountInventoryScreen;
pub mod AbstractRecipeBookScreen;
pub mod AbstractSignEditScreen;
pub mod AnvilScreen;
pub mod BeaconScreen;
pub mod BlastFurnaceScreen;
pub mod BookEditScreen;
pub mod BookSignScreen;
pub mod BookViewScreen;
pub mod BrewingStandScreen;
pub mod CartographyTableScreen;
pub mod CommandBlockEditScreen;
pub mod ContainerScreen;
pub mod CrafterScreen;
pub mod CraftingScreen;
pub mod CreativeInventoryListener;
pub mod CreativeModeInventoryScreen;
pub mod CyclingSlotBackground;
pub mod DispenserScreen;
pub mod EffectsInInventory;
pub mod EnchantmentNames;
pub mod EnchantmentScreen;
pub mod FurnaceScreen;
pub mod GrindstoneScreen;
pub mod HangingSignEditScreen;
pub mod HopperScreen;
pub mod HorseInventoryScreen;
pub mod InventoryScreen;
pub mod ItemCombinerScreen;
pub mod JigsawBlockEditScreen;
pub mod LecternScreen;
pub mod LoomScreen;
pub mod MenuAccess;
pub mod MerchantScreen;
pub mod MinecartCommandBlockEditScreen;
pub mod NautilusInventoryScreen;
pub mod PageButton;
pub mod ShulkerBoxScreen;
pub mod SignEditScreen;
pub mod SmithingScreen;
pub mod SmokerScreen;
pub mod StonecutterScreen;
pub mod StructureBlockEditScreen;
pub mod TestBlockEditScreen;
pub mod TestInstanceBlockEditScreen;
#[path = "package-info.rs"]
pub mod package_info;
