//! Module declarations for `net.minecraft.world.level.levelgen.structure.pools` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod alias;

pub mod DimensionPadding;
pub mod EmptyPoolElement;
pub mod FeaturePoolElement;
pub mod JigsawJunction;
pub mod JigsawPlacement;
pub mod LegacySinglePoolElement;
pub mod ListPoolElement;
pub mod SinglePoolElement;
pub mod StructurePoolElement;
pub mod StructurePoolElementType;
pub mod StructureTemplatePool;
#[path = "package-info.rs"]
pub mod package_info;
