//! Module declarations for `net.minecraft.client.data.models.blockstates` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BlockModelDefinitionGenerator;
pub mod ConditionBuilder;
pub mod MultiPartGenerator;
pub mod MultiVariantGenerator;
pub mod PropertyDispatch;
pub mod PropertyValueList;
#[path = "package-info.rs"]
pub mod package_info;
