//! Module declarations for `net.minecraft.world.entity.vehicle.boat` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractBoat;
pub mod AbstractChestBoat;
pub mod Boat;
pub mod ChestBoat;
pub mod ChestRaft;
pub mod Raft;
#[path = "package-info.rs"]
pub mod package_info;
