//! Module declarations for `net.minecraft.world.item.equipment` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod trim;

pub mod AllowedEntitiesProvider;
pub mod ArmorMaterial;
pub mod ArmorMaterials;
pub mod ArmorType;
pub mod EquipmentAsset;
pub mod EquipmentAssets;
pub mod Equippable;
#[path = "package-info.rs"]
pub mod package_info;
