//! Module declarations for `net.minecraft.world.entity.ai.control` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BodyRotationControl;
pub mod Control;
pub mod FlyingMoveControl;
pub mod JumpControl;
pub mod LookControl;
pub mod MoveControl;
pub mod SmoothSwimmingLookControl;
pub mod SmoothSwimmingMoveControl;
#[path = "package-info.rs"]
pub mod package_info;
