//! Module declarations for `net.minecraft.data.worldgen` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod biome;
pub mod features;
pub mod placement;

pub mod AncientCityStructurePieces;
pub mod AncientCityStructurePools;
pub mod BastionBridgePools;
pub mod BastionHoglinStablePools;
pub mod BastionHousingUnitsPools;
pub mod BastionPieces;
pub mod BastionSharedPools;
pub mod BastionTreasureRoomPools;
pub mod BiomeDefaultFeatures;
pub mod BootstrapContext;
pub mod Carvers;
pub mod DesertVillagePools;
pub mod DimensionTypes;
pub mod NoiseData;
pub mod PillagerOutpostPools;
pub mod PlainVillagePools;
pub mod Pools;
pub mod ProcessorLists;
pub mod SavannaVillagePools;
pub mod SnowyVillagePools;
pub mod StructureSets;
pub mod Structures;
pub mod SurfaceRuleData;
pub mod TaigaVillagePools;
pub mod TerrainProvider;
pub mod TrailRuinsStructurePools;
pub mod TrialChambersStructurePools;
pub mod VillagePools;
#[path = "package-info.rs"]
pub mod package_info;
