//! Module declarations for `net.minecraft.client.gui.render` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod pip;

pub mod DynamicAtlasAllocator;
pub mod GuiItemAtlas;
pub mod GuiRenderer;
pub mod TextureSetup;
#[path = "package-info.rs"]
pub mod package_info;
