//! Module declarations for `net.minecraft.client.model.object.projectile` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod ArrowModel;
pub mod ShulkerBulletModel;
pub mod TridentModel;
pub mod WindChargeModel;
#[path = "package-info.rs"]
pub mod package_info;
