//! Module declarations for `net.minecraft.world.entity.monster.zombie` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod Drowned;
pub mod Husk;
pub mod Zombie;
pub mod ZombieVillager;
pub mod ZombifiedPiglin;
#[path = "package-info.rs"]
pub mod package_info;
