//! Module declarations for `net.minecraft.world.level.material` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod EmptyFluid;
pub mod FlowingFluid;
pub mod Fluid;
pub mod FluidIds;
pub mod FluidState;
pub mod Fluids;
pub mod FogType;
pub mod LavaFluid;
pub mod MapColor;
pub mod PushReaction;
pub mod WaterFluid;
#[path = "package-info.rs"]
pub mod package_info;
