//! Module declarations for `net.minecraft.util.profiling.jfr` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod callback;
pub mod event;
pub mod parse;
pub mod serialize;
pub mod stats;

pub mod Environment;
pub mod JfrProfiler;
pub mod JvmProfiler;
pub mod Percentiles;
pub mod SummaryReporter;
#[path = "package-info.rs"]
pub mod package_info;
