//! Module declarations for `net.minecraft.world.entity.decoration` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod painting;

pub mod ArmorStand;
pub mod BlockAttachedEntity;
pub mod GlowItemFrame;
pub mod HangingEntity;
pub mod ItemFrame;
pub mod LeashFenceKnotEntity;
pub mod Mannequin;
#[path = "package-info.rs"]
pub mod package_info;
