//! Module declarations for `net.minecraft.network.chat.contents.objects` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AtlasSprite;
pub mod ObjectInfo;
pub mod ObjectInfos;
pub mod PlayerSprite;
#[path = "package-info.rs"]
pub mod package_info;
