//! Module declarations for `net.minecraft.client.model.monster.piglin` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractPiglinModel;
pub mod AdultPiglinModel;
pub mod AdultZombifiedPiglinModel;
pub mod BabyPiglinModel;
pub mod BabyZombifiedPiglinModel;
pub mod PiglinModel;
pub mod ZombifiedPiglinModel;
#[path = "package-info.rs"]
pub mod package_info;
