//! Module declarations for `net.minecraft.core.dispenser` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BlockSource;
pub mod BoatDispenseItemBehavior;
pub mod DefaultDispenseItemBehavior;
pub mod DispenseItemBehavior;
pub mod EquipmentDispenseItemBehavior;
pub mod FlintAndSteelDispenseItemBehavior;
pub mod MinecartDispenseItemBehavior;
pub mod OptionalDispenseItemBehavior;
pub mod ProjectileDispenseBehavior;
pub mod ShearsDispenseItemBehavior;
pub mod ShulkerBoxDispenseBehavior;
pub mod SpawnEggItemBehavior;
pub mod SulfurCubeBlockDispenseItemBehavior;
#[path = "package-info.rs"]
pub mod package_info;
