//! Module declarations for `net.minecraft.world.level.saveddata` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod maps;

pub mod SavedData;
pub mod SavedDataType;
pub mod WanderingTraderData;
pub mod WeatherData;
#[path = "package-info.rs"]
pub mod package_info;
