//! Module declarations for `net.minecraft.world.level.storage.loot.functions` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod ApplyBonusCount;
pub mod ApplyExplosionDecay;
pub mod CopyBlockState;
pub mod CopyComponentsFunction;
pub mod CopyCustomDataFunction;
pub mod CopyNameFunction;
pub mod DiscardItem;
pub mod EnchantRandomlyFunction;
pub mod EnchantWithLevelsFunction;
pub mod EnchantedCountIncreaseFunction;
pub mod ExplorationMapFunction;
pub mod FillPlayerHead;
pub mod FilteredFunction;
pub mod FunctionReference;
pub mod FunctionUserBuilder;
pub mod LimitCount;
pub mod ListOperation;
pub mod LootItemConditionalFunction;
pub mod LootItemFunction;
pub mod LootItemFunctions;
pub mod ModifyContainerContents;
pub mod SequenceFunction;
pub mod SetAttributesFunction;
pub mod SetBannerPatternFunction;
pub mod SetBookCoverFunction;
pub mod SetComponentsFunction;
pub mod SetContainerContents;
pub mod SetContainerLootTable;
pub mod SetCustomDataFunction;
pub mod SetCustomModelDataFunction;
pub mod SetEnchantmentsFunction;
pub mod SetFireworkExplosionFunction;
pub mod SetFireworksFunction;
pub mod SetInstrumentFunction;
pub mod SetItemCountFunction;
pub mod SetItemDamageFunction;
pub mod SetItemFunction;
pub mod SetLoreFunction;
pub mod SetNameFunction;
pub mod SetOminousBottleAmplifierFunction;
pub mod SetPotionFunction;
pub mod SetRandomDyesFunction;
pub mod SetRandomPotionFunction;
pub mod SetStewEffectFunction;
pub mod SetWritableBookPagesFunction;
pub mod SetWrittenBookPagesFunction;
pub mod SmeltItemFunction;
pub mod ToggleTooltips;
#[path = "package-info.rs"]
pub mod package_info;
