//! Module declarations for `net.minecraft.data.recipes.packs` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod VanillaRecipeProvider;
#[path = "package-info.rs"]
pub mod package_info;
