//! Module declarations for `net.minecraft.util.profiling.jfr.event` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod ChunkGenerationEvent;
pub mod ChunkRegionIoEvent;
pub mod ChunkRegionReadEvent;
pub mod ChunkRegionWriteEvent;
pub mod ClientFpsEvent;
pub mod NetworkSummaryEvent;
pub mod PacketEvent;
pub mod PacketReceivedEvent;
pub mod PacketSentEvent;
pub mod ServerTickTimeEvent;
pub mod StructureGenerationEvent;
pub mod WorldLoadFinishedEvent;
#[path = "package-info.rs"]
pub mod package_info;
