//! Module declarations for `net.minecraft.commands.functions` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod CommandFunction;
pub mod FunctionBuilder;
pub mod InstantiatedFunction;
pub mod MacroFunction;
pub mod PlainTextFunction;
pub mod StringTemplate;
#[path = "package-info.rs"]
pub mod package_info;
