//! Module declarations for `net.minecraft.world.item.crafting.display` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod DisplayContentsFactory;
pub mod FurnaceRecipeDisplay;
pub mod RecipeDisplay;
pub mod RecipeDisplayEntry;
pub mod RecipeDisplayId;
pub mod RecipeDisplays;
pub mod ShapedCraftingRecipeDisplay;
pub mod ShapelessCraftingRecipeDisplay;
pub mod SlotDisplay;
pub mod SlotDisplayContext;
pub mod SlotDisplays;
pub mod SmithingRecipeDisplay;
pub mod StonecutterRecipeDisplay;
#[path = "package-info.rs"]
pub mod package_info;
