//! Module declarations for `net.minecraft.client.model.monster.zombie` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractZombieModel;
pub mod BabyDrownedModel;
pub mod BabyZombieModel;
pub mod BabyZombieVillagerModel;
pub mod DrownedModel;
pub mod GiantZombieModel;
pub mod ZombieModel;
pub mod ZombieVillagerModel;
#[path = "package-info.rs"]
pub mod package_info;
