//! Module declarations for `net.minecraft.world.effect` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbsorptionMobEffect;
pub mod BadOmenMobEffect;
pub mod HealOrHarmMobEffect;
pub mod HungerMobEffect;
pub mod InfestedMobEffect;
pub mod InstantaneousMobEffect;
pub mod MobEffect;
pub mod MobEffectCategory;
pub mod MobEffectInstance;
pub mod MobEffectUtil;
pub mod MobEffects;
pub mod OozingMobEffect;
pub mod PoisonMobEffect;
pub mod RaidOmenMobEffect;
pub mod RegenerationMobEffect;
pub mod SaturationMobEffect;
pub mod WeavingMobEffect;
pub mod WindChargedMobEffect;
pub mod WitherMobEffect;
#[path = "package-info.rs"]
pub mod package_info;
