//! Module declarations for `net.minecraft.world.entity.ai.util` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AirAndWaterRandomPos;
pub mod AirRandomPos;
pub mod DefaultRandomPos;
pub mod GoalUtils;
pub mod HoverRandomPos;
pub mod LandRandomPos;
pub mod RandomPos;
#[path = "package-info.rs"]
pub mod package_info;
