//! Module declarations for `net.minecraft.world.level.levelgen.feature.stateproviders` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BlockStateProvider;
pub mod BlockStateProviderType;
pub mod DualNoiseProvider;
pub mod NoiseBasedStateProvider;
pub mod NoiseProvider;
pub mod NoiseThresholdProvider;
pub mod RandomizedIntStateProvider;
pub mod RotatedBlockProvider;
pub mod RuleBasedStateProvider;
pub mod SimpleStateProvider;
pub mod WeightedStateProvider;
#[path = "package-info.rs"]
pub mod package_info;
