//! Module declarations for `net.minecraft.util.filefix.operations` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod ApplyInFolders;
pub mod DeleteFileOrEmptyDirectory;
pub mod FileFixOperation;
pub mod FileFixOperations;
pub mod GroupMove;
pub mod ModifyContent;
pub mod Move;
pub mod RegexMove;
#[path = "package-info.rs"]
pub mod package_info;
