//! Module declarations for `net.minecraft.advancements.triggers` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AnyBlockInteractionTrigger;
pub mod BeeNestDestroyedTrigger;
pub mod BredAnimalsTrigger;
pub mod BrewedPotionTrigger;
pub mod ChangeDimensionTrigger;
pub mod ChanneledLightningTrigger;
pub mod ConstructBeaconTrigger;
pub mod ConsumeItemTrigger;
pub mod CriteriaTriggers;
pub mod Criterion;
pub mod CriterionTrigger;
pub mod CuredZombieVillagerTrigger;
pub mod DefaultBlockInteractionTrigger;
pub mod DistanceTrigger;
pub mod EffectsChangedTrigger;
pub mod EnchantedItemTrigger;
pub mod EnterBlockTrigger;
pub mod EntityHurtPlayerTrigger;
pub mod FallAfterExplosionTrigger;
pub mod FilledBucketTrigger;
pub mod FishingRodHookedTrigger;
pub mod ImpossibleTrigger;
pub mod InventoryChangeTrigger;
pub mod ItemDurabilityTrigger;
pub mod ItemUsedOnLocationTrigger;
pub mod KilledByArrowTrigger;
pub mod KilledTrigger;
pub mod LevitationTrigger;
pub mod LightningStrikeTrigger;
pub mod LootTableTrigger;
pub mod PickedUpItemTrigger;
pub mod PlayerHurtEntityTrigger;
pub mod PlayerInteractTrigger;
pub mod PlayerTrigger;
pub mod RecipeCraftedTrigger;
pub mod RecipeUnlockedTrigger;
pub mod ShotCrossbowTrigger;
pub mod SimpleCriterionTrigger;
pub mod SlideDownBlockTrigger;
pub mod SpearMobsTrigger;
pub mod StartRidingTrigger;
pub mod SummonedEntityTrigger;
pub mod TameAnimalTrigger;
pub mod TargetBlockTrigger;
pub mod TradeTrigger;
pub mod UsedEnderEyeTrigger;
pub mod UsedTotemTrigger;
pub mod UsingItemTrigger;
#[path = "package-info.rs"]
pub mod package_info;
