//! Module declarations for `net.minecraft.world.entity.animal.axolotl` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod Axolotl;
pub mod AxolotlAi;
pub mod PlayDead;
pub mod ValidatePlayDead;
#[path = "package-info.rs"]
pub mod package_info;
