//! Module declarations for `com.mojang.realmsclient.gui.task` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod DataFetcher;
pub mod RepeatedDelayStrategy;
#[path = "package-info.rs"]
pub mod package_info;
