//! Module declarations for `net.minecraft.client.renderer.blockentity` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod state;

pub mod AbstractEndPortalRenderer;
pub mod AbstractSignRenderer;
pub mod BannerRenderer;
pub mod BeaconRenderer;
pub mod BellRenderer;
pub mod BlockEntityRenderDispatcher;
pub mod BlockEntityRenderer;
pub mod BlockEntityRendererProvider;
pub mod BlockEntityRenderers;
pub mod BlockEntityWithBoundingBoxRenderer;
pub mod BrightnessCombiner;
pub mod BrushableBlockRenderer;
pub mod CampfireRenderer;
pub mod ChestRenderer;
pub mod ConduitRenderer;
pub mod CopperGolemStatueBlockRenderer;
pub mod DecoratedPotRenderer;
pub mod EnchantTableRenderer;
pub mod HangingSignRenderer;
pub mod LecternRenderer;
pub mod PistonHeadRenderer;
pub mod ShelfRenderer;
pub mod ShulkerBoxRenderer;
pub mod SkullBlockRenderer;
pub mod SpawnerRenderer;
pub mod StandingSignRenderer;
pub mod TestInstanceRenderer;
pub mod TheEndGatewayRenderer;
pub mod TheEndPortalRenderer;
pub mod TrialSpawnerRenderer;
pub mod VaultRenderer;
pub mod WallAndGroundTransformations;
#[path = "package-info.rs"]
pub mod package_info;
