//! Module declarations for `net.minecraft.data.worldgen.features` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AquaticFeatures;
pub mod CaveFeatures;
pub mod EndFeatures;
pub mod FeatureUtils;
pub mod MiscOverworldFeatures;
pub mod NetherFeatures;
pub mod OreFeatures;
pub mod PileFeatures;
pub mod TreeFeatures;
pub mod VegetationFeatures;
#[path = "package-info.rs"]
pub mod package_info;
