//! Module declarations for `net.minecraft.client` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod animation;
pub mod color;
pub mod data;
pub mod entity;
pub mod gui;
pub mod input;
pub mod main;
pub mod model;
pub mod multiplayer;
pub mod particle;
pub mod player;
pub mod profiling;
pub mod quickplay;
pub mod renderer;
pub mod resources;
pub mod searchtree;
pub mod server;
pub mod sounds;
pub mod telemetry;
pub mod tutorial;
pub mod waypoints;

pub mod AttackIndicatorStatus;
pub mod Camera;
pub mod CameraType;
pub mod ClientBootstrap;
pub mod ClientBrandRetriever;
pub mod ClientClockManager;
pub mod ClientRecipeBook;
pub mod CloudStatus;
pub mod CommandHistory;
pub mod ComponentCollector;
pub mod DebugQueryHandler;
pub mod DeltaTracker;
pub mod FramerateLimiter;
pub mod GameLoadCookie;
pub mod GameNarrator;
pub mod GraphicsPreset;
pub mod HotbarManager;
pub mod InactivityFpsLimit;
pub mod InputType;
pub mod KeyMapping;
pub mod KeyboardHandler;
pub mod Minecraft;
pub mod MouseHandler;
pub mod MusicToastDisplayState;
pub mod NarratorStatus;
pub mod OptionInstance;
pub mod Options;
pub mod PeriodicNotificationManager;
pub mod PreferredGraphicsApi;
pub mod PresenceSharing;
pub mod PrioritizeChunkUpdates;
pub mod ResourceLoadStateTracker;
pub mod RotatingSectionStorage;
pub mod Screenshot;
pub mod ScrollWheelHandler;
pub mod SectionUpdateTracker;
pub mod StringSplitter;
pub mod TextureFilteringMethod;
pub mod ToggleKeyMapping;
pub mod User;
#[path = "package-info.rs"]
pub mod package_info;
