//! Module declarations for `net.minecraft.client.renderer.texture.atlas.sources` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod DirectoryLister;
pub mod LazyLoadedImage;
pub mod PalettedPermutations;
pub mod SingleFile;
pub mod SourceFilter;
pub mod Unstitcher;
#[path = "package-info.rs"]
pub mod package_info;
