//! Module declarations for `com.mojang` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod blaze3d;
pub mod math;
pub mod realmsclient;
