//! Module declarations for `com.mojang.realmsclient.gui` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod screens;
pub mod task;

pub mod RealmsDataFetcher;
pub mod RealmsNewsManager;
pub mod RealmsServerList;
pub mod RealmsWorldSlotButton;
#[path = "package-info.rs"]
pub mod package_info;
