//! Module declarations for `net.minecraft.world.entity.animal.happyghast` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod HappyGhast;
pub mod HappyGhastAi;
#[path = "package-info.rs"]
pub mod package_info;
