//! Module declarations for `net.minecraft.client.renderer.entity.layers` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod ArrowLayer;
pub mod BeeStingerLayer;
pub mod BlockDecorationLayer;
pub mod BreezeEyesLayer;
pub mod BreezeWindLayer;
pub mod CapeLayer;
pub mod CarriedBlockLayer;
pub mod CatCollarLayer;
pub mod CreeperPowerLayer;
pub mod CrossedArmsItemLayer;
pub mod CustomHeadLayer;
pub mod Deadmau5EarsLayer;
pub mod DolphinCarryingItemLayer;
pub mod DrownedOuterLayer;
pub mod EnderEyesLayer;
pub mod EnergySwirlLayer;
pub mod EquipmentLayerRenderer;
pub mod EyesLayer;
pub mod FoxHeldItemLayer;
pub mod HorseMarkingLayer;
pub mod HumanoidArmorLayer;
pub mod IronGolemCrackinessLayer;
pub mod IronGolemFlowerLayer;
pub mod ItemInHandLayer;
pub mod LivingEntityEmissiveLayer;
pub mod LlamaDecorLayer;
pub mod MushroomCowMushroomLayer;
pub mod PandaHoldsItemLayer;
pub mod ParrotOnShoulderLayer;
pub mod PhantomEyesLayer;
pub mod PlayerItemInHandLayer;
pub mod RenderLayer;
pub mod RopesLayer;
pub mod SheepWoolLayer;
pub mod SheepWoolUndercoatLayer;
pub mod SimpleEquipmentLayer;
pub mod SkeletonClothingLayer;
pub mod SlimeOuterLayer;
pub mod SnowGolemHeadLayer;
pub mod SpiderEyesLayer;
pub mod SpinAttackEffectLayer;
pub mod StuckInBodyLayer;
pub mod SulfurCubeInnerLayer;
pub mod TropicalFishPatternLayer;
pub mod VillagerProfessionLayer;
pub mod WingsLayer;
pub mod WitchItemLayer;
pub mod WitherArmorLayer;
pub mod WolfArmorLayer;
pub mod WolfCollarLayer;
#[path = "package-info.rs"]
pub mod package_info;
