//! Module declarations for `net.minecraft.client.sounds` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AudioStream;
pub mod ChannelAccess;
pub mod ChunkedSampleByteBuf;
pub mod FiniteAudioStream;
pub mod FloatSampleSource;
pub mod JOrbisAudioStream;
pub mod LoopingAudioStream;
pub mod MusicManager;
pub mod SoundBufferLibrary;
pub mod SoundEngine;
pub mod SoundEngineExecutor;
pub mod SoundEventListener;
pub mod SoundManager;
pub mod SoundPreviewHandler;
pub mod WeighedSoundEvents;
pub mod Weighted;
#[path = "package-info.rs"]
pub mod package_info;
