//! Module declarations for `com.mojang.realmsclient.util.task` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod CloseServerTask;
pub mod ConnectTask;
pub mod DownloadTask;
pub mod GetServerDetailsTask;
pub mod LongRunningTask;
pub mod OpenServerTask;
pub mod RealmCreationTask;
pub mod ResettingTemplateWorldTask;
pub mod ResettingWorldTask;
pub mod RestoreTask;
pub mod SwitchMinigameTask;
pub mod SwitchSlotTask;
#[path = "package-info.rs"]
pub mod package_info;
