//! Module declarations for `net.minecraft.world.entity.animal.wolf` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod Wolf;
pub mod WolfSoundVariant;
pub mod WolfSoundVariants;
pub mod WolfVariant;
pub mod WolfVariants;
#[path = "package-info.rs"]
pub mod package_info;
