//! Module declarations for `net.minecraft.world.level.block.state` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod pattern;
pub mod predicate;
pub mod properties;

pub mod BlockBehaviour;
pub mod BlockState;
pub mod StateDefinition;
pub mod StateHolder;
#[path = "package-info.rs"]
pub mod package_info;
