//! Module declarations for `net.minecraft.world.entity.ai.goal` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod target;

pub mod AvoidEntityGoal;
pub mod BegGoal;
pub mod BreakDoorGoal;
pub mod BreathAirGoal;
pub mod BreedGoal;
pub mod CatLieOnBedGoal;
pub mod CatSitOnBlockGoal;
pub mod ClimbOnTopOfPowderSnowGoal;
pub mod DolphinJumpGoal;
pub mod DoorInteractGoal;
pub mod EatBlockGoal;
pub mod FleeSunGoal;
pub mod FloatGoal;
pub mod FollowFlockLeaderGoal;
pub mod FollowMobGoal;
pub mod FollowOwnerGoal;
pub mod FollowParentGoal;
pub mod FollowPlayerRiddenEntityGoal;
pub mod Goal;
pub mod GoalSelector;
pub mod GolemRandomStrollInVillageGoal;
pub mod InteractGoal;
pub mod JumpGoal;
pub mod LandOnOwnersShoulderGoal;
pub mod LeapAtTargetGoal;
pub mod LlamaFollowCaravanGoal;
pub mod LookAtPlayerGoal;
pub mod LookAtTradingPlayerGoal;
pub mod MeleeAttackGoal;
pub mod MoveBackToVillageGoal;
pub mod MoveThroughVillageGoal;
pub mod MoveToBlockGoal;
pub mod MoveTowardsRestrictionGoal;
pub mod MoveTowardsTargetGoal;
pub mod OcelotAttackGoal;
pub mod OfferFlowerGoal;
pub mod OpenDoorGoal;
pub mod PanicGoal;
pub mod PathfindToRaidGoal;
pub mod RandomLookAroundGoal;
pub mod RandomStandGoal;
pub mod RandomStrollGoal;
pub mod RandomSwimmingGoal;
pub mod RangedAttackGoal;
pub mod RangedBowAttackGoal;
pub mod RangedCrossbowAttackGoal;
pub mod RemoveBlockGoal;
pub mod RestrictSunGoal;
pub mod RunAroundLikeCrazyGoal;
pub mod SitWhenOrderedToGoal;
pub mod SpearUseGoal;
pub mod StrollThroughVillageGoal;
pub mod SwellGoal;
pub mod TemptGoal;
pub mod TradeWithPlayerGoal;
pub mod TryFindWaterGoal;
pub mod UseItemGoal;
pub mod WaterAvoidingRandomFlyingGoal;
pub mod WaterAvoidingRandomStrollGoal;
pub mod WrappedGoal;
pub mod ZombieAttackGoal;
#[path = "package-info.rs"]
pub mod package_info;
