//! Module declarations for `com.mojang.realmsclient.client` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod worldupload;

pub mod FileDownload;
pub mod FileUpload;
pub mod Ping;
pub mod RealmsClient;
pub mod RealmsClientConfig;
pub mod RealmsError;
pub mod Request;
pub mod UploadStatus;
#[path = "package-info.rs"]
pub mod package_info;
