//! Module declarations for `net.minecraft.client.gui.components.tabs` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod GridLayoutTab;
pub mod LoadingTab;
pub mod MenuTabBar;
pub mod Tab;
pub mod TabManager;
pub mod TabNavigationBar;
#[path = "package-info.rs"]
pub mod package_info;
