//! Module declarations for `net.minecraft.world.entity.ai.attributes` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod Attribute;
pub mod AttributeInstance;
pub mod AttributeMap;
pub mod AttributeModifier;
pub mod AttributeSupplier;
pub mod Attributes;
pub mod DefaultAttributes;
pub mod RangedAttribute;
#[path = "package-info.rs"]
pub mod package_info;
