//! Module declarations for `net.minecraft.world.level.saveddata.maps` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod MapBanner;
pub mod MapDecoration;
pub mod MapDecorationType;
pub mod MapDecorationTypes;
pub mod MapFrame;
pub mod MapId;
pub mod MapIndex;
pub mod MapItemSavedData;
#[path = "package-info.rs"]
pub mod package_info;
