//! Module declarations for `net.minecraft.commands.arguments.blocks` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BlockInput;
pub mod BlockPredicateArgument;
pub mod BlockStateArgument;
pub mod BlockStateParser;
#[path = "package-info.rs"]
pub mod package_info;
