//! Module declarations for `net.minecraft.client.main` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod GameConfig;
pub mod Main;
pub mod SilentInitException;
#[path = "package-info.rs"]
pub mod package_info;
