//! Module declarations for `net.minecraft.world.scores` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod criteria;

pub mod DisplaySlot;
pub mod Objective;
pub mod PlayerScoreEntry;
pub mod PlayerScores;
pub mod PlayerTeam;
pub mod ReadOnlyScoreInfo;
pub mod Score;
pub mod ScoreAccess;
pub mod ScoreHolder;
pub mod Scoreboard;
pub mod ScoreboardSaveData;
pub mod Team;
pub mod TeamColor;
#[path = "package-info.rs"]
pub mod package_info;
