//! Module declarations for `net.minecraft.world.item.context` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BlockPlaceContext;
pub mod DirectionalPlaceContext;
pub mod UseOnContext;
#[path = "package-info.rs"]
pub mod package_info;
