//! Module declarations for `net.minecraft` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod advancements;
pub mod client;
pub mod commands;
pub mod core;
pub mod data;
pub mod gametest;
pub mod gizmos;
pub mod locale;
pub mod nbt;
pub mod network;
pub mod realms;
pub mod recipebook;
pub mod references;
pub mod resources;
pub mod server;
pub mod sounds;
pub mod stats;
pub mod tags;
pub mod util;
pub mod world;

pub mod CharPredicate;
pub mod ChatFormatting;
pub mod CrashReport;
pub mod CrashReportCategory;
pub mod CrashReportDetail;
pub mod DefaultUncaughtExceptionHandler;
pub mod DefaultUncaughtExceptionHandlerWithName;
pub mod DetectedVersion;
pub mod ExitCodes;
pub mod IdentifierException;
pub mod Optionull;
pub mod ReportType;
pub mod ReportedException;
pub mod SharedConstants;
pub mod SuppressForbidden;
pub mod SystemReport;
pub mod TracingExecutor;
pub mod WorldVersion;
#[path = "package-info.rs"]
pub mod package_info;
