//! Module declarations for `net.minecraft.client.model.geom` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod builders;

pub mod EntityModelSet;
pub mod LayerDefinitions;
pub mod ModelLayerLocation;
pub mod ModelLayers;
pub mod ModelPart;
pub mod PartNames;
pub mod PartPose;
#[path = "package-info.rs"]
pub mod package_info;
