//! Module declarations for `net.minecraft.server.jsonrpc.api` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod MethodInfo;
pub mod ParamInfo;
pub mod PlayerDto;
pub mod ReferenceUtil;
pub mod ResultInfo;
pub mod Schema;
pub mod SchemaComponent;
#[path = "package-info.rs"]
pub mod package_info;
