//! Module declarations for `net.minecraft.commands.arguments.item` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod ComponentPredicateParser;
pub mod FunctionArgument;
pub mod ItemArgument;
pub mod ItemInput;
pub mod ItemParser;
pub mod ItemPredicateArgument;
#[path = "package-info.rs"]
pub mod package_info;
