//! Module declarations for `com.mojang.math` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod Axis;
pub mod Constants;
pub mod Divisor;
pub mod GivensParameters;
pub mod MatrixUtil;
pub mod OctahedralGroup;
pub mod Quadrant;
pub mod SymmetricGroup3;
pub mod Transformation;
#[path = "package-info.rs"]
pub mod package_info;
