// ============================================================================
// ORACLE -- not game code. Runs the ORIGINAL net.minecraft.util.Mth.
//
// Every row is (inputs as raw bits) -> (result as raw bits). Nothing is
// reimplemented: each row calls straight into Mth.
// ============================================================================
package oracle;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.function.IntPredicate;
import net.minecraft.core.Vec3i;
import net.minecraft.util.Mth;
import net.minecraft.util.RandomSource;
import net.minecraft.world.phys.AABB;
import net.minecraft.world.phys.Vec3;
import org.apache.commons.lang3.math.Fraction;
import org.joml.Quaternionf;
import org.joml.Vector3f;

public final class MthOracle {
	// ---- shared edge-case corpus ----------------------------------------
	// negatives, +/-0.0, NaN, +/-Infinity, min/max, subnormals, integer
	// boundaries where float/double -> int conversions saturate, and the
	// values that matter for the sin LUT.
	private static final double[] D = {
		0.0, -0.0, 1.0, -1.0, 0.5, -0.5, 2.0, -2.0, 3.0, -3.0, 4.0, -4.0, 5.0, -5.0, 7.0, -7.0,
		10.0, -10.0, 16.0, -16.0, 32.0, -32.0, 45.0, -45.0, 90.0, -90.0, 180.0, -180.0,
		359.0, -359.0, 360.0, -360.0, 361.0, -361.0, 720.0, -720.0, 1080.0, -1080.0,
		0.25, -0.25, 0.1, 0.2, 0.3, -0.1, 1.0 / 3.0, -1.0 / 3.0,
		123.456, -123.456, 0.0001, -0.0001, 1000000.0, -1000000.0,
		Math.PI, -Math.PI, Math.E, -Math.E, Math.PI * 2, -(Math.PI * 2),
		Double.MIN_VALUE, -Double.MIN_VALUE, Double.MIN_NORMAL, -Double.MIN_NORMAL,
		Double.MAX_VALUE, -Double.MAX_VALUE,
		Double.NaN, Double.POSITIVE_INFINITY, Double.NEGATIVE_INFINITY,
		2147483647.0, 2147483648.0, -2147483648.0, -2147483649.0, 4294967295.0, 4294967296.0,
		9007199254740992.0, 1.0E15, 1.0E16, -1.0E16, 1.0E300, -1.0E300, 1.0E-300,
		Math.nextUp(0.0), Math.nextDown(0.0), Math.nextAfter(1.0, 2.0), Math.nextAfter(1.0, 0.0),
		Math.nextUp(180.0), Math.nextDown(-180.0),
		1.0E-5, -1.0E-5, 1.0E-7, 65535.0, 65536.0, 16384.0, 32768.0, 10430.378350470453,
		6.283185307179586, -6.283185307179586,
	};

	private static final float[] F = {
		0.0F, -0.0F, 1.0F, -1.0F, 0.5F, -0.5F, 2.0F, -2.0F, 3.0F, -3.0F, 4.0F, -4.0F, 5.0F, -5.0F,
		7.0F, -7.0F, 10.0F, -10.0F, 16.0F, -16.0F, 32.0F, -32.0F, 45.0F, -45.0F, 90.0F, -90.0F,
		180.0F, -180.0F, 359.0F, -359.0F, 360.0F, -360.0F, 0.25F, -0.25F, 0.1F, 0.2F, 0.3F, -0.1F,
		123.456F, -123.456F, 0.0001F, -0.0001F, 1.0E7F, -1.0E-7F,
		Float.MIN_VALUE, -Float.MIN_VALUE, Float.MIN_NORMAL, -Float.MIN_NORMAL,
		Float.MAX_VALUE, -Float.MAX_VALUE, Float.NaN, Float.POSITIVE_INFINITY, Float.NEGATIVE_INFINITY,
		2147483520.0F, 2147483648.0F, -2147483648.0F, -2147483904.0F, 4294967296.0F,
		Math.nextUp(0.0F), Math.nextDown(0.0F), Math.nextAfter(1.0F, 2.0F), Math.nextAfter(1.0F, 0.0F),
		(float) Math.PI, -(float) Math.PI, (float) (Math.PI * 2), 1.0E-5F, -1.0E-5F,
		65535.0F, 65536.0F, 1.0F / 3.0F, 2.0F / 3.0F,
	};

	private static final int[] I = {
		0, 1, -1, 2, -2, 3, -3, 4, -4, 5, -5, 6, -6, 7, -7, 8, -8, 9, -9, 10, -10,
		15, -15, 16, -16, 17, -17, 31, -31, 32, -32, 33, -33, 63, -63, 64, -64, 65, -65,
		100, -100, 127, -127, 128, -128, 255, -255, 256, -256, 257, -257, 359, -359, 360, -360,
		361, -361, 1000, -1000, 65535, -65535, 65536, -65536, 1000000, -1000000,
		Integer.MAX_VALUE, Integer.MIN_VALUE, Integer.MAX_VALUE - 1, Integer.MIN_VALUE + 1,
		123456789, -123456789, 1000000000, -1000000000, 2000000000, -2000000000,
		0x40000000, 0x55555555, 0x2AAAAAAA, 0x7FFFFFFF, Integer.MIN_VALUE,
	};

	private static final long[] L = {
		0L, 1L, -1L, 2L, -2L, 3L, -3L, 255L, -255L, 256L, 123456789L, -123456789L,
		Long.MAX_VALUE, Long.MIN_VALUE, Long.MAX_VALUE - 1L, Long.MIN_VALUE + 1L,
		0x0123456789ABCDEFL, 0x7FFFFFFFFFFFFFFFL, -0x7FFFFFFFFFFFFFFFL, -0x0123456789ABCDEFL,
		25214903917L, 281474976710655L, 6364136223846793005L, 1442695040888963407L,
		-7046029254386353131L, 7640891576956012809L, -4658895280553007687L, -7723592293110705685L,
		8682522807148012L, 1181783497276652981L, 4294967296L, 4294967295L, 1000000007L, -1000000007L,
	};

	static final long[] SEEDS = {
		0L, 1L, -1L, 42L, -42L, 123456789L, -123456789L, Long.MAX_VALUE, Long.MIN_VALUE,
		25214903917L, 281474976710655L, -7046029254386353131L, 7640891576956012809L,
		0x0123456789ABCDEFL, -1L, 1234567890123456789L, -1234567890123456789L,
	};

	private MthOracle() {
	}

	public static void emit(final Path path) throws Exception {
		Out o = new Out();
		o.comment("Golden data for net.minecraft.util.Mth (Minecraft 26.2, Mojang mappings).");
		o.comment("Generated by _porting/java-oracle. Do not hand-edit.");
		o.blank();

        sinTable(o);
		unaryD64(o, "sin", Mth::sin, D);
		unaryD64(o, "cos", Mth::cos, D);
		unaryF32(o, "sqrt", Mth::sqrt, F);
		unaryF32i(o, "floor", Mth::floor, F);
		unaryD32(o, "floor_d", Mth::floor, D);
		unaryD64(o, "lfloor", Mth::lfloor, D);
		unaryF32(o, "abs", Mth::abs, F);
		unaryI32(o, "abs_i", Mth::abs, I);
		unaryF32i(o, "ceil", Mth::ceil, F);
		unaryD32(o, "ceil_d", Mth::ceil, D);
		unaryD64i(o, "ceilLong", Mth::ceilLong, D);
		unaryD64(o, "positiveModulo", v -> Mth.positiveModulo(v, 7.0),
				new double[]{0.0, -0.0, 1.0, -1.0, 6.5, -6.5, 7.0, -7.0, 100.0, -100.0, Double.NaN, Double.POSITIVE_INFINITY});
		unaryF32(o, "positiveModulo_f", v -> Mth.positiveModulo(v, 7.0F),
				new float[]{0.0F, -0.0F, 1.0F, -1.0F, 6.5F, -6.5F, 7.0F, -7.0F, 100.0F, -100.0F, Float.NaN, Float.POSITIVE_INFINITY});
		unaryI32(o, "floorDiv", v -> Mth.floorDiv(v, 7), I);
		unaryI32(o, "positiveModulo_i", v -> Mth.positiveModulo(v, 7), I);
		unaryI32b(o, "isMultipleOf", v -> Mth.isMultipleOf(v, 7), I);
		unaryI32(o, "positiveCeilDiv", v -> Mth.positiveCeilDiv(v, 7), I);
		unaryI32(o, "roundToward_i", v -> Mth.roundToward(v, 16), I);
		unaryL64(o, "roundToward_l", v -> Mth.roundToward(v, 16L), L);
		unaryI32(o, "smallestEncompassingPowerOfTwo", Mth::smallestEncompassingPowerOfTwo,
				new int[]{0, 1, 2, 3, 4, 5, 7, 8, 9, 15, 16, 17, 1000, 65535, 65536, 1000000, Integer.MAX_VALUE, -1, Integer.MIN_VALUE});
		unaryI32(o, "smallestSquareSide", Mth::smallestSquareSide,
				new int[]{0, 1, 2, 3, 4, 8, 9, 15, 16, 100, 10000, 1000000});
		unaryI32b(o, "isPowerOfTwo_i", Mth::isPowerOfTwo, I);
		unaryL64b(o, "isPowerOfTwo_l", Mth::isPowerOfTwo, L);
		unaryI32(o, "ceillog2", Mth::ceillog2, POWERS);
		unaryI32(o, "log2", Mth::log2, POWERS);
		unaryF32(o, "frac_f", Mth::frac, F);
		unaryD64(o, "frac_d", Mth::frac, D);
		unaryD32(o, "sign", Mth::sign, D);
		unaryF32i(o, "packDegrees", v -> (int) Mth.packDegrees(v), F);
		unaryI32f(o, "unpackDegrees", v -> Mth.unpackDegrees((byte) v),
				new int[]{-128, -127, -100, -1, 0, 1, 45, 100, 126, 127});
		unaryI32(o, "wrapDegrees_i", Mth::wrapDegrees, I);
		unaryL64f(o, "wrapDegrees_l", v -> Mth.wrapDegrees(v), L);
		unaryF32(o, "wrapDegrees_f", Mth::wrapDegrees, F);
		unaryD64(o, "wrapDegrees_d", Mth::wrapDegrees, D);
		unaryF32(o, "wrapDegrees90", Mth::wrapDegrees90, F);
		unaryD64(o, "atan2", v -> Mth.atan2(v, v * 0.5), D);
		unaryD64(o, "fastInvSqrt", Mth::fastInvSqrt,
				new double[]{0.0, -0.0, 1.0, 2.0, 4.0, 0.5, 1e30, 1e-30, 1e300, Double.MIN_VALUE, Double.MAX_VALUE,
						Double.NaN, Double.POSITIVE_INFINITY, Double.NEGATIVE_INFINITY, 3.0, 1.0 / 3.0, 1e-300});
		unaryF32(o, "invSqrt_f", Mth::invSqrt,
				new float[]{0.0F, -0.0F, 1.0F, 2.0F, 4.0F, 0.5F, 1e30F, 1e-30F, Float.MAX_VALUE, Float.MIN_VALUE,
						Float.NaN, Float.POSITIVE_INFINITY, Float.NEGATIVE_INFINITY, 3.0F, 0.1F});
		unaryD64(o, "invSqrt_d", Mth::invSqrt,
				new double[]{0.0, -0.0, 1.0, 2.0, 4.0, 0.5, 1e30, 1e-30, Double.MAX_VALUE, Double.MIN_VALUE,
						Double.NaN, Double.POSITIVE_INFINITY, Double.NEGATIVE_INFINITY, 3.0, 0.1});
		unaryF32(o, "fastInvCubeRoot", Mth::fastInvCubeRoot,
				new float[]{0.0F, -0.0F, 1.0F, -1.0F, 8.0F, -8.0F, 27.0F, 0.125F, 1e10F, -1e10F,
						Float.MAX_VALUE, Float.MIN_VALUE, Float.NaN, Float.POSITIVE_INFINITY, Float.NEGATIVE_INFINITY,
						3.0F, -3.0F, 1.0e-30F, 1.0e30F});
		unaryF32(o, "square_f", Mth::square, F);
		unaryD64(o, "square_d", Mth::square, D);
		unaryI32(o, "square_i", Mth::square, I);
		unaryL64(o, "square_l", Mth::square, L);
		unaryF32(o, "cube", Mth::cube, F);
		unaryF32(o, "triangleWave", v -> Mth.triangleWave(v, 4.0F), F);
		unaryD64(o, "smoothstep", Mth::smoothstep, new double[]{-1.0, -0.5, 0.0, 0.25, 0.5, 0.75, 1.0, 2.0, Double.NaN});
		unaryD64(o, "smoothstepDerivative", Mth::smoothstepDerivative, new double[]{-1.0, -0.5, 0.0, 0.25, 0.5, 0.75, 1.0, 2.0, Double.NaN});
		unaryI32(o, "murmurHash3Mixer", Mth::murmurHash3Mixer, I);

		// `Mth#wobble` is DELIBERATELY NOT EMITTED.
		//
		// public static double wobble(double coord) {
		//     return coord + (2.0 * RandomSource.createThreadLocalInstance(floor(coord * 3000.0)).nextDouble() - 1.0) * 1.0E-7 / 2.0;
		// }
		//
		// `createThreadLocalInstance(long)` with no seed draws from netty's
		// ThreadLocalRandom, i.e. per-thread state seeded off the system clock. The
		// result is therefore different on every call and cannot be asserted against a
		// golden value -- emitting it produced rows that changed on every oracle run,
		// which is worse than useless because it makes the whole file look unstable.
		//
		// What IS deterministic, and what random.txt tests as `wobble_check`, is the
		// seeded path: `RandomSource.createThreadLocalInstance(seed)` followed by a draw
		// from it. That covers the arithmetic wobble performs on the drawn value, which
		// is the part worth pinning.
		//
		// See OPEN_QUESTIONS.md #1 -- this is also why `generateUniqueSeed` is untested.

		strings(o);
		pairs(o);
		triples(o);
		randomBacked(o);
		geometry(o);

		o.write(path);
	}

	private static final int[] POWERS = {
		1, 2, 3, 4, 5, 7, 8, 9, 15, 16, 17, 31, 32, 33, 63, 64, 65, 100, 127, 128, 255, 256,
		1000, 65535, 65536, 1000000, 1 << 20, 1 << 24, 1 << 30, Integer.MAX_VALUE,
	};

	// ---------------------------------------------------------------- helpers
	// One emit helper per (arg type, return type) combination so that a mismatch
	// is a compile error rather than a silently mislabelled golden file.
	private interface DF {
		double apply(double v);
	}

	private interface DFi {
		int apply(double v);
	}

	private interface DFl {
		long apply(double v);
	}

	private interface FF {
		float apply(float v);
	}

	private interface FFi {
		int apply(float v);
	}

	private interface II {
		int apply(int v);
	}

	private interface IIb {
		boolean apply(int v);
	}

	private interface IF {
		float apply(int v);
	}

	private interface LL {
		long apply(long v);
	}

	private interface LLb {
		boolean apply(long v);
	}

	private interface LF {
		float apply(long v);
	}

	private static void unaryD64(final Out o, final String name, final DF f, final double[] vs) {
		o.fn(name, "f64", "f64");
		for (double v : vs) {
			o.row(Out.f64(v), Out.f64(f.apply(v)));
		}

		o.blank();
	}

	private static void unaryD32(final Out o, final String name, final DFi f, final double[] vs) {
		o.fn(name, "f64", "i32");
		for (double v : vs) {
			o.row(Out.f64(v), Out.i32(f.apply(v)));
		}

		o.blank();
	}

	private static void unaryD64i(final Out o, final String name, final DFl f, final double[] vs) {
		o.fn(name, "f64", "i64");
		for (double v : vs) {
			o.row(Out.f64(v), Out.i64(f.apply(v)));
		}

		o.blank();
	}

	private static void unaryF32(final Out o, final String name, final FF f, final float[] vs) {
		o.fn(name, "f32", "f32");
		for (float v : vs) {
			o.row(Out.f32(v), Out.f32(f.apply(v)));
		}

		o.blank();
	}

	private static void unaryF32i(final Out o, final String name, final FFi f, final float[] vs) {
		o.fn(name, "f32", "i32");
		for (float v : vs) {
			o.row(Out.f32(v), Out.i32(f.apply(v)));
		}

		o.blank();
	}

	private static void unaryI32(final Out o, final String name, final II f, final int[] vs) {
		o.fn(name, "i32", "i32");
		for (int v : vs) {
			o.row(Out.i32(v), Out.i32(f.apply(v)));
		}

		o.blank();
	}

	private static void unaryI32b(final Out o, final String name, final IIb f, final int[] vs) {
		o.fn(name, "i32", "bool");
		for (int v : vs) {
			o.row(Out.i32(v), Out.b(f.apply(v)));
		}

		o.blank();
	}

	private static void unaryI32f(final Out o, final String name, final IF f, final int[] vs) {
		o.fn(name, "i32", "f32");
		for (int v : vs) {
			o.row(Out.i32(v), Out.f32(f.apply(v)));
		}

		o.blank();
	}

	private static void unaryL64(final Out o, final String name, final LL f, final long[] vs) {
		o.fn(name, "i64", "i64");
		for (long v : vs) {
			o.row(Out.i64(v), Out.i64(f.apply(v)));
		}

		o.blank();
	}

	private static void unaryL64b(final Out o, final String name, final LLb f, final long[] vs) {
		o.fn(name, "i64", "bool");
		for (long v : vs) {
			o.row(Out.i64(v), Out.b(f.apply(v)));
		}

		o.blank();
	}

	private static void unaryL64f(final Out o, final String name, final LF f, final long[] vs) {
		o.fn(name, "i64", "f32");
		for (long v : vs) {
			o.row(Out.i64(v), Out.f32(f.apply(v)));
		}

		o.blank();
	}

	// ---- String / predicate / Fraction taking methods ---------------------
	private static void strings(final Out o) {
		o.fn("getInt", "str i32", "i32");
		for (String s : new String[]{"0", "1", "-1", "42", "2147483647", "-2147483648", "2147483648",
				"", " ", "+7", "007", "1.0", "abc", "0x10", "99999999999999999999"}) {
			o.row(Out.join(Out.str(s), Out.i32(5)), Out.i32(Mth.getInt(s, 5)));
		}
		o.blank();

		o.fn("mulAndTruncate", "f64 i32", "i32");
		for (double d : new double[]{0.0, 0.5, -0.5, 1.0, -1.0, 0.25, 0.75, 1.0 / 3.0, 2.0 / 3.0, -2.0 / 3.0, 10.0, -10.0, 100.0}) {
			for (int f : new int[]{1, -1, 2, 3, 7, 100, -100}) {
				o.row(Out.join(Out.f64(d), Out.i32(f)), Out.i32(Mth.mulAndTruncate(Fraction.getFraction(d), f)));
			}
		}
		o.blank();

		o.fn("binarySearch", "i32 i32", "i32");
		for (int[] range : new int[][]{{0, 0}, {0, 1}, {0, 8}, {-8, 8}, {-100, 100}, {5, 5}, {0, 2147483647}}) {
			IntPredicate cond = i -> i % 3 == 0;
			o.row(Out.join(Out.i32(range[0]), Out.i32(range[1])), Out.i32(Mth.binarySearch(range[0], range[1], cond)));
		}
		o.blank();
	}

	// ---- binary numeric ---------------------------------------------------
	private static void pairs(final Out o) {
		o.fn("clamp_i", "i32 i32 i32", "i32");
		for (int v : I) {
			o.row(Out.join(Out.i32(v), Out.i32(-100), Out.i32(100)), Out.i32(Mth.clamp(v, -100, 100)));
		}
		o.blank();

		o.fn("clamp_l", "i64 i64 i64", "i64");
		for (long v : L) {
			o.row(Out.join(Out.i64(v), Out.i64(-100L), Out.i64(100L)), Out.i64(Mth.clamp(v, -100L, 100L)));
		}
		o.blank();

		o.fn("clamp_f", "f32 f32 f32", "f32");
		for (float v : F) {
			for (float lo : new float[]{-1.0F, 0.0F, 1.0F, Float.NEGATIVE_INFINITY}) {
				o.row(Out.join(Out.f32(v), Out.f32(lo), Out.f32(100.0F)), Out.f32(Mth.clamp(v, lo, 100.0F)));
			}
		}
		o.blank();

		o.fn("clamp_d", "f64 f64 f64", "f64");
		for (double v : D) {
			o.row(Out.join(Out.f64(v), Out.f64(-1.0), Out.f64(100.0)), Out.f64(Mth.clamp(v, -1.0, 100.0)));
		}
		o.blank();

		o.fn("clampedLerp_f", "f32 f32 f32", "f32");
		for (float f : F) {
			o.row(Out.join(Out.f32(f), Out.f32(0.0F), Out.f32(1.0F)), Out.f32(Mth.clampedLerp(f, 0.0F, 1.0F)));
		}
		o.blank();

		o.fn("clampedLerp_d", "f64 f64 f64", "f64");
		for (double f : D) {
			o.row(Out.join(Out.f64(f), Out.f64(0.0), Out.f64(1.0)), Out.f64(Mth.clampedLerp(f, 0.0, 1.0)));
		}
		o.blank();

		o.fn("absMax_i", "i32 i32", "i32");
		for (int a : I) {
			o.row(Out.join(Out.i32(a), Out.i32(-a)), Out.i32(Mth.absMax(a, -a)));
		}
		o.blank();

		o.fn("absMax_f", "f32 f32", "f32");
		for (float a : F) {
			o.row(Out.join(Out.f32(a), Out.f32(-a)), Out.f32(Mth.absMax(a, -a)));
		}
		o.blank();

		o.fn("absMax_d", "f64 f64", "f64");
		for (double a : D) {
			o.row(Out.join(Out.f64(a), Out.f64(-a)), Out.f64(Mth.absMax(a, -a)));
		}
		o.blank();

		o.fn("chessboardDistance", "i32 i32 i32 i32", "i32");
		for (int a : I) {
			o.row(Out.join(Out.i32(a), Out.i32(-a), Out.i32(a), Out.i32(-a)), Out.i32(Mth.chessboardDistance(a, -a, a, -a)));
		}
		o.blank();

		o.fn("equal_f", "f32 f32", "bool");
		for (float a : F) {
			o.row(Out.join(Out.f32(a), Out.f32(0.0F)), Out.b(Mth.equal(a, 0.0F)));
		}
		o.blank();

		o.fn("equal_d", "f64 f64", "bool");
		for (double a : D) {
			o.row(Out.join(Out.f64(a), Out.f64(0.0)), Out.b(Mth.equal(a, 0.0)));
		}
		o.blank();

		o.fn("degreesDifference", "f32 f32", "f32");
		for (float a : F) {
			o.row(Out.join(Out.f32(a), Out.f32(180.0F)), Out.f32(Mth.degreesDifference(a, 180.0F)));
		}
		o.blank();

		o.fn("degreesDifferenceAbs", "f32 f32", "f32");
		for (float a : F) {
			o.row(Out.join(Out.f32(a), Out.f32(90.0F)), Out.f32(Mth.degreesDifferenceAbs(a, 90.0F)));
		}
		o.blank();

		o.fn("rotateIfNecessary", "f32 f32 f32", "f32");
		for (float a : F) {
			o.row(Out.join(Out.f32(a), Out.f32(90.0F), Out.f32(45.0F)), Out.f32(Mth.rotateIfNecessary(a, 90.0F, 45.0F)));
		}
		o.blank();

		o.fn("approach", "f32 f32 f32", "f32");
		for (float a : F) {
			o.row(Out.join(Out.f32(a), Out.f32(1.0F), Out.f32(0.25F)), Out.f32(Mth.approach(a, 1.0F, 0.25F)));
		}
		o.blank();

		o.fn("approachDegrees", "f32 f32 f32", "f32");
		for (float a : F) {
			o.row(Out.join(Out.f32(a), Out.f32(180.0F), Out.f32(15.0F)), Out.f32(Mth.approachDegrees(a, 180.0F, 15.0F)));
		}
		o.blank();

		o.fn("inverseLerp_f", "f32 f32 f32", "f32");
		for (float a : F) {
			o.row(Out.join(Out.f32(a), Out.f32(0.0F), Out.f32(2.0F)), Out.f32(Mth.inverseLerp(a, 0.0F, 2.0F)));
		}
		o.blank();

		o.fn("inverseLerp_d", "f64 f64 f64", "f64");
		for (double a : D) {
			o.row(Out.join(Out.f64(a), Out.f64(0.0), Out.f64(2.0)), Out.f64(Mth.inverseLerp(a, 0.0, 2.0)));
		}
		o.blank();

		o.fn("lerpInt", "f32 i32 i32", "i32");
		for (float a : F) {
			o.row(Out.join(Out.f32(a), Out.i32(0), Out.i32(10)), Out.i32(Mth.lerpInt(a, 0, 10)));
		}
		o.blank();

		o.fn("lerpDiscrete", "f32 i32 i32", "i32");
		for (float a : F) {
			o.row(Out.join(Out.f32(a), Out.i32(0), Out.i32(10)), Out.i32(Mth.lerpDiscrete(a, 0, 10)));
		}
		o.blank();

		o.fn("lerp_f", "f32 f32 f32", "f32");
		for (float a : F) {
			o.row(Out.join(Out.f32(a), Out.f32(0.5F), Out.f32(2.5F)), Out.f32(Mth.lerp(a, 0.5F, 2.5F)));
		}
		o.blank();

		o.fn("lerp_d", "f64 f64 f64", "f64");
		for (double a : D) {
			o.row(Out.join(Out.f64(a), Out.f64(0.5), Out.f64(2.5)), Out.f64(Mth.lerp(a, 0.5, 2.5)));
		}
		o.blank();

		o.fn("catmullrom", "f32 f32 f32 f32 f32", "f32");
		for (float a : F) {
			o.row(Out.join(Out.f32(a), Out.f32(1.0F), Out.f32(2.0F), Out.f32(3.0F), Out.f32(4.0F)),
					Out.f32(Mth.catmullrom(a, 1.0F, 2.0F, 3.0F, 4.0F)));
		}
		o.blank();

		o.fn("rotLerp_f", "f32 f32 f32", "f32");
		for (float a : F) {
			o.row(Out.join(Out.f32(a), Out.f32(350.0F), Out.f32(10.0F)), Out.f32(Mth.rotLerp(a, 350.0F, 10.0F)));
		}
		o.blank();

		o.fn("rotLerp_d", "f64 f64 f64", "f64");
		for (double a : D) {
			o.row(Out.join(Out.f64(a), Out.f64(350.0), Out.f64(10.0)), Out.f64(Mth.rotLerp(a, 350.0, 10.0)));
		}
		o.blank();

		o.fn("rotLerpRad", "f32 f32 f32", "f32");
		for (float a : F) {
			o.row(Out.join(Out.f32(a), Out.f32(6.0F), Out.f32(-6.0F)), Out.f32(Mth.rotLerpRad(a, 6.0F, -6.0F)));
		}
		o.blank();

		o.fn("clampedMap_f", "f32 f32 f32 f32 f32", "f32");
		for (float a : F) {
			o.row(Out.join(Out.f32(a), Out.f32(0.0F), Out.f32(2.0F), Out.f32(10.0F), Out.f32(20.0F)),
					Out.f32(Mth.clampedMap(a, 0.0F, 2.0F, 10.0F, 20.0F)));
		}
		o.blank();

		o.fn("clampedMap_d", "f64 f64 f64 f64 f64", "f64");
		for (double a : D) {
			o.row(Out.join(Out.f64(a), Out.f64(0.0), Out.f64(2.0), Out.f64(10.0), Out.f64(20.0)),
					Out.f64(Mth.clampedMap(a, 0.0, 2.0, 10.0, 20.0)));
		}
		o.blank();

		o.fn("map_f", "f32 f32 f32 f32 f32", "f32");
		for (float a : F) {
			o.row(Out.join(Out.f32(a), Out.f32(0.0F), Out.f32(2.0F), Out.f32(10.0F), Out.f32(20.0F)),
					Out.f32(Mth.map(a, 0.0F, 2.0F, 10.0F, 20.0F)));
		}
		o.blank();

		o.fn("map_d", "f64 f64 f64 f64 f64", "f64");
		for (double a : D) {
			o.row(Out.join(Out.f64(a), Out.f64(0.0), Out.f64(2.0), Out.f64(10.0), Out.f64(20.0)),
					Out.f64(Mth.map(a, 0.0, 2.0, 10.0, 20.0)));
		}
		o.blank();

		o.fn("lengthSquared2", "f64 f64", "f64");
		for (double a : D) {
			o.row(Out.join(Out.f64(a), Out.f64(-a)), Out.f64(Mth.lengthSquared(a, -a)));
		}
		o.blank();

		o.fn("length2", "f64 f64", "f64");
		for (double a : D) {
			o.row(Out.join(Out.f64(a), Out.f64(-a)), Out.f64(Mth.length(a, -a)));
		}
		o.blank();

		o.fn("lengthF2", "f32 f32", "f32");
		for (float a : F) {
			o.row(Out.join(Out.f32(a), Out.f32(-a)), Out.f32(Mth.length(a, -a)));
		}
		o.blank();

		o.fn("lengthSquared3", "f64 f64 f64", "f64");
		for (double a : D) {
			o.row(Out.join(Out.f64(a), Out.f64(-a), Out.f64(a * 0.5)), Out.f64(Mth.lengthSquared(a, -a, a * 0.5)));
		}
		o.blank();

		o.fn("length3", "f64 f64 f64", "f64");
		for (double a : D) {
			o.row(Out.join(Out.f64(a), Out.f64(-a), Out.f64(a * 0.5)), Out.f64(Mth.length(a, -a, a * 0.5)));
		}
		o.blank();

		o.fn("lengthSquaredF3", "f32 f32 f32", "f32");
		for (float a : F) {
			o.row(Out.join(Out.f32(a), Out.f32(-a), Out.f32(a * 0.5F)), Out.f32(Mth.lengthSquared(a, -a, a * 0.5F)));
		}
		o.blank();

		o.fn("quantize", "f64 i32", "i32");
		for (double a : D) {
			o.row(Out.join(Out.f64(a), Out.i32(16)), Out.i32(Mth.quantize(a, 16)));
		}
		o.blank();

		o.fn("lerp2", "f64 f64 f64 f64 f64 f64", "f64");
		for (double a : D) {
			o.row(Out.join(Out.f64(a), Out.f64(-a), Out.f64(1.0), Out.f64(2.0), Out.f64(3.0), Out.f64(4.0)),
					Out.f64(Mth.lerp2(a, -a, 1.0, 2.0, 3.0, 4.0)));
		}
		o.blank();
	}

	private static void triples(final Out o) {
		o.fn("nextInt_rand", "i64 i32 i32", "i32");
		for (long seed : SEEDS) {
			for (int[] range : new int[][]{{0, 0}, {0, 1}, {0, 6}, {-3, 3}, {-6, -1}, {5, 5}, {-1000000, 1000000}}) {
				RandomSource r = RandomSource.create(seed);
				for (int k = 0; k < 4; k++) {
					o.row(Out.join(Out.i64(seed), Out.i32(range[0]), Out.i32(range[1])),
							Out.i32(Mth.nextInt(r, range[0], range[1])));
				}
			}
		}
		o.blank();

		o.fn("randomBetweenInclusive", "i64 i32 i32", "i32");
		for (long seed : SEEDS) {
			RandomSource r = RandomSource.create(seed);
			for (int k = 0; k < 8; k++) {
				o.row(Out.join(Out.i64(seed), Out.i32(-10), Out.i32(10)), Out.i32(Mth.randomBetweenInclusive(r, -10, 10)));
			}
		}
		o.blank();

		o.fn("nextFloat_rand", "i64 f32 f32", "f32");
		for (long seed : SEEDS) {
			RandomSource r = RandomSource.create(seed);
			for (int k = 0; k < 8; k++) {
				o.row(Out.join(Out.i64(seed), Out.f32(-1.0F), Out.f32(1.0F)), Out.f32(Mth.nextFloat(r, -1.0F, 1.0F)));
			}
		}
		o.blank();

		o.fn("randomBetween", "i64 f32 f32", "f32");
		for (long seed : SEEDS) {
			RandomSource r = RandomSource.create(seed);
			for (int k = 0; k < 8; k++) {
				o.row(Out.join(Out.i64(seed), Out.f32(-1.0F), Out.f32(1.0F)), Out.f32(Mth.randomBetween(r, -1.0F, 1.0F)));
			}
		}
		o.blank();

		o.fn("nextDouble_rand", "i64 f64 f64", "f64");
		for (long seed : SEEDS) {
			RandomSource r = RandomSource.create(seed);
			for (int k = 0; k < 8; k++) {
				o.row(Out.join(Out.i64(seed), Out.f64(-1.0), Out.f64(1.0)), Out.f64(Mth.nextDouble(r, -1.0, 1.0)));
			}
		}
		o.blank();

		o.fn("normal", "i64 f32 f32", "f32");
		for (long seed : SEEDS) {
			RandomSource r = RandomSource.create(seed);
			for (int k = 0; k < 8; k++) {
				o.row(Out.join(Out.i64(seed), Out.f32(10.0F), Out.f32(2.0F)), Out.f32(Mth.normal(r, 10.0F, 2.0F)));
			}
		}
		o.blank();

		o.fn("createInsecureUUID", "i64", "i64 i64");
		for (long seed : SEEDS) {
			RandomSource r = RandomSource.create(seed);
			UUID u = Mth.createInsecureUUID(r);
			o.row(Out.i64(seed), Out.join(Out.i64(u.getMostSignificantBits()), Out.i64(u.getLeastSignificantBits())));
		}
		o.blank();

		int[] coords = {0, 1, -1, 1000, -1000, 1000000, -1000000, Integer.MAX_VALUE, Integer.MIN_VALUE, 123456789};
		o.fn("getSeed3", "i32 i32 i32", "i64");
		for (int a : coords) {
			o.row(Out.join(Out.i32(a), Out.i32(-a), Out.i32(a * 31)), Out.i64(Mth.getSeed(a, -a, a * 31)));
		}
		o.blank();

		o.fn("getSeedVec3i", "i32 i32 i32", "i64");
		for (int a : coords) {
			o.row(Out.join(Out.i32(a), Out.i32(-a), Out.i32(a * 31)),
					Out.i64(Mth.getSeed(new Vec3i(a, -a, a * 31))));
		}
		o.blank();

		o.fn("lerpVec3", "f64 f64 f64 f64 f64 f64 f64", "f64 f64 f64");
		for (double a : D) {
			Vec3 p1 = new Vec3(a, -a, a * 0.5);
			Vec3 p2 = new Vec3(-a, a, a * 0.25);
			Vec3 r = Mth.lerp(a, p1, p2);
			o.row(Out.join(Out.f64(a), Out.f64(p1.x), Out.f64(p1.y), Out.f64(p1.z), Out.f64(p2.x), Out.f64(p2.y), Out.f64(p2.z)),
					Out.join(Out.f64(r.x), Out.f64(r.y), Out.f64(r.z)));
		}
		o.blank();

		o.fn("outFromOrigin", "i32 i32 i32", "s");
		for (int[] c : new int[][]{{0, 0, 0}, {5, 0, 10}, {0, -10, 10}, {100, -100, 100}, {-100, -100, -50}, {7, 3, 3}, {0, 0, 1000}}) {
			o.row(Out.join(Out.i32(c[0]), Out.i32(c[1]), Out.i32(c[2])),
					Out.ints(Mth.outFromOrigin(c[0], c[1], c[2]).toArray()));
		}
		o.blank();

		o.fn("lerp3", "f64 f64 f64 f64 f64 f64 f64 f64 f64 f64 f64", "f64");
		for (double a : D) {
			o.row(Out.join(Out.f64(a), Out.f64(-a), Out.f64(a * 0.5), Out.f64(1.0), Out.f64(2.0), Out.f64(3.0),
							Out.f64(4.0), Out.f64(5.0), Out.f64(6.0), Out.f64(7.0), Out.f64(8.0)),
					Out.f64(Mth.lerp3(a, -a, a * 0.5, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0)));
		}
		o.blank();
	}

	private static void randomBacked(final Out o) {
		o.fn("nextIntBound_rand", "i64 i32", "i32");
		for (long seed : SEEDS) {
			for (int bound : new int[]{1, 2, 3, 5, 7, 8, 16, 17, 100, 1000, 65536, 2147483647}) {
				RandomSource r = RandomSource.create(seed);
				o.row(Out.join(Out.i64(seed), Out.i32(bound)), Out.i32(r.nextInt(bound)));
			}
		}
		o.blank();

		o.fn("nextIntOriginBound", "i64 i32 i32", "i32");
		for (long seed : SEEDS) {
			RandomSource r = RandomSource.create(seed);
			for (int k = 0; k < 4; k++) {
				o.row(Out.join(Out.i64(seed), Out.i32(-5), Out.i32(5)), Out.i32(r.nextInt(-5, 5)));
			}
		}
		o.blank();
	}

	private static void geometry(final Out o) {
		o.fn("rayIntersectsAABB", "f64 f64 f64 f64 f64 f64 f64 f64 f64 f64 f64 f64 f64 f64 f64", "bool");
		double[][] boxes = {
			{-1.0, -1.0, -1.0, 1.0, 1.0, 1.0},
			{0.0, 0.0, 0.0, 1.0, 1.0, 1.0},
			{-0.5, -0.5, -0.5, -0.5, -0.5, -0.5},
			{0.0, 0.0, 0.0, 0.0, 0.0, 0.0},
			{-1e10, -1e10, -1e10, 1e10, 1e10, 1e10},
		};
		double[][] starts = {
			{0.0, 0.0, 0.0}, {-5.0, -5.0, -5.0}, {2.0, 2.0, 2.0}, {0.0, -5.0, 0.0}, {-5.0, 0.0, -5.0},
		};
		double[][] dirs = {
			{0.0, 0.0, 1.0}, {1.0, 0.0, 0.0}, {0.0, 1.0, 0.0}, {1.0, 1.0, 1.0}, {-1.0, -1.0, -1.0},
			{0.5, 0.0, 0.0}, {0.0, -0.5, 0.0}, {1.0, 0.0, -1.0},
		};
		for (double[] box : boxes) {
			AABB aabb = new AABB(box[0], box[1], box[2], box[3], box[4], box[5]);
			for (double[] s : starts) {
				for (double[] d : dirs) {
					o.row(Out.join(Out.f64(s[0]), Out.f64(s[1]), Out.f64(s[2]),
									Out.f64(d[0]), Out.f64(d[1]), Out.f64(d[2]),
									Out.f64(box[0]), Out.f64(box[1]), Out.f64(box[2]),
									Out.f64(box[3]), Out.f64(box[4]), Out.f64(box[5])),
							Out.b(Mth.rayIntersectsAABB(new Vec3(s[0], s[1], s[2]), new Vec3(d[0], d[1], d[2]), aabb)));
				}
			}
		}
		o.blank();

		o.fn("rotationAroundAxis", "f32 f32 f32 f32 f32 f32 f32 f32", "f32 f32 f32 f32");
		float[][] axes = {{1, 0, 0}, {0, 1, 0}, {0, 0, 1}, {1, 1, 1}, {-1, 0.5F, 2}};
		float[][] rots = {{0, 0, 0, 1}, {0.5F, 0.5F, 0.5F, 0.5F}, {0, 0.70710677F, 0, 0.70710677F},
				{-0.57735026F, 0.57735026F, -0.57735026F, 0}};
		for (float[] ax : axes) {
			for (float[] rr : rots) {
				Vector3f axis = new Vector3f(ax[0], ax[1], ax[2]);
				Quaternionf rot = new Quaternionf(rr[0], rr[1], rr[2], rr[3]);
				Quaternionf res = Mth.rotationAroundAxis(axis, rot, new Quaternionf());
				o.row(Out.join(Out.f32(ax[0]), Out.f32(ax[1]), Out.f32(ax[2]),
								Out.f32(rr[0]), Out.f32(rr[1]), Out.f32(rr[2]), Out.f32(rr[3])),
						Out.join(Out.f32(res.x()), Out.f32(res.y()), Out.f32(res.z()), Out.f32(res.w())));
			}
		}
		o.blank();
	}

	// ---- the 65536-entry sin lookup table ---------------------------------
	// The table is the single most load-bearing constant in Mth: every sin()/cos()
	// call in the game indexes it. Rather than ship 65536 golden rows we emit
	//   * an FNV-1a 64 hash over the raw bits of the WHOLE table, and
	//   * a deterministic sample (first 512, last 512, every 137th).
	// Matching the hash means all 65536 entries are bit-identical.
	private static void sinTable(final Out o) {
		final float[] table = new float[65536];
		for (int i = 0; i < table.length; i++) {
			table[i] = (float) Math.sin(i / 10430.378350470453);
		}

		long h = 0xCBF29CE484222325L;
		for (int i = 0; i < table.length; i++) {
			int bits = Float.floatToRawIntBits(table[i]);
			for (int b = 0; b < 4; b++) {
				h ^= (bits >>> (8 * b)) & 0xFFL;
				h *= 0x100000001B3L;
			}
		}

		o.fn("sinTableHash", "", "i64");
		o.row("", Out.i64(h));
		o.blank();

		List<Integer> idx = new ArrayList<>();
		for (int i = 0; i < 512; i++) {
			idx.add(i);
		}

		for (int i = 65536 - 512; i < 65536; i++) {
			idx.add(i);
		}

		for (int i = 0; i < 65536; i += 137) {
			idx.add(i);
		}

		o.fn("sinTable", "i32", "f32");
		for (int i : idx) {
			o.row(Out.i32(i), Out.f32(table[i]));
		}

		o.blank();
	}

	/**
	 * Dumps the FULL sin / asin / cos lookup tables so the Rust side can embed them
	 * verbatim instead of calling the host libm.
	 *
	 * Why embed: Java's Math.sin is permitted a 1-ulp error and the exact value
	 * depends on JVM internals (fdlibm vs. x86 intrinsic). Rust's f64::sin links
	 * the platform libm. Across 65536 entries a 1-ulp double difference can still
	 * flip the rounded f32 result for a handful of indices -- and one flipped
	 * entry changes every sin()/cos() call that lands on it, i.e. block rotation,
	 * entity yaw, camera angles. Embedding removes the host-libm dependency and
	 * makes the table identical on every platform and CPU.
	 * See _porting/DESIGN_DECISIONS.md (#embedded-trig-tables).
	 *
	 * This file is an INPUT for _porting/tools/gen_tables.py, not for the tests.
	 */
	public static void emitTables(final Path path) throws Exception {
		Out o = new Out();
		o.comment("Full lookup tables from net.minecraft.util.Mth (Minecraft 26.2).");
		o.comment("INPUT for _porting/tools/gen_tables.py -- NOT read by the parity tests.");
		o.blank();

		o.fn("SIN", "i32", "f32");
		for (int i = 0; i < 65536; i++) {
			o.row(Out.i32(i), Out.f32((float) Math.sin(i / 10430.378350470453)));
		}
		o.blank();

		double[] asin = new double[257];
		double[] cos = new double[257];
		for (int ind = 0; ind < 257; ind++) {
			double v = ind / 256.0;
			double asinv = Math.asin(v);
			cos[ind] = Math.cos(asinv);
			asin[ind] = asinv;
		}

		o.fn("ASIN_TAB", "i32", "f64");
		for (int i = 0; i < 257; i++) {
			o.row(Out.i32(i), Out.f64(asin[i]));
		}
		o.blank();

		o.fn("COS_TAB", "i32", "f64");
		for (int i = 0; i < 257; i++) {
			o.row(Out.i32(i), Out.f64(cos[i]));
		}
		o.blank();

		o.write(path);
	}
}