// ============================================================================
// ORACLE -- not game code. Runs the ORIGINAL random sources from
// minecraft-decompiled/, unchanged.
//
// For stateful sources the golden rows are a TRANSCRIPT: the Rust test walks
// the rows in file order and performs the same calls in the same order on a
// freshly constructed object. The first argument is the construction seed.
// ============================================================================
package oracle;

import java.nio.file.Path;
import net.minecraft.util.Mth;
import net.minecraft.util.RandomSource;
import net.minecraft.world.level.levelgen.BitRandomSource;
import net.minecraft.world.level.levelgen.LegacyRandomSource;
import net.minecraft.world.level.levelgen.PositionalRandomFactory;
import net.minecraft.world.level.levelgen.RandomSupport;
import net.minecraft.world.level.levelgen.SingleThreadedRandomSource;
import net.minecraft.world.level.levelgen.ThreadSafeLegacyRandomSource;
import net.minecraft.world.level.levelgen.WorldgenRandom;
import net.minecraft.world.level.levelgen.Xoroshiro128PlusPlus;
import net.minecraft.world.level.levelgen.XoroshiroRandomSource;

public final class RandomOracle {
	private static final long[] SEEDS = {
		0L, 1L, -1L, 42L, -42L, 123456789L, -123456789L, Long.MAX_VALUE, Long.MIN_VALUE,
		25214903917L, 281474976710655L, -7046029254386353131L, 7640891576956012809L,
		0x0123456789ABCDEFL, -1L, 1234567890123456789L, -1234567890123456789L,
		281474976710656L, 281474976710654L, 0x8000000000000000L,
	};

	private static final int[] BOUNDS = {
		1, 2, 3, 4, 5, 7, 8, 9, 16, 17, 31, 32, 33, 63, 64, 65, 100, 127, 128, 255, 256, 1000,
		65535, 65536, 1000000, 2147483647, 2147483646, 1073741824,
	};

	private RandomOracle() {
	}

	public static void emit(final Path path) throws Exception {
		Out o = new Out();
		o.comment("Golden data for the Minecraft 26.2 random sources.");
		o.comment("Generated by _porting/java-oracle. Do not hand-edit.");
		o.blank();

		legacy(o);
		xoroshiro(o);
		singleThreaded(o);
		threadSafe(o);
		worldgen(o);
		support(o);
		positional(o);
		lcg(o);
		bitRandom(o);

		o.write(path);
	}

	/** Transcripts for one implementation of BitRandomSource. */
	private static void transcript(final Out o, final String tag, final java.util.function.LongFunction<RandomSource> ctor,
			final boolean rawBits) {
		o.fn(tag + ".nextInt", "i64", "i32");
		for (long seed : SEEDS) {
			RandomSource r = ctor.apply(seed);
			for (int k = 0; k < 24; k++) {
				o.row(Out.i64(seed), Out.i32(r.nextInt()));
			}
		}
		o.blank();

		o.fn(tag + ".nextLong", "i64", "i64");
		for (long seed : SEEDS) {
			RandomSource r = ctor.apply(seed);
			for (int k = 0; k < 24; k++) {
				o.row(Out.i64(seed), Out.i64(r.nextLong()));
			}
		}
		o.blank();

		o.fn(tag + ".nextBoolean", "i64", "bool");
		for (long seed : SEEDS) {
			RandomSource r = ctor.apply(seed);
			for (int k = 0; k < 24; k++) {
				o.row(Out.i64(seed), Out.b(r.nextBoolean()));
			}
		}
		o.blank();

		o.fn(tag + ".nextFloat", "i64", "f32");
		for (long seed : SEEDS) {
			RandomSource r = ctor.apply(seed);
			for (int k = 0; k < 24; k++) {
				o.row(Out.i64(seed), Out.f32(r.nextFloat()));
			}
		}
		o.blank();

		o.fn(tag + ".nextDouble", "i64", "f64");
		for (long seed : SEEDS) {
			RandomSource r = ctor.apply(seed);
			for (int k = 0; k < 24; k++) {
				o.row(Out.i64(seed), Out.f64(r.nextDouble()));
			}
		}
		o.blank();

		o.fn(tag + ".nextGaussian", "i64", "f64");
		for (long seed : SEEDS) {
			RandomSource r = ctor.apply(seed);
			for (int k = 0; k < 16; k++) {
				o.row(Out.i64(seed), Out.f64(r.nextGaussian()));
			}
		}
		o.blank();

		// nextInt(bound): one transcript per bound, all sharing ONE instance per
		// seed so the stream position matters.
		o.fn(tag + ".nextIntBound", "i64 i32", "i32");
		for (long seed : SEEDS) {
			RandomSource r = ctor.apply(seed);
			for (int bound : BOUNDS) {
				for (int k = 0; k < 6; k++) {
					o.row(Out.join(Out.i64(seed), Out.i32(bound)), Out.i32(r.nextInt(bound)));
				}
			}
		}
		o.blank();

		o.fn(tag + ".nextIntBetweenInclusive", "i64 i32 i32", "i32");
		for (long seed : SEEDS) {
			RandomSource r = ctor.apply(seed);
			for (int[] range : new int[][]{{0, 0}, {0, 1}, {-5, 5}, {-10, 10}, {100, 200}, {-200, -100}}) {
				for (int k = 0; k < 6; k++) {
					o.row(Out.join(Out.i64(seed), Out.i32(range[0]), Out.i32(range[1])),
							Out.i32(r.nextIntBetweenInclusive(range[0], range[1])));
				}
			}
		}
		o.blank();

		o.fn(tag + ".triangleD", "i64 f64 f64", "f64");
		for (long seed : SEEDS) {
			RandomSource r = ctor.apply(seed);
			for (int k = 0; k < 16; k++) {
				o.row(Out.join(Out.i64(seed), Out.f64(10.0), Out.f64(3.0)), Out.f64(r.triangle(10.0, 3.0)));
			}
		}
		o.blank();

		o.fn(tag + ".triangleF", "i64 f32 f32", "f32");
		for (long seed : SEEDS) {
			RandomSource r = ctor.apply(seed);
			for (int k = 0; k < 16; k++) {
				o.row(Out.join(Out.i64(seed), Out.f32(10.0F), Out.f32(3.0F)), Out.f32(r.triangle(10.0F, 3.0F)));
			}
		}
		o.blank();

		o.fn(tag + ".consumeCount", "i64 i32", "i32");
		for (long seed : SEEDS) {
			for (int rounds : new int[]{0, 1, 2, 7, 64}) {
				RandomSource r = ctor.apply(seed);
				r.consumeCount(rounds);
				o.row(Out.join(Out.i64(seed), Out.i32(rounds)), Out.i32(r.nextInt()));
			}
		}
		o.blank();

		o.fn(tag + ".setSeed", "i64 i64", "i32");
		for (long seed : SEEDS) {
			for (long s2 : SEEDS) {
				RandomSource r = ctor.apply(seed);
				r.setSeed(s2);
				o.row(Out.join(Out.i64(seed), Out.i64(s2)), Out.i32(r.nextInt()));
			}
		}
		o.blank();

		o.fn(tag + ".fork", "i64", "i32 i32 i64");
		for (long seed : SEEDS) {
			RandomSource r = ctor.apply(seed);
			RandomSource f = r.fork();
			o.row(Out.i64(seed), Out.join(Out.i32(f.nextInt()), Out.i32(f.nextInt()), Out.i64(f.nextLong())));
		}
		o.blank();

		if (rawBits) {
			o.fn(tag + ".nextBits", "i64 i32", "i32");
			for (long seed : SEEDS) {
				BitRandomSource r = (BitRandomSource) ctor.apply(seed);
				for (int bits : new int[]{1, 2, 8, 16, 24, 31, 32}) {
					for (int k = 0; k < 4; k++) {
						o.row(Out.join(Out.i64(seed), Out.i32(bits)), Out.i32(r.next(bits)));
					}
				}
			}
			o.blank();
		}

		// Mth.wobble uses createThreadLocalInstance(seed) -> SingleThreadedRandomSource.
		o.fn("wobble_check", "i64", "i32");
		for (long seed : SEEDS) {
			RandomSource r = RandomSource.createThreadLocalInstance(seed);
			o.row(Out.i64(seed), Out.i32(r.nextInt()));
		}
		o.blank();
	}

	private static void legacy(final Out o) {
		transcript(o, "legacy", LegacyRandomSource::new, true);
	}

	private static void xoroshiro(final Out o) {
		transcript(o, "xoroshiro", XoroshiroRandomSource::new, false);

		// The three constructors must all be exercised.
		o.fn("xoroshiro.seed128", "i64 i64", "i64");
		for (long a : SEEDS) {
			for (long b : new long[]{0L, 1L, -1L, 7640891576956012809L, -7046029254386353131L}) {
				XoroshiroRandomSource r = new XoroshiroRandomSource(a, b);
				o.row(Out.join(Out.i64(a), Out.i64(b)), Out.i64(r.nextLong()));
			}
		}
		o.blank();

		o.fn("xoroshiro.seed128bit", "i64 i64", "i64");
		for (long a : SEEDS) {
			for (long b : new long[]{0L, 1L, -1L, 7640891576956012809L}) {
				XoroshiroRandomSource r = new XoroshiroRandomSource(new RandomSupport.Seed128bit(a, b));
				o.row(Out.join(Out.i64(a), Out.i64(b)), Out.i64(r.nextLong()));
			}
		}
		o.blank();

		o.fn("xoroshiro128pp", "i64 i64", "i64");
		for (long a : SEEDS) {
			for (long b : new long[]{0L, 1L, -1L, 7640891576956012809L, -7046029254386353131L}) {
				Xoroshiro128PlusPlus g = new Xoroshiro128PlusPlus(a, b);
				StringBuilder sb = new StringBuilder();
				for (int k = 0; k < 8; k++) {
					if (k > 0) {
						sb.append(' ');
					}

					sb.append(Out.i64(g.nextLong()));
				}
				o.row(Out.join(Out.i64(a), Out.i64(b)), sb.toString());
			}
		}
		o.blank();

		o.fn("xoroshiro128pp.zero", "", "i64");
		o.row("", Out.i64(new Xoroshiro128PlusPlus(0L, 0L).nextLong()));
		o.blank();
	}

	private static void singleThreaded(final Out o) {
		transcript(o, "single", SingleThreadedRandomSource::new, true);
	}

	private static void threadSafe(final Out o) {
		transcript(o, "threadsafe", ThreadSafeLegacyRandomSource::new, true);
	}

	private static void worldgen(final Out o) {
		o.fn("worldgen.setDecorationSeed", "i64 i32 i32", "i64");
		for (long seed : SEEDS) {
			for (int[] c : new int[][]{{0, 0}, {1, 2}, {-1, -2}, {1000000, -1000000}, {Integer.MAX_VALUE, Integer.MIN_VALUE}}) {
				WorldgenRandom r = new WorldgenRandom(RandomSource.create(seed));
				o.row(Out.join(Out.i64(seed), Out.i32(c[0]), Out.i32(c[1])),
						Out.i64(r.setDecorationSeed(seed, c[0], c[1])));
			}
		}
		o.blank();

		o.fn("worldgen.afterDecoration", "i64 i32 i32", "i32 i32 i64");
		for (long seed : SEEDS) {
			for (int[] c : new int[][]{{0, 0}, {1, 2}, {-1, -2}, {1000000, -1000000}}) {
				WorldgenRandom r = new WorldgenRandom(RandomSource.create(seed));
				r.setDecorationSeed(seed, c[0], c[1]);
				o.row(Out.join(Out.i64(seed), Out.i32(c[0]), Out.i32(c[1])),
						Out.join(Out.i32(r.nextInt()), Out.i32(r.nextInt()), Out.i64(r.getCount())));
			}
		}
		o.blank();

		o.fn("worldgen.setFeatureSeed", "i64 i32 i32", "i32");
		for (long seed : SEEDS) {
			WorldgenRandom r = new WorldgenRandom(RandomSource.create(seed));
			r.setFeatureSeed(seed, 3, 7);
			o.row(Out.i64(seed), Out.i32(r.nextInt()));
		}
		o.blank();

		o.fn("worldgen.setLargeFeatureSeed", "i64 i32 i32", "i32");
		for (long seed : SEEDS) {
			for (int[] c : new int[][]{{0, 0}, {1, 2}, {-1, -2}, {1000000, -1000000}}) {
				WorldgenRandom r = new WorldgenRandom(RandomSource.create(seed));
				r.setLargeFeatureSeed(seed, c[0], c[1]);
				o.row(Out.join(Out.i64(seed), Out.i32(c[0]), Out.i32(c[1])), Out.i32(r.nextInt()));
			}
		}
		o.blank();

		o.fn("worldgen.setLargeFeatureWithSalt", "i64 i32 i32 i32", "i32");
		for (long seed : SEEDS) {
			for (int[] c : new int[][]{{0, 0, 0}, {1, 2, 3}, {-1, -2, -3}, {1000000, -1000000, 1000000}}) {
				WorldgenRandom r = new WorldgenRandom(RandomSource.create(seed));
				r.setLargeFeatureWithSalt(seed, c[0], c[1], c[2]);
				o.row(Out.join(Out.i64(seed), Out.i32(c[0]), Out.i32(c[1]), Out.i32(c[2])), Out.i32(r.nextInt()));
			}
		}
		o.blank();

		o.fn("worldgen.nextBits", "i64 i32", "i32");
		for (long seed : SEEDS) {
			WorldgenRandom r = new WorldgenRandom(RandomSource.create(seed));
			for (int bits : new int[]{1, 8, 16, 31, 32}) {
				for (int k = 0; k < 4; k++) {
					o.row(Out.join(Out.i64(seed), Out.i32(bits)), Out.i32(r.next(bits)));
				}
			}
		}
		o.blank();

		o.fn("worldgen.overXoroshiro", "i64 i32", "i32");
		for (long seed : SEEDS) {
			WorldgenRandom r = new WorldgenRandom(new XoroshiroRandomSource(seed));
			for (int bits : new int[]{1, 8, 16, 31, 32}) {
				for (int k = 0; k < 4; k++) {
					o.row(Out.join(Out.i64(seed), Out.i32(bits)), Out.i32(r.next(bits)));
				}
			}
		}
		o.blank();

		o.fn("worldgen.seedSlimeChunk", "i32 i32 i64 i64", "i32");
		for (int[] c : new int[][]{{0, 0}, {1, 1}, {-1, -1}, {1000, -1000}}) {
			for (long s : new long[]{0L, 42L, -42L, Long.MAX_VALUE}) {
				RandomSource r = WorldgenRandom.seedSlimeChunk(c[0], c[1], s, 0x3ad8025fL);
				o.row(Out.join(Out.i32(c[0]), Out.i32(c[1]), Out.i64(s), Out.i64(0x3ad8025fL)), Out.i32(r.nextInt()));
			}
		}
		o.blank();

		o.fn("worldgen.algorithm", "i64 i32", "i32");
		for (long seed : SEEDS) {
			for (int a = 0; a < WorldgenRandom.Algorithm.values().length; a++) {
				RandomSource r = WorldgenRandom.Algorithm.values()[a].newInstance(seed);
				o.row(Out.join(Out.i64(seed), Out.i32(a)), Out.i32(r.nextInt()));
			}
		}
		o.blank();
	}

	private static void support(final Out o) {
		o.fn("mixStafford13", "i64", "i64");
		for (long v : SEEDS) {
			o.row(Out.i64(v), Out.i64(RandomSupport.mixStafford13(v)));
		}
		o.blank();

		o.fn("upgradeSeedTo128bitUnmixed", "i64", "i64 i64");
		for (long v : SEEDS) {
			RandomSupport.Seed128bit s = RandomSupport.upgradeSeedTo128bitUnmixed(v);
			o.row(Out.i64(v), Out.join(Out.i64(s.seedLo()), Out.i64(s.seedHi())));
		}
		o.blank();

		o.fn("upgradeSeedTo128bit", "i64", "i64 i64");
		for (long v : SEEDS) {
			RandomSupport.Seed128bit s = RandomSupport.upgradeSeedTo128bit(v);
			o.row(Out.i64(v), Out.join(Out.i64(s.seedLo()), Out.i64(s.seedHi())));
		}
		o.blank();

		o.fn("seedFromHashOf", "str", "i64 i64");
		String[] names = {"", "a", "minecraft:overworld", "abc", "\u00e4\u00f6\u00fc",
				"\u4f60\u597d\u4e16\u754c", "survival", "the_end", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"};
		for (String n : names) {
			RandomSupport.Seed128bit s = RandomSupport.seedFromHashOf(n);
			o.row(Out.str(n), Out.join(Out.i64(s.seedLo()), Out.i64(s.seedHi())));
		}
		o.blank();

		o.fn("seed128bit_xor", "i64 i64 i64 i64", "i64 i64");
		long[] vals = {0L, 1L, -1L, 42L, Long.MAX_VALUE, Long.MIN_VALUE};
		for (long a : vals) {
			for (long b : vals) {
				for (long c : vals) {
					for (long d : vals) {
						RandomSupport.Seed128bit s = new RandomSupport.Seed128bit(a, b).xor(c, d);
						o.row(Out.join(Out.i64(a), Out.i64(b), Out.i64(c), Out.i64(d)),
								Out.join(Out.i64(s.seedLo()), Out.i64(s.seedHi())));
					}
				}
			}
		}
		o.blank();

		o.fn("seed128bit_mixed", "i64 i64", "i64 i64");
		for (long a : vals) {
			for (long b : vals) {
				RandomSupport.Seed128bit s = new RandomSupport.Seed128bit(a, b).mixed();
				o.row(Out.join(Out.i64(a), Out.i64(b)), Out.join(Out.i64(s.seedLo()), Out.i64(s.seedHi())));
			}
		}
		o.blank();
	}

	private static void positional(final Out o) {
		int[][] coords = {
			{0, 0, 0}, {1, 1, 1}, {-1, -1, -1}, {0, 0, 64}, {0, 64, 0}, {64, 0, 0},
			{1000000, -1000000, 1000000}, {-1000000, 1000000, -1000000},
			{Integer.MAX_VALUE, Integer.MIN_VALUE, 0}, {12345, -67890, 111213},
		};

		for (int variant = 0; variant < 3; variant++) {
			String tag = variant == 0 ? "legacyPos" : (variant == 1 ? "xoroshiroPos" : "singlePos");
			o.fn(tag + ".at", "i64 i32 i32 i32", "i32 i32 i64");
			for (long seed : SEEDS) {
				PositionalRandomFactory f = factory(variant, seed);
				for (int[] c : coords) {
					RandomSource r = f.at(c[0], c[1], c[2]);
					o.row(Out.join(Out.i64(seed), Out.i32(c[0]), Out.i32(c[1]), Out.i32(c[2])),
							Out.join(Out.i32(r.nextInt()), Out.i32(r.nextInt()), Out.i64(r.nextLong())));
				}
			}
			o.blank();

			o.fn(tag + ".fromHashOf", "i64 str", "i32 i32 i64");
			for (long seed : SEEDS) {
				PositionalRandomFactory f = factory(variant, seed);
				for (String n : new String[]{"", "a", "minecraft:overworld", "survival", "\u00e4\u00f6\u00fc"}) {
					RandomSource r = f.fromHashOf(n);
					o.row(Out.join(Out.i64(seed), Out.str(n)),
							Out.join(Out.i32(r.nextInt()), Out.i32(r.nextInt()), Out.i64(r.nextLong())));
				}
			}
			o.blank();

			o.fn(tag + ".fromSeed", "i64 i64", "i32 i32 i64");
			for (long seed : SEEDS) {
				PositionalRandomFactory f = factory(variant, seed);
				for (long s : SEEDS) {
					RandomSource r = f.fromSeed(s);
					o.row(Out.join(Out.i64(seed), Out.i64(s)),
							Out.join(Out.i32(r.nextInt()), Out.i32(r.nextInt()), Out.i64(r.nextLong())));
				}
			}
			o.blank();

			o.fn(tag + ".parityConfigString", "i64", "str");
			for (long seed : SEEDS) {
				StringBuilder sb = new StringBuilder();
				factory(variant, seed).parityConfigString(sb);
				o.row(Out.i64(seed), Out.str(sb.toString()));
			}
			o.blank();
		}

		// forkPositional() consumes from the source before wrapping the factory.
		o.fn("forkPositional", "i64 i32", "i32 i64");
		for (int variant = 0; variant < 4; variant++) {
			for (long seed : SEEDS) {
				RandomSource r = src(variant, seed);
				PositionalRandomFactory f = r.forkPositional();
				RandomSource at = f.at(3, -4, 5);
				o.row(Out.join(Out.i64(seed), Out.i32(variant)),
						Out.join(Out.i32(at.nextInt()), Out.i64(at.nextLong())));
			}
		}
		o.blank();
	}

	private static PositionalRandomFactory factory(final int variant, final long seed) {
		return switch (variant) {
			case 0 -> new LegacyRandomSource.LegacyPositionalRandomFactory(seed);
			case 1 -> new XoroshiroRandomSource.XoroshiroPositionalRandomFactory(seed, seed ^ 0x9E3779B97F4A7C15L);
			default -> new LegacyRandomSource.LegacyPositionalRandomFactory(seed);
		};
	}

	private static RandomSource src(final int variant, final long seed) {
		return switch (variant) {
			case 0 -> new LegacyRandomSource(seed);
			case 1 -> new XoroshiroRandomSource(seed);
			case 2 -> new SingleThreadedRandomSource(seed);
			default -> new ThreadSafeLegacyRandomSource(seed);
		};
	}

	private static void lcg(final Out o) {
		o.fn("lcg.next", "i64 i64", "i64");
		long[] vals = {0L, 1L, -1L, 42L, Long.MAX_VALUE, Long.MIN_VALUE, 0x0123456789ABCDEFL,
				123456789L, -123456789L, 0x5555555555555555L};
		for (long r : vals) {
			for (long c : vals) {
				o.row(Out.join(Out.i64(r), Out.i64(c)),
						Out.i64(net.minecraft.util.LinearCongruentialGenerator.next(r, c)));
			}
		}
		o.blank();
	}

	private static void bitRandom(final Out o) {
		// nextInt()/nextLong()/nextFloat()/nextDouble() on a bare BitRandomSource
		// with a power-of-two bound hit the (bound & bound-1) == 0 fast path.
		o.fn("bit.nextIntPow2", "i64 i32", "i32");
		for (long seed : SEEDS) {
			BitRandomSource r = new LegacyRandomSource(seed);
			for (int bound : new int[]{1, 2, 4, 8, 16, 1024, 65536, 1 << 30}) {
				for (int k = 0; k < 4; k++) {
					o.row(Out.join(Out.i64(seed), Out.i32(bound)), Out.i32(r.nextInt(bound)));
				}
			}
		}
		o.blank();

		o.fn("bit.seed", "i64", "i64");
		for (long seed : SEEDS) {
			BitRandomSource r = new LegacyRandomSource(seed);
			o.row(Out.i64(seed), Out.i64(r.nextLong()));
		}
		o.blank();

		o.fn("mth.getSeed", "i32 i32 i32", "i64");
		for (int x : new int[]{0, 1, -1, 1000000, -1000000, Integer.MAX_VALUE, Integer.MIN_VALUE}) {
			o.row(Out.join(Out.i32(x), Out.i32(-x), Out.i32(x * 7)), Out.i64(Mth.getSeed(x, -x, x * 7)));
		}
		o.blank();
	}
}