//! Module declarations for `net.minecraft.client.multiplayer.chat.report` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbuseReportSender;
pub mod BanReason;
pub mod ChatReport;
pub mod ChatReportContextBuilder;
pub mod NameReport;
pub mod Report;
pub mod ReportEnvironment;
pub mod ReportReason;
pub mod ReportType;
pub mod ReportingContext;
pub mod SkinReport;
#[path = "package-info.rs"]
pub mod package_info;
