//! Module declarations for `net.minecraft.world.entity.animal.feline` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod Cat;
pub mod CatSoundVariant;
pub mod CatSoundVariants;
pub mod CatVariant;
pub mod CatVariants;
pub mod Ocelot;
#[path = "package-info.rs"]
pub mod package_info;
