//! Module declarations for `net.minecraft.network.syncher` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod EntityDataAccessor;
pub mod EntityDataSerializer;
pub mod EntityDataSerializers;
pub mod SyncedDataHolder;
pub mod SynchedEntityData;
#[path = "package-info.rs"]
pub mod package_info;
