//! Module declarations for `net.minecraft.world.entity.monster.piglin` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractPiglin;
pub mod Piglin;
pub mod PiglinAi;
pub mod PiglinArmPose;
pub mod PiglinBrute;
pub mod PiglinBruteAi;
pub mod RememberIfHoglinWasKilled;
pub mod StartAdmiringItemIfSeen;
pub mod StartHuntingHoglin;
pub mod StopAdmiringIfItemTooFarAway;
pub mod StopAdmiringIfTiredOfTryingToReachItem;
pub mod StopHoldingItemIfNoLongerAdmiring;
#[path = "package-info.rs"]
pub mod package_info;
