//! Module declarations for `net.minecraft.client.renderer.block.dispatch.multipart` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod CombinedCondition;
pub mod Condition;
pub mod KeyValueCondition;
pub mod MultiPartModel;
pub mod Selector;
#[path = "package-info.rs"]
pub mod package_info;
