//! Module declarations for `net.minecraft.world.entity.projectile.arrow` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractArrow;
pub mod Arrow;
pub mod SpectralArrow;
pub mod ThrownTrident;
#[path = "package-info.rs"]
pub mod package_info;
