//! Module declarations for `net.minecraft.gizmos` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod ArrowGizmo;
pub mod CircleGizmo;
pub mod CuboidGizmo;
pub mod Gizmo;
pub mod GizmoCollector;
pub mod GizmoPrimitives;
pub mod GizmoProperties;
pub mod GizmoStyle;
pub mod Gizmos;
pub mod LineGizmo;
pub mod PointGizmo;
pub mod RectGizmo;
pub mod SimpleGizmoCollector;
pub mod TextGizmo;
#[path = "package-info.rs"]
pub mod package_info;
