//! Module declarations for `net.minecraft.data.structures` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod NbtToSnbt;
pub mod SnbtDatafixer;
pub mod SnbtToNbt;
pub mod StructureUpdater;
#[path = "package-info.rs"]
pub mod package_info;
