//! Module declarations for `net.minecraft.network.protocol.login.custom` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod CustomQueryAnswerPayload;
pub mod CustomQueryPayload;
pub mod DiscardedQueryAnswerPayload;
pub mod DiscardedQueryPayload;
#[path = "package-info.rs"]
pub mod package_info;
