//! Module declarations for `net.minecraft.world.level.storage.loot.providers.nbt` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod ContextNbtProvider;
pub mod NbtProvider;
pub mod NbtProviders;
pub mod StorageNbtProvider;
#[path = "package-info.rs"]
pub mod package_info;
