//! Module declarations for `net.minecraft.world.flag` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod FeatureElement;
pub mod FeatureFlag;
pub mod FeatureFlagRegistry;
pub mod FeatureFlagSet;
pub mod FeatureFlagUniverse;
pub mod FeatureFlags;
#[path = "package-info.rs"]
pub mod package_info;
