//! Module declarations for `net.minecraft.world.phys.shapes` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod ArrayVoxelShape;
pub mod BitSetDiscreteVoxelShape;
pub mod BooleanOp;
pub mod CollisionContext;
pub mod CubePointRange;
pub mod CubeVoxelShape;
pub mod DiscreteCubeMerger;
pub mod DiscreteVoxelShape;
pub mod EntityCollisionContext;
pub mod IdenticalMerger;
pub mod IndexMerger;
pub mod IndirectMerger;
pub mod MinecartCollisionContext;
pub mod NonOverlappingMerger;
pub mod OffsetDoubleList;
pub mod PositionCollisionContext;
pub mod Shapes;
pub mod SliceShape;
pub mod SubShape;
pub mod VoxelShape;
#[path = "package-info.rs"]
pub mod package_info;
