//! Module declarations for `net.minecraft.client.model.geom.builders` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod CubeDefinition;
pub mod CubeDeformation;
pub mod CubeListBuilder;
pub mod LayerDefinition;
pub mod MaterialDefinition;
pub mod MeshDefinition;
pub mod MeshTransformer;
pub mod PartDefinition;
pub mod UVPair;
#[path = "package-info.rs"]
pub mod package_info;
