//! Module declarations for `net.minecraft.util.filefix.virtualfilesystem` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod exception;

pub mod CopyOnWriteFSPath;
pub mod CopyOnWriteFSProvider;
pub mod CopyOnWriteFileStore;
pub mod CopyOnWriteFileSystem;
pub mod DirectoryNode;
pub mod FileMove;
pub mod FileNode;
pub mod Node;
#[path = "package-info.rs"]
pub mod package_info;
