//! Module declarations for `net.minecraft.client.resources.model.cuboid` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod CuboidFace;
pub mod CuboidModel;
pub mod CuboidModelElement;
pub mod CuboidRotation;
pub mod FaceBakery;
pub mod ItemModelGenerator;
pub mod ItemTransform;
pub mod ItemTransforms;
pub mod MissingCuboidModel;
pub mod UnbakedCuboidGeometry;
#[path = "package-info.rs"]
pub mod package_info;
