//! Module declarations for `net.minecraft.server.dialog.body` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod DialogBody;
pub mod DialogBodyTypes;
pub mod ItemBody;
pub mod PlainMessage;
#[path = "package-info.rs"]
pub mod package_info;
