//! Module declarations for `net.minecraft.client.input` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod CharacterEvent;
pub mod InputQuirks;
pub mod InputWithModifiers;
pub mod KeyEvent;
pub mod MouseButtonEvent;
pub mod MouseButtonInfo;
pub mod PreeditEvent;
#[path = "package-info.rs"]
pub mod package_info;
