//! Module declarations for `net.minecraft.client.gui.screens.advancements` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AdvancementTab;
pub mod AdvancementTabType;
pub mod AdvancementWidget;
pub mod AdvancementWidgetType;
pub mod AdvancementsScreen;
#[path = "package-info.rs"]
pub mod package_info;
