//! Module declarations for `net.minecraft.world.entity.animal.golem` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractGolem;
pub mod CopperGolem;
pub mod CopperGolemAi;
pub mod CopperGolemOxidationLevel;
pub mod CopperGolemOxidationLevels;
pub mod CopperGolemState;
pub mod IronGolem;
pub mod SnowGolem;
#[path = "package-info.rs"]
pub mod package_info;
