//! Module declarations for `net.minecraft.client.player` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod inventory;

pub mod AbstractClientPlayer;
pub mod ClientInput;
pub mod KeyboardInput;
pub mod LocalPlayer;
pub mod LocalPlayerResolver;
pub mod RemotePlayer;
#[path = "package-info.rs"]
pub mod package_info;
