//! Module declarations for `com.mojang.blaze3d.vulkan.glsl` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod GlslCompiler;
pub mod IntermediaryShaderModule;
pub mod ShaderCompileException;
pub mod SpvSampler;
pub mod SpvUniformBuffer;
pub mod SpvVariable;
pub mod SpvcUtil;
#[path = "package-info.rs"]
pub mod package_info;
