//! Module declarations for `net.minecraft.client.server` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod IntegratedPlayerList;
pub mod IntegratedServer;
pub mod LanServer;
pub mod LanServerDetection;
pub mod LanServerPinger;
#[path = "package-info.rs"]
pub mod package_info;
