//! Module declarations for `net.minecraft.data.worldgen.placement` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AquaticPlacements;
pub mod CavePlacements;
pub mod EndPlacements;
pub mod MiscOverworldPlacements;
pub mod NetherPlacements;
pub mod OrePlacements;
pub mod PlacementUtils;
pub mod TreePlacements;
pub mod VegetationPlacements;
pub mod VillagePlacements;
#[path = "package-info.rs"]
pub mod package_info;
