//! Module declarations for `net.minecraft.client.gui.spectator` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod categories;

pub mod PlayerMenuItem;
pub mod RootSpectatorMenuCategory;
pub mod SpectatorMenu;
pub mod SpectatorMenuCategory;
pub mod SpectatorMenuItem;
pub mod SpectatorMenuListener;
#[path = "package-info.rs"]
pub mod package_info;
