//! Module declarations for `net.minecraft.world.level.timers` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod FunctionCallback;
pub mod FunctionTagCallback;
pub mod TimerCallback;
pub mod TimerCallbacks;
pub mod TimerQueue;
#[path = "package-info.rs"]
pub mod package_info;
