//! Module declarations for `net.minecraft.client.gui.font.glyphs` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BakedGlyph;
pub mod BakedSheetGlyph;
pub mod EffectGlyph;
pub mod EmptyGlyph;
pub mod SpecialGlyphs;
#[path = "package-info.rs"]
pub mod package_info;
