//! Module declarations for `net.minecraft.client.telemetry.events` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AggregatedTelemetryEvent;
pub mod GameLoadTimesEvent;
pub mod PerformanceMetricsEvent;
pub mod WorldLoadEvent;
pub mod WorldLoadTimesEvent;
pub mod WorldUnloadEvent;
#[path = "package-info.rs"]
pub mod package_info;
