//! Module declarations for `net.minecraft.server.network.config` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod JoinWorldTask;
pub mod PrepareSpawnTask;
pub mod ServerCodeOfConductConfigurationTask;
pub mod ServerResourcePackConfigurationTask;
pub mod SynchronizeRegistriesTask;
#[path = "package-info.rs"]
pub mod package_info;
