//! Module declarations for `net.minecraft.world.entity.ai` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod attributes;
pub mod behavior;
pub mod control;
pub mod goal;
pub mod gossip;
pub mod memory;
pub mod navigation;
pub mod sensing;
pub mod targeting;
pub mod util;
pub mod village;

pub mod ActivityData;
pub mod Brain;
#[path = "package-info.rs"]
pub mod package_info;
