//! Module declarations for `net.minecraft.util.thread` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractConsecutiveExecutor;
pub mod BlockableEventLoop;
pub mod ConsecutiveExecutor;
pub mod ParallelMapTransform;
pub mod PriorityConsecutiveExecutor;
pub mod ReentrantBlockableEventLoop;
pub mod StrictQueue;
pub mod TaskScheduler;
#[path = "package-info.rs"]
pub mod package_info;
