//! Module declarations for `net.minecraft.server.commands.data` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BlockDataAccessor;
pub mod DataAccessor;
pub mod DataCommands;
pub mod EntityDataAccessor;
pub mod StorageDataAccessor;
#[path = "package-info.rs"]
pub mod package_info;
