//! Module declarations for `net.minecraft.world.clock` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod ClockManager;
pub mod ClockNetworkState;
pub mod ClockState;
pub mod ClockTimeMarker;
pub mod ClockTimeMarkers;
pub mod PackedClockStates;
pub mod ServerClockManager;
pub mod WorldClock;
pub mod WorldClocks;
#[path = "package-info.rs"]
pub mod package_info;
