//! Module declarations for `net.minecraft.world.damagesource` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod CombatEntry;
pub mod CombatRules;
pub mod CombatTracker;
pub mod DamageEffects;
pub mod DamageScaling;
pub mod DamageSource;
pub mod DamageSources;
pub mod DamageType;
pub mod DamageTypes;
pub mod DeathMessageType;
pub mod FallLocation;
#[path = "package-info.rs"]
pub mod package_info;
