//! Module declarations for `net.minecraft.client.gui.components.debugchart` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractDebugChart;
pub mod BandwidthDebugChart;
pub mod FpsDebugChart;
pub mod PingDebugChart;
pub mod ProfilerPieChart;
pub mod TpsDebugChart;
#[path = "package-info.rs"]
pub mod package_info;
