//! Module declarations for `net.minecraft.core.particles` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BlockParticleOption;
pub mod ColorParticleOption;
pub mod DustColorTransitionOptions;
pub mod DustParticleOptions;
pub mod ExplosionParticleInfo;
pub mod GeyserBaseParticleOptions;
pub mod GeyserParticleOptions;
pub mod ItemParticleOption;
pub mod ParticleLimit;
pub mod ParticleOptions;
pub mod ParticleType;
pub mod ParticleTypes;
pub mod PowerParticleOption;
pub mod ScalableParticleOptionsBase;
pub mod SculkChargeParticleOptions;
pub mod ShriekParticleOption;
pub mod SimpleParticleType;
pub mod SpellParticleOption;
pub mod TrailParticleOption;
pub mod VibrationParticleOption;
#[path = "package-info.rs"]
pub mod package_info;
