//! Module declarations for `net.minecraft.util.profiling.metrics.profiling` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod ActiveMetricsRecorder;
pub mod InactiveMetricsRecorder;
pub mod MetricsRecorder;
pub mod ProfilerSamplerAdapter;
pub mod ServerMetricsSamplersProvider;
#[path = "package-info.rs"]
pub mod package_info;
