//! Module declarations for `net.minecraft.client.model.monster.slime` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod MagmaCubeModel;
pub mod SlimeModel;
pub mod SmallSulfurCubeModel;
pub mod SulfurCubeModel;
#[path = "package-info.rs"]
pub mod package_info;
