//! Module declarations for `net.minecraft.world.level.levelgen.feature.featuresize` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod FeatureSize;
pub mod FeatureSizeType;
pub mod ThreeLayersFeatureSize;
pub mod TwoLayersFeatureSize;
#[path = "package-info.rs"]
pub mod package_info;
