//! Module declarations for `net.minecraft.server.notifications` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod EmptyNotificationService;
pub mod NotificationManager;
pub mod NotificationService;
pub mod ServerActivityMonitor;
#[path = "package-info.rs"]
pub mod package_info;
