//! Module declarations for `net.minecraft.world.level.dimension` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod end;

pub mod BuiltinDimensionTypes;
pub mod DimensionDefaults;
pub mod DimensionType;
pub mod LevelStem;
#[path = "package-info.rs"]
pub mod package_info;
