//! Module declarations for `net.minecraft.commands.execution.tasks` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BuildContexts;
pub mod CallFunction;
pub mod ContinuationTask;
pub mod ExecuteCommand;
pub mod FallthroughTask;
pub mod IsolatedCall;
#[path = "package-info.rs"]
pub mod package_info;
