//! Module declarations for `net.minecraft.client.renderer` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod block;
pub mod blockentity;
pub mod chunk;
pub mod culling;
pub mod debug;
pub mod entity;
pub mod extract;
pub mod feature;
pub mod fog;
pub mod gizmos;
pub mod item;
pub mod rendertype;
pub mod special;
pub mod state;
pub mod texture;

pub mod BindGroupLayouts;
pub mod BiomeColors;
pub mod CloudRenderer;
pub mod CubeMap;
pub mod DebugCrosshairRenderer;
pub mod DynamicUniformStorage;
pub mod DynamicUniforms;
pub mod EndFlashState;
pub mod FaceInfo;
pub mod GameRenderer;
pub mod GlobalSettingsUniform;
pub mod GpuWarnlistManager;
pub mod ItemInHandRenderer;
pub mod LevelEventHandler;
pub mod LevelRenderer;
pub mod LevelTargetBundle;
pub mod Lightmap;
pub mod LightmapRenderStateExtractor;
pub mod MapRenderer;
pub mod MappableRingBuffer;
pub mod MultiblockChestResources;
pub mod Octree;
pub mod OrderedSubmitNodeCollector;
pub mod Panorama;
pub mod PlayerSkinRenderCache;
pub mod PostChain;
pub mod PostChainConfig;
pub mod PostPass;
pub mod Projection;
pub mod ProjectionMatrixBuffer;
pub mod Rect2i;
pub mod RenderBuffers;
pub mod RenderPipelines;
pub mod RunningTrimmedMean;
pub mod ScreenEffectRenderer;
pub mod SectionBufferBuilderPack;
pub mod SectionBufferBuilderPool;
pub mod SectionOcclusionGraph;
pub mod ShaderDefines;
pub mod ShaderManager;
pub mod Sheets;
pub mod SkyRenderer;
pub mod SpriteCoordinateExpander;
pub mod SpriteMapper;
pub mod StagedVertexBuffer;
pub mod SubmitNodeCollection;
pub mod SubmitNodeCollector;
pub mod SubmitNodeStorage;
pub mod UiLightmap;
pub mod UniformValue;
pub mod ViewArea;
pub mod WeatherEffectRenderer;
pub mod WorldBorderRenderer;
#[path = "package-info.rs"]
pub mod package_info;
