//! Module declarations for `net.minecraft.world.waypoints` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod PartialTickSupplier;
pub mod TrackedWaypoint;
pub mod TrackedWaypointManager;
pub mod Waypoint;
pub mod WaypointManager;
pub mod WaypointStyleAsset;
pub mod WaypointStyleAssets;
pub mod WaypointTransmitter;
#[path = "package-info.rs"]
pub mod package_info;
