//! Module declarations for `net.minecraft.client.model.animal.wolf` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AdultWolfModel;
pub mod BabyWolfModel;
pub mod WolfModel;
#[path = "package-info.rs"]
pub mod package_info;
