//! Module declarations for `net.minecraft.world.inventory` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod tooltip;

pub mod AbstractContainerMenu;
pub mod AbstractCraftingMenu;
pub mod AbstractFurnaceMenu;
pub mod AbstractMountInventoryMenu;
pub mod AnvilMenu;
pub mod ArmorSlot;
pub mod BeaconMenu;
pub mod BlastFurnaceMenu;
pub mod BrewingStandMenu;
pub mod CartographyTableMenu;
pub mod ChestMenu;
pub mod ClickAction;
pub mod ContainerData;
pub mod ContainerInput;
pub mod ContainerLevelAccess;
pub mod ContainerListener;
pub mod ContainerSynchronizer;
pub mod CrafterMenu;
pub mod CrafterSlot;
pub mod CraftingContainer;
pub mod CraftingMenu;
pub mod DataSlot;
pub mod DispenserMenu;
pub mod EnchantmentMenu;
pub mod FurnaceFuelSlot;
pub mod FurnaceMenu;
pub mod FurnaceResultSlot;
pub mod GrindstoneMenu;
pub mod HopperMenu;
pub mod HorseInventoryMenu;
pub mod InventoryMenu;
pub mod ItemCombinerMenu;
pub mod ItemCombinerMenuSlotDefinition;
pub mod LecternMenu;
pub mod LoomMenu;
pub mod MenuConstructor;
pub mod MenuType;
pub mod MerchantContainer;
pub mod MerchantMenu;
pub mod MerchantResultSlot;
pub mod NautilusInventoryMenu;
pub mod NonInteractiveResultSlot;
pub mod PlayerEnderChestContainer;
pub mod RecipeBookMenu;
pub mod RecipeBookType;
pub mod RecipeCraftingHolder;
pub mod RemoteSlot;
pub mod ResultContainer;
pub mod ResultSlot;
pub mod ShulkerBoxMenu;
pub mod ShulkerBoxSlot;
pub mod SimpleContainerData;
pub mod Slot;
pub mod SlotRange;
pub mod SlotRanges;
pub mod SmithingMenu;
pub mod SmokerMenu;
pub mod StackedContentsCompatible;
pub mod StonecutterMenu;
pub mod TransientCraftingContainer;
#[path = "package-info.rs"]
pub mod package_info;
