//! Module declarations for `net.minecraft.stats` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod RecipeBook;
pub mod RecipeBookSettings;
pub mod ServerRecipeBook;
pub mod ServerStatsCounter;
pub mod Stat;
pub mod StatFormatter;
pub mod StatType;
pub mod Stats;
pub mod StatsCounter;
#[path = "package-info.rs"]
pub mod package_info;
