//! Module declarations for `net.minecraft.data.advancements` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod packs;

pub mod AdvancementProvider;
pub mod AdvancementSubProvider;
#[path = "package-info.rs"]
pub mod package_info;
