//! Module declarations for `net.minecraft.world.level.levelgen.structure.pools.alias` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod DirectPoolAlias;
pub mod PoolAliasBinding;
pub mod PoolAliasBindings;
pub mod PoolAliasLookup;
pub mod RandomGroupPoolAlias;
pub mod RandomPoolAlias;
#[path = "package-info.rs"]
pub mod package_info;
