//! Module declarations for `net.minecraft.client.gui.components.debug` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod DebugEntryBiome;
pub mod DebugEntryCategory;
pub mod DebugEntryChunkGeneration;
pub mod DebugEntryChunkRenderStats;
pub mod DebugEntryChunkSourceStats;
pub mod DebugEntryDayCount;
pub mod DebugEntryDetailedMemory;
pub mod DebugEntryEntityRenderStats;
pub mod DebugEntryFps;
pub mod DebugEntryGpuUtilization;
pub mod DebugEntryHeightmap;
pub mod DebugEntryLight;
pub mod DebugEntryLocalDifficulty;
pub mod DebugEntryLookingAt;
pub mod DebugEntryLookingAtEntity;
pub mod DebugEntryLookingAtEntityTags;
pub mod DebugEntryMemory;
pub mod DebugEntryNoop;
pub mod DebugEntryParticleRenderStats;
pub mod DebugEntryPosition;
pub mod DebugEntryPostEffect;
pub mod DebugEntrySectionPosition;
pub mod DebugEntrySimplePerformanceImpactors;
pub mod DebugEntrySoundCache;
pub mod DebugEntrySoundMood;
pub mod DebugEntrySpawnCounts;
pub mod DebugEntrySystemSpecs;
pub mod DebugEntryTps;
pub mod DebugEntryVersion;
pub mod DebugScreenDisplayer;
pub mod DebugScreenEntries;
pub mod DebugScreenEntry;
pub mod DebugScreenEntryList;
pub mod DebugScreenEntryStatus;
pub mod DebugScreenProfile;
#[path = "package-info.rs"]
pub mod package_info;
