//! Module declarations for `net.minecraft.client.multiplayer` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod chat;
pub mod prediction;
pub mod resolver;

pub mod AccountProfileKeyPairManager;
pub mod CacheSlot;
pub mod ChunkBatchSizeCalculator;
pub mod ClientAdvancements;
pub mod ClientChunkCache;
pub mod ClientCommonPacketListenerImpl;
pub mod ClientConfigurationPacketListenerImpl;
pub mod ClientDebugSubscriber;
pub mod ClientExplosionTracker;
pub mod ClientHandshakePacketListenerImpl;
pub mod ClientLevel;
pub mod ClientPacketListener;
pub mod ClientRecipeContainer;
pub mod ClientRegistryLayer;
pub mod ClientSuggestionProvider;
pub mod CommonListenerCookie;
pub mod KnownPacksManager;
pub mod LegacyServerPinger;
pub mod LevelLoadTracker;
pub mod MultiPlayerGameMode;
pub mod PingDebugMonitor;
pub mod PlayerInfo;
pub mod ProfileKeyPairManager;
pub mod RegistryDataCollector;
pub mod ServerData;
pub mod ServerList;
pub mod ServerStatusPinger;
pub mod SessionSearchTrees;
pub mod TransferState;
#[path = "package-info.rs"]
pub mod package_info;
