//! Module declarations for `net.minecraft.world.level.biome` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod Biome;
pub mod BiomeGenerationSettings;
pub mod BiomeManager;
pub mod BiomeResolver;
pub mod BiomeSource;
pub mod BiomeSources;
pub mod BiomeSpecialEffects;
pub mod Biomes;
pub mod CheckerboardColumnBiomeSource;
pub mod Climate;
pub mod FeatureSorter;
pub mod FixedBiomeSource;
pub mod MobSpawnSettings;
pub mod MultiNoiseBiomeSource;
pub mod MultiNoiseBiomeSourceParameterList;
pub mod MultiNoiseBiomeSourceParameterLists;
pub mod OverworldBiomeBuilder;
pub mod TheEndBiomeSource;
#[path = "package-info.rs"]
pub mod package_info;
