//! Module declarations for `net.minecraft.world.entity.animal.fish` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractFish;
pub mod AbstractSchoolingFish;
pub mod Cod;
pub mod Pufferfish;
pub mod Salmon;
pub mod TropicalFish;
pub mod WaterAnimal;
#[path = "package-info.rs"]
pub mod package_info;
