//! Module declarations for `net.minecraft.client.renderer.state.gui.pip` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod GuiBannerResultRenderState;
pub mod GuiBookModelRenderState;
pub mod GuiEntityRenderState;
pub mod GuiProfilerChartRenderState;
pub mod GuiSkinRenderState;
pub mod OversizedItemRenderState;
pub mod PictureInPictureRenderState;
#[path = "package-info.rs"]
pub mod package_info;
