//! Module declarations for `net.minecraft.world.level.levelgen.structure.templatesystem` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod loader;
pub mod rule;

pub mod AlwaysTrueTest;
pub mod AxisAlignedLinearPosTest;
pub mod BlackstoneReplaceProcessor;
pub mod BlockAgeProcessor;
pub mod BlockIgnoreProcessor;
pub mod BlockMatchTest;
pub mod BlockRotProcessor;
pub mod BlockStateMatchTest;
pub mod CappedProcessor;
pub mod GravityProcessor;
pub mod JigsawReplacementProcessor;
pub mod LavaSubmergedBlockProcessor;
pub mod LinearPosTest;
pub mod LiquidSettings;
pub mod NopProcessor;
pub mod PosAlwaysTrueTest;
pub mod PosRuleTest;
pub mod PosRuleTestType;
pub mod ProcessorRule;
pub mod ProtectedBlockProcessor;
pub mod RandomBlockMatchTest;
pub mod RandomBlockStateMatchTest;
pub mod RuleProcessor;
pub mod RuleTest;
pub mod RuleTestType;
pub mod StructurePlaceSettings;
pub mod StructureProcessor;
pub mod StructureProcessorList;
pub mod StructureProcessorType;
pub mod StructureProcessorTypes;
pub mod StructureTemplate;
pub mod StructureTemplateManager;
pub mod TagMatchTest;
#[path = "package-info.rs"]
pub mod package_info;
