//! Module declarations for `net.minecraft.client.model.animal.turtle` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AdultTurtleModel;
pub mod BabyTurtleModel;
pub mod TurtleModel;
#[path = "package-info.rs"]
pub mod package_info;
