//! Module declarations for `net.minecraft.client.data` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod models;

pub mod AtlasProvider;
pub mod Main;
#[path = "package-info.rs"]
pub mod package_info;
