//! Module declarations for `net.minecraft.world.entity.ai.navigation` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AmphibiousPathNavigation;
pub mod FlyingPathNavigation;
pub mod GroundPathNavigation;
pub mod PathNavigation;
pub mod WallClimberNavigation;
pub mod WaterBoundPathNavigation;
#[path = "package-info.rs"]
pub mod package_info;
