//! Module declarations for `net.minecraft.world.entity.variant` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BiomeCheck;
pub mod ModelAndTexture;
pub mod MoonBrightnessCheck;
pub mod PriorityProvider;
pub mod SpawnCondition;
pub mod SpawnConditions;
pub mod SpawnContext;
pub mod SpawnPrioritySelectors;
pub mod StructureCheck;
pub mod VariantUtils;
#[path = "package-info.rs"]
pub mod package_info;
