//! Module declarations for `net.minecraft.client.data.models.model` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod DelegatedModel;
pub mod ItemModelUtils;
pub mod ModelInstance;
pub mod ModelLocationUtils;
pub mod ModelTemplate;
pub mod ModelTemplates;
pub mod TextureMapping;
pub mod TextureSlot;
pub mod TexturedModel;
#[path = "package-info.rs"]
pub mod package_info;
