//! Module declarations for `net.minecraft.world.entity.animal.chicken` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod Chicken;
pub mod ChickenSoundVariant;
pub mod ChickenSoundVariants;
pub mod ChickenVariant;
pub mod ChickenVariants;
#[path = "package-info.rs"]
pub mod package_info;
