//! Module declarations for `net.minecraft.util.profiling.metrics` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod profiling;
pub mod storage;

pub mod MetricCategory;
pub mod MetricSampler;
pub mod MetricsRegistry;
pub mod MetricsSamplerProvider;
pub mod ProfilerMeasured;
#[path = "package-info.rs"]
pub mod package_info;
