//! Module declarations for `net.minecraft.world.level.gamerules` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod GameRule;
pub mod GameRuleCategory;
pub mod GameRuleMap;
pub mod GameRuleType;
pub mod GameRuleTypeVisitor;
pub mod GameRules;
#[path = "package-info.rs"]
pub mod package_info;
