//! Module declarations for `net.minecraft.client.gui.font.providers` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BitmapProvider;
pub mod FreeTypeUtil;
pub mod GlyphProviderDefinition;
pub mod GlyphProviderType;
pub mod ProviderReferenceDefinition;
pub mod TrueTypeGlyphProviderDefinition;
pub mod UnihexProvider;
#[path = "package-info.rs"]
pub mod package_info;
