//! Module declarations for `net.minecraft.server.jsonrpc.websocket` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod JsonToWebSocketEncoder;
pub mod WebSocketToJsonCodec;
#[path = "package-info.rs"]
pub mod package_info;
