//! Module declarations for `net.minecraft.util.datafix` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod fixes;
pub mod schemas;

pub mod DataFixTypes;
pub mod DataFixers;
pub mod ExtraDataFixUtils;
pub mod LegacyComponentDataFixUtils;
pub mod PackedBitStorage;
#[path = "package-info.rs"]
pub mod package_info;
