//! Module declarations for `net.minecraft.client.gui.screens.multiplayer` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod CodeOfConductScreen;
pub mod JoinMultiplayerScreen;
pub mod RestrictionsScreen;
pub mod SafetyScreen;
pub mod ServerReconfigScreen;
pub mod ServerSelectionList;
pub mod WarningScreen;
#[path = "package-info.rs"]
pub mod package_info;
