//! Module declarations for `net.minecraft.client.renderer.feature.submit` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BatchableSubmit;
pub mod SubmitNode;
pub mod TranslucentSubmit;
#[path = "package-info.rs"]
pub mod package_info;
