//! Module declarations for `net.minecraft.world.level.levelgen.structure.structures` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod BuriedTreasurePieces;
pub mod BuriedTreasureStructure;
pub mod DesertPyramidPiece;
pub mod DesertPyramidStructure;
pub mod EndCityPieces;
pub mod EndCityStructure;
pub mod IglooPieces;
pub mod IglooStructure;
pub mod JigsawStructure;
pub mod JungleTemplePiece;
pub mod JungleTempleStructure;
pub mod MineshaftPieces;
pub mod MineshaftStructure;
pub mod NetherFortressPieces;
pub mod NetherFortressStructure;
pub mod NetherFossilPieces;
pub mod NetherFossilStructure;
pub mod OceanMonumentPieces;
pub mod OceanMonumentStructure;
pub mod OceanRuinPieces;
pub mod OceanRuinStructure;
pub mod RuinedPortalPiece;
pub mod RuinedPortalStructure;
pub mod ShipwreckPieces;
pub mod ShipwreckStructure;
pub mod StrongholdPieces;
pub mod StrongholdStructure;
pub mod SwampHutPiece;
pub mod SwampHutStructure;
pub mod WoodlandMansionPieces;
pub mod WoodlandMansionStructure;
#[path = "package-info.rs"]
pub mod package_info;
