//! Module declarations for `net.minecraft.util.filefix.fixes` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod DimensionStorageFileFix;
pub mod GeneratedStructuresRenameFileFix;
pub mod LegacyStructureFileFix;
pub mod LevelDatToSavedDataFileFix;
pub mod PlayerStorageFileFix;
pub mod ReenableSpectatorsGenerateChunksInHardcoreWorldsFileFix;
pub mod RemoveObsoleteFilesFileFix;
pub mod ResourcePackLocationFileFix;
#[path = "package-info.rs"]
pub mod package_info;
