//! Module declarations for `net.minecraft.client.model.monster` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod blaze;
pub mod breeze;
pub mod creaking;
pub mod creeper;
pub mod dragon;
pub mod enderman;
pub mod endermite;
pub mod ghast;
pub mod guardian;
pub mod hoglin;
pub mod illager;
pub mod nautilus;
pub mod phantom;
pub mod piglin;
pub mod ravager;
pub mod shulker;
pub mod silverfish;
pub mod skeleton;
pub mod slime;
pub mod spider;
pub mod strider;
pub mod vex;
pub mod warden;
pub mod witch;
pub mod wither;
pub mod zombie;
