//! Module declarations for `net.minecraft.world.entity.ai.village.poi` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod PoiManager;
pub mod PoiRecord;
pub mod PoiSection;
pub mod PoiType;
pub mod PoiTypes;
#[path = "package-info.rs"]
pub mod package_info;
