//! Module declarations for `net.minecraft.world.entity.npc` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod villager;
pub mod wanderingtrader;

pub mod CatSpawner;
pub mod ClientSideMerchant;
pub mod InventoryCarrier;
pub mod Npc;
#[path = "package-info.rs"]
pub mod package_info;
