//! Module declarations for `net.minecraft.client.model.animal.nautilus` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod NautilusArmorModel;
pub mod NautilusModel;
pub mod NautilusSaddleModel;
#[path = "package-info.rs"]
pub mod package_info;
