//! Module declarations for `net.minecraft.client.multiplayer.resolver` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AddressCheck;
pub mod ResolvedServerAddress;
pub mod ServerAddress;
pub mod ServerAddressResolver;
pub mod ServerNameResolver;
pub mod ServerRedirectHandler;
#[path = "package-info.rs"]
pub mod package_info;
