//! Module declarations for `net.minecraft.client.model.animal.fish` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod CodModel;
pub mod PufferfishBigModel;
pub mod PufferfishMidModel;
pub mod PufferfishSmallModel;
pub mod SalmonModel;
pub mod TropicalFishLargeModel;
pub mod TropicalFishSmallModel;
#[path = "package-info.rs"]
pub mod package_info;
