//! Module declarations for `net.minecraft.advancements.predicates` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod entity;

pub mod BlockPredicate;
pub mod CollectionContentsPredicate;
pub mod CollectionCountsPredicate;
pub mod CollectionPredicate;
pub mod ContextAwarePredicate;
pub mod DamagePredicate;
pub mod DamageSourcePredicate;
pub mod DataComponentMatchers;
pub mod DistancePredicate;
pub mod EnchantmentPredicate;
pub mod FluidPredicate;
pub mod FoodPredicate;
pub mod GameTypePredicate;
pub mod InputPredicate;
pub mod ItemPredicate;
pub mod LightPredicate;
pub mod LocationPredicate;
pub mod MinMaxBounds;
pub mod MobEffectsPredicate;
pub mod NbtPredicate;
pub mod SingleComponentItemPredicate;
pub mod SlotsPredicate;
pub mod StatePropertiesPredicate;
pub mod TagPredicate;
#[path = "package-info.rs"]
pub mod package_info;
