//! Module declarations for `net.minecraft.world.level.storage.loot.entries` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AlternativesEntry;
pub mod ComposableEntryContainer;
pub mod CompositeEntryBase;
pub mod DynamicLoot;
pub mod EmptyLootItem;
pub mod EntryGroup;
pub mod LootItem;
pub mod LootPoolEntries;
pub mod LootPoolEntry;
pub mod LootPoolEntryContainer;
pub mod LootPoolSingletonContainer;
pub mod NestedLootTable;
pub mod SequentialEntry;
pub mod SlotLoot;
pub mod TagEntry;
#[path = "package-info.rs"]
pub mod package_info;
