//! Module declarations for `net.minecraft.world.entity.monster.illager` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod AbstractIllager;
pub mod Evoker;
pub mod Illusioner;
pub mod Pillager;
pub mod SpellcasterIllager;
pub mod Vindicator;
#[path = "package-info.rs"]
pub mod package_info;
