//! Module declarations for `net.minecraft.client.gui.screens` -- generated by _porting/tools/mirror.py.

//
// No game logic in mod.rs -- only child module declarations.
// Child folders first, then sibling files (both mirror minecraft-decompiled/).

pub mod achievement;
pub mod advancements;
pub mod debug;
pub mod dialog;
pub mod friends;
pub mod inventory;
pub mod multiplayer;
pub mod options;
pub mod packs;
pub mod recipebook;
pub mod reporting;
pub mod social;
pub mod telemetry;
pub mod worldselection;

pub mod AccessibilityOnboardingScreen;
pub mod AlertScreen;
pub mod BackupConfirmScreen;
pub mod BanNoticeScreens;
pub mod ChatScreen;
pub mod ConfirmLinkScreen;
pub mod ConfirmScreen;
pub mod ConnectScreen;
pub mod CreateBuffetWorldScreen;
pub mod CreateFlatWorldScreen;
pub mod CreditsAndAttributionScreen;
pub mod DatapackLoadFailureScreen;
pub mod DeathScreen;
pub mod DirectJoinServerScreen;
pub mod DisconnectedScreen;
pub mod ErrorScreen;
pub mod FaviconTexture;
pub mod FileFixerAbortedScreen;
pub mod GenericMessageScreen;
pub mod GenericWaitingScreen;
pub mod InBedChatScreen;
pub mod LevelLoadingScreen;
pub mod LoadingDotsText;
pub mod LoadingOverlay;
pub mod ManageServerScreen;
pub mod MenuScreens;
pub mod MultiplayerOptionsScreen;
pub mod NoticeWithLinkScreen;
pub mod OutOfMemoryScreen;
pub mod Overlay;
pub mod PauseScreen;
pub mod PresetFlatWorldScreen;
pub mod PrivacyConfirmLinkScreen;
pub mod ProgressScreen;
pub mod RecoverWorldDataScreen;
pub mod Screen;
pub mod TitleScreen;
pub mod WinScreen;
#[path = "package-info.rs"]
pub mod package_info;
